// Code generated by ent, DO NOT EDIT.

package promotionscript

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldEQ(FieldName, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldEQ(FieldCategory, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldEQ(FieldContent, v))
}

// UseCount applies equality check predicate on the "use_count" field. It's identical to UseCountEQ.
func UseCount(v int64) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldEQ(FieldUseCount, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldEQ(FieldEnabled, v))
}

// CreatedByUserID applies equality check predicate on the "created_by_user_id" field. It's identical to CreatedByUserIDEQ.
func CreatedByUserID(v int64) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldEQ(FieldCreatedByUserID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldContainsFold(FieldName, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldContainsFold(FieldCategory, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldContainsFold(FieldContent, v))
}

// UseCountEQ applies the EQ predicate on the "use_count" field.
func UseCountEQ(v int64) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldEQ(FieldUseCount, v))
}

// UseCountNEQ applies the NEQ predicate on the "use_count" field.
func UseCountNEQ(v int64) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldNEQ(FieldUseCount, v))
}

// UseCountIn applies the In predicate on the "use_count" field.
func UseCountIn(vs ...int64) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldIn(FieldUseCount, vs...))
}

// UseCountNotIn applies the NotIn predicate on the "use_count" field.
func UseCountNotIn(vs ...int64) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldNotIn(FieldUseCount, vs...))
}

// UseCountGT applies the GT predicate on the "use_count" field.
func UseCountGT(v int64) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldGT(FieldUseCount, v))
}

// UseCountGTE applies the GTE predicate on the "use_count" field.
func UseCountGTE(v int64) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldGTE(FieldUseCount, v))
}

// UseCountLT applies the LT predicate on the "use_count" field.
func UseCountLT(v int64) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldLT(FieldUseCount, v))
}

// UseCountLTE applies the LTE predicate on the "use_count" field.
func UseCountLTE(v int64) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldLTE(FieldUseCount, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldNEQ(FieldEnabled, v))
}

// CreatedByUserIDEQ applies the EQ predicate on the "created_by_user_id" field.
func CreatedByUserIDEQ(v int64) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldEQ(FieldCreatedByUserID, v))
}

// CreatedByUserIDNEQ applies the NEQ predicate on the "created_by_user_id" field.
func CreatedByUserIDNEQ(v int64) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldNEQ(FieldCreatedByUserID, v))
}

// CreatedByUserIDIn applies the In predicate on the "created_by_user_id" field.
func CreatedByUserIDIn(vs ...int64) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldIn(FieldCreatedByUserID, vs...))
}

// CreatedByUserIDNotIn applies the NotIn predicate on the "created_by_user_id" field.
func CreatedByUserIDNotIn(vs ...int64) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldNotIn(FieldCreatedByUserID, vs...))
}

// CreatedByUserIDGT applies the GT predicate on the "created_by_user_id" field.
func CreatedByUserIDGT(v int64) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldGT(FieldCreatedByUserID, v))
}

// CreatedByUserIDGTE applies the GTE predicate on the "created_by_user_id" field.
func CreatedByUserIDGTE(v int64) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldGTE(FieldCreatedByUserID, v))
}

// CreatedByUserIDLT applies the LT predicate on the "created_by_user_id" field.
func CreatedByUserIDLT(v int64) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldLT(FieldCreatedByUserID, v))
}

// CreatedByUserIDLTE applies the LTE predicate on the "created_by_user_id" field.
func CreatedByUserIDLTE(v int64) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldLTE(FieldCreatedByUserID, v))
}

// CreatedByUserIDIsNil applies the IsNil predicate on the "created_by_user_id" field.
func CreatedByUserIDIsNil() predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldIsNull(FieldCreatedByUserID))
}

// CreatedByUserIDNotNil applies the NotNil predicate on the "created_by_user_id" field.
func CreatedByUserIDNotNil() predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldNotNull(FieldCreatedByUserID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PromotionScript {
	return predicate.PromotionScript(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PromotionScript) predicate.PromotionScript {
	return predicate.PromotionScript(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PromotionScript) predicate.PromotionScript {
	return predicate.PromotionScript(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PromotionScript) predicate.PromotionScript {
	return predicate.PromotionScript(sql.NotPredicates(p))
}
