// Code generated by ent, DO NOT EDIT.

package promotionactivation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldLTE(FieldID, id))
}

// PromoterUserID applies equality check predicate on the "promoter_user_id" field. It's identical to PromoterUserIDEQ.
func PromoterUserID(v int64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldEQ(FieldPromoterUserID, v))
}

// ActivatedAt applies equality check predicate on the "activated_at" field. It's identical to ActivatedAtEQ.
func ActivatedAt(v time.Time) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldEQ(FieldActivatedAt, v))
}

// ThresholdAmount applies equality check predicate on the "threshold_amount" field. It's identical to ThresholdAmountEQ.
func ThresholdAmount(v float64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldEQ(FieldThresholdAmount, v))
}

// TriggerUsageAmount applies equality check predicate on the "trigger_usage_amount" field. It's identical to TriggerUsageAmountEQ.
func TriggerUsageAmount(v float64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldEQ(FieldTriggerUsageAmount, v))
}

// CommissionRecordID applies equality check predicate on the "commission_record_id" field. It's identical to CommissionRecordIDEQ.
func CommissionRecordID(v int64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldEQ(FieldCommissionRecordID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldEQ(FieldUpdatedAt, v))
}

// PromoterUserIDEQ applies the EQ predicate on the "promoter_user_id" field.
func PromoterUserIDEQ(v int64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldEQ(FieldPromoterUserID, v))
}

// PromoterUserIDNEQ applies the NEQ predicate on the "promoter_user_id" field.
func PromoterUserIDNEQ(v int64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldNEQ(FieldPromoterUserID, v))
}

// PromoterUserIDIn applies the In predicate on the "promoter_user_id" field.
func PromoterUserIDIn(vs ...int64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldIn(FieldPromoterUserID, vs...))
}

// PromoterUserIDNotIn applies the NotIn predicate on the "promoter_user_id" field.
func PromoterUserIDNotIn(vs ...int64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldNotIn(FieldPromoterUserID, vs...))
}

// PromoterUserIDGT applies the GT predicate on the "promoter_user_id" field.
func PromoterUserIDGT(v int64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldGT(FieldPromoterUserID, v))
}

// PromoterUserIDGTE applies the GTE predicate on the "promoter_user_id" field.
func PromoterUserIDGTE(v int64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldGTE(FieldPromoterUserID, v))
}

// PromoterUserIDLT applies the LT predicate on the "promoter_user_id" field.
func PromoterUserIDLT(v int64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldLT(FieldPromoterUserID, v))
}

// PromoterUserIDLTE applies the LTE predicate on the "promoter_user_id" field.
func PromoterUserIDLTE(v int64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldLTE(FieldPromoterUserID, v))
}

// ActivatedAtEQ applies the EQ predicate on the "activated_at" field.
func ActivatedAtEQ(v time.Time) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldEQ(FieldActivatedAt, v))
}

// ActivatedAtNEQ applies the NEQ predicate on the "activated_at" field.
func ActivatedAtNEQ(v time.Time) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldNEQ(FieldActivatedAt, v))
}

// ActivatedAtIn applies the In predicate on the "activated_at" field.
func ActivatedAtIn(vs ...time.Time) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldIn(FieldActivatedAt, vs...))
}

// ActivatedAtNotIn applies the NotIn predicate on the "activated_at" field.
func ActivatedAtNotIn(vs ...time.Time) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldNotIn(FieldActivatedAt, vs...))
}

// ActivatedAtGT applies the GT predicate on the "activated_at" field.
func ActivatedAtGT(v time.Time) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldGT(FieldActivatedAt, v))
}

// ActivatedAtGTE applies the GTE predicate on the "activated_at" field.
func ActivatedAtGTE(v time.Time) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldGTE(FieldActivatedAt, v))
}

// ActivatedAtLT applies the LT predicate on the "activated_at" field.
func ActivatedAtLT(v time.Time) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldLT(FieldActivatedAt, v))
}

// ActivatedAtLTE applies the LTE predicate on the "activated_at" field.
func ActivatedAtLTE(v time.Time) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldLTE(FieldActivatedAt, v))
}

// ThresholdAmountEQ applies the EQ predicate on the "threshold_amount" field.
func ThresholdAmountEQ(v float64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldEQ(FieldThresholdAmount, v))
}

// ThresholdAmountNEQ applies the NEQ predicate on the "threshold_amount" field.
func ThresholdAmountNEQ(v float64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldNEQ(FieldThresholdAmount, v))
}

// ThresholdAmountIn applies the In predicate on the "threshold_amount" field.
func ThresholdAmountIn(vs ...float64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldIn(FieldThresholdAmount, vs...))
}

// ThresholdAmountNotIn applies the NotIn predicate on the "threshold_amount" field.
func ThresholdAmountNotIn(vs ...float64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldNotIn(FieldThresholdAmount, vs...))
}

// ThresholdAmountGT applies the GT predicate on the "threshold_amount" field.
func ThresholdAmountGT(v float64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldGT(FieldThresholdAmount, v))
}

// ThresholdAmountGTE applies the GTE predicate on the "threshold_amount" field.
func ThresholdAmountGTE(v float64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldGTE(FieldThresholdAmount, v))
}

// ThresholdAmountLT applies the LT predicate on the "threshold_amount" field.
func ThresholdAmountLT(v float64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldLT(FieldThresholdAmount, v))
}

// ThresholdAmountLTE applies the LTE predicate on the "threshold_amount" field.
func ThresholdAmountLTE(v float64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldLTE(FieldThresholdAmount, v))
}

// TriggerUsageAmountEQ applies the EQ predicate on the "trigger_usage_amount" field.
func TriggerUsageAmountEQ(v float64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldEQ(FieldTriggerUsageAmount, v))
}

// TriggerUsageAmountNEQ applies the NEQ predicate on the "trigger_usage_amount" field.
func TriggerUsageAmountNEQ(v float64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldNEQ(FieldTriggerUsageAmount, v))
}

// TriggerUsageAmountIn applies the In predicate on the "trigger_usage_amount" field.
func TriggerUsageAmountIn(vs ...float64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldIn(FieldTriggerUsageAmount, vs...))
}

// TriggerUsageAmountNotIn applies the NotIn predicate on the "trigger_usage_amount" field.
func TriggerUsageAmountNotIn(vs ...float64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldNotIn(FieldTriggerUsageAmount, vs...))
}

// TriggerUsageAmountGT applies the GT predicate on the "trigger_usage_amount" field.
func TriggerUsageAmountGT(v float64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldGT(FieldTriggerUsageAmount, v))
}

// TriggerUsageAmountGTE applies the GTE predicate on the "trigger_usage_amount" field.
func TriggerUsageAmountGTE(v float64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldGTE(FieldTriggerUsageAmount, v))
}

// TriggerUsageAmountLT applies the LT predicate on the "trigger_usage_amount" field.
func TriggerUsageAmountLT(v float64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldLT(FieldTriggerUsageAmount, v))
}

// TriggerUsageAmountLTE applies the LTE predicate on the "trigger_usage_amount" field.
func TriggerUsageAmountLTE(v float64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldLTE(FieldTriggerUsageAmount, v))
}

// CommissionRecordIDEQ applies the EQ predicate on the "commission_record_id" field.
func CommissionRecordIDEQ(v int64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldEQ(FieldCommissionRecordID, v))
}

// CommissionRecordIDNEQ applies the NEQ predicate on the "commission_record_id" field.
func CommissionRecordIDNEQ(v int64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldNEQ(FieldCommissionRecordID, v))
}

// CommissionRecordIDIn applies the In predicate on the "commission_record_id" field.
func CommissionRecordIDIn(vs ...int64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldIn(FieldCommissionRecordID, vs...))
}

// CommissionRecordIDNotIn applies the NotIn predicate on the "commission_record_id" field.
func CommissionRecordIDNotIn(vs ...int64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldNotIn(FieldCommissionRecordID, vs...))
}

// CommissionRecordIDGT applies the GT predicate on the "commission_record_id" field.
func CommissionRecordIDGT(v int64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldGT(FieldCommissionRecordID, v))
}

// CommissionRecordIDGTE applies the GTE predicate on the "commission_record_id" field.
func CommissionRecordIDGTE(v int64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldGTE(FieldCommissionRecordID, v))
}

// CommissionRecordIDLT applies the LT predicate on the "commission_record_id" field.
func CommissionRecordIDLT(v int64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldLT(FieldCommissionRecordID, v))
}

// CommissionRecordIDLTE applies the LTE predicate on the "commission_record_id" field.
func CommissionRecordIDLTE(v int64) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldLTE(FieldCommissionRecordID, v))
}

// CommissionRecordIDIsNil applies the IsNil predicate on the "commission_record_id" field.
func CommissionRecordIDIsNil() predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldIsNull(FieldCommissionRecordID))
}

// CommissionRecordIDNotNil applies the NotNil predicate on the "commission_record_id" field.
func CommissionRecordIDNotNil() predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldNotNull(FieldCommissionRecordID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PromotionActivation) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PromotionActivation) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PromotionActivation) predicate.PromotionActivation {
	return predicate.PromotionActivation(sql.NotPredicates(p))
}
