// Code generated by ent, DO NOT EDIT.

package promotionlevelconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the promotionlevelconfig type in the database.
	Label = "promotion_level_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLevelNo holds the string denoting the level_no field in the database.
	FieldLevelNo = "level_no"
	// FieldLevelName holds the string denoting the level_name field in the database.
	FieldLevelName = "level_name"
	// FieldRequiredActivatedInvites holds the string denoting the required_activated_invites field in the database.
	FieldRequiredActivatedInvites = "required_activated_invites"
	// FieldDirectRate holds the string denoting the direct_rate field in the database.
	FieldDirectRate = "direct_rate"
	// FieldIndirectRate holds the string denoting the indirect_rate field in the database.
	FieldIndirectRate = "indirect_rate"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the promotionlevelconfig in the database.
	Table = "promotion_level_configs"
)

// Columns holds all SQL columns for promotionlevelconfig fields.
var Columns = []string{
	FieldID,
	FieldLevelNo,
	FieldLevelName,
	FieldRequiredActivatedInvites,
	FieldDirectRate,
	FieldIndirectRate,
	FieldSortOrder,
	FieldEnabled,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// LevelNameValidator is a validator for the "level_name" field. It is called by the builders before save.
	LevelNameValidator func(string) error
	// DefaultRequiredActivatedInvites holds the default value on creation for the "required_activated_invites" field.
	DefaultRequiredActivatedInvites int
	// DefaultDirectRate holds the default value on creation for the "direct_rate" field.
	DefaultDirectRate float64
	// DefaultIndirectRate holds the default value on creation for the "indirect_rate" field.
	DefaultIndirectRate float64
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the PromotionLevelConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLevelNo orders the results by the level_no field.
func ByLevelNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLevelNo, opts...).ToFunc()
}

// ByLevelName orders the results by the level_name field.
func ByLevelName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLevelName, opts...).ToFunc()
}

// ByRequiredActivatedInvites orders the results by the required_activated_invites field.
func ByRequiredActivatedInvites(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequiredActivatedInvites, opts...).ToFunc()
}

// ByDirectRate orders the results by the direct_rate field.
func ByDirectRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDirectRate, opts...).ToFunc()
}

// ByIndirectRate orders the results by the indirect_rate field.
func ByIndirectRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIndirectRate, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
