// Code generated by ent, DO NOT EDIT.

package promotionlevelconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldLTE(FieldID, id))
}

// LevelNo applies equality check predicate on the "level_no" field. It's identical to LevelNoEQ.
func LevelNo(v int) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldEQ(FieldLevelNo, v))
}

// LevelName applies equality check predicate on the "level_name" field. It's identical to LevelNameEQ.
func LevelName(v string) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldEQ(FieldLevelName, v))
}

// RequiredActivatedInvites applies equality check predicate on the "required_activated_invites" field. It's identical to RequiredActivatedInvitesEQ.
func RequiredActivatedInvites(v int) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldEQ(FieldRequiredActivatedInvites, v))
}

// DirectRate applies equality check predicate on the "direct_rate" field. It's identical to DirectRateEQ.
func DirectRate(v float64) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldEQ(FieldDirectRate, v))
}

// IndirectRate applies equality check predicate on the "indirect_rate" field. It's identical to IndirectRateEQ.
func IndirectRate(v float64) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldEQ(FieldIndirectRate, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldEQ(FieldSortOrder, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// LevelNoEQ applies the EQ predicate on the "level_no" field.
func LevelNoEQ(v int) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldEQ(FieldLevelNo, v))
}

// LevelNoNEQ applies the NEQ predicate on the "level_no" field.
func LevelNoNEQ(v int) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldNEQ(FieldLevelNo, v))
}

// LevelNoIn applies the In predicate on the "level_no" field.
func LevelNoIn(vs ...int) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldIn(FieldLevelNo, vs...))
}

// LevelNoNotIn applies the NotIn predicate on the "level_no" field.
func LevelNoNotIn(vs ...int) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldNotIn(FieldLevelNo, vs...))
}

// LevelNoGT applies the GT predicate on the "level_no" field.
func LevelNoGT(v int) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldGT(FieldLevelNo, v))
}

// LevelNoGTE applies the GTE predicate on the "level_no" field.
func LevelNoGTE(v int) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldGTE(FieldLevelNo, v))
}

// LevelNoLT applies the LT predicate on the "level_no" field.
func LevelNoLT(v int) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldLT(FieldLevelNo, v))
}

// LevelNoLTE applies the LTE predicate on the "level_no" field.
func LevelNoLTE(v int) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldLTE(FieldLevelNo, v))
}

// LevelNameEQ applies the EQ predicate on the "level_name" field.
func LevelNameEQ(v string) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldEQ(FieldLevelName, v))
}

// LevelNameNEQ applies the NEQ predicate on the "level_name" field.
func LevelNameNEQ(v string) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldNEQ(FieldLevelName, v))
}

// LevelNameIn applies the In predicate on the "level_name" field.
func LevelNameIn(vs ...string) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldIn(FieldLevelName, vs...))
}

// LevelNameNotIn applies the NotIn predicate on the "level_name" field.
func LevelNameNotIn(vs ...string) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldNotIn(FieldLevelName, vs...))
}

// LevelNameGT applies the GT predicate on the "level_name" field.
func LevelNameGT(v string) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldGT(FieldLevelName, v))
}

// LevelNameGTE applies the GTE predicate on the "level_name" field.
func LevelNameGTE(v string) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldGTE(FieldLevelName, v))
}

// LevelNameLT applies the LT predicate on the "level_name" field.
func LevelNameLT(v string) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldLT(FieldLevelName, v))
}

// LevelNameLTE applies the LTE predicate on the "level_name" field.
func LevelNameLTE(v string) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldLTE(FieldLevelName, v))
}

// LevelNameContains applies the Contains predicate on the "level_name" field.
func LevelNameContains(v string) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldContains(FieldLevelName, v))
}

// LevelNameHasPrefix applies the HasPrefix predicate on the "level_name" field.
func LevelNameHasPrefix(v string) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldHasPrefix(FieldLevelName, v))
}

// LevelNameHasSuffix applies the HasSuffix predicate on the "level_name" field.
func LevelNameHasSuffix(v string) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldHasSuffix(FieldLevelName, v))
}

// LevelNameEqualFold applies the EqualFold predicate on the "level_name" field.
func LevelNameEqualFold(v string) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldEqualFold(FieldLevelName, v))
}

// LevelNameContainsFold applies the ContainsFold predicate on the "level_name" field.
func LevelNameContainsFold(v string) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldContainsFold(FieldLevelName, v))
}

// RequiredActivatedInvitesEQ applies the EQ predicate on the "required_activated_invites" field.
func RequiredActivatedInvitesEQ(v int) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldEQ(FieldRequiredActivatedInvites, v))
}

// RequiredActivatedInvitesNEQ applies the NEQ predicate on the "required_activated_invites" field.
func RequiredActivatedInvitesNEQ(v int) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldNEQ(FieldRequiredActivatedInvites, v))
}

// RequiredActivatedInvitesIn applies the In predicate on the "required_activated_invites" field.
func RequiredActivatedInvitesIn(vs ...int) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldIn(FieldRequiredActivatedInvites, vs...))
}

// RequiredActivatedInvitesNotIn applies the NotIn predicate on the "required_activated_invites" field.
func RequiredActivatedInvitesNotIn(vs ...int) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldNotIn(FieldRequiredActivatedInvites, vs...))
}

// RequiredActivatedInvitesGT applies the GT predicate on the "required_activated_invites" field.
func RequiredActivatedInvitesGT(v int) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldGT(FieldRequiredActivatedInvites, v))
}

// RequiredActivatedInvitesGTE applies the GTE predicate on the "required_activated_invites" field.
func RequiredActivatedInvitesGTE(v int) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldGTE(FieldRequiredActivatedInvites, v))
}

// RequiredActivatedInvitesLT applies the LT predicate on the "required_activated_invites" field.
func RequiredActivatedInvitesLT(v int) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldLT(FieldRequiredActivatedInvites, v))
}

// RequiredActivatedInvitesLTE applies the LTE predicate on the "required_activated_invites" field.
func RequiredActivatedInvitesLTE(v int) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldLTE(FieldRequiredActivatedInvites, v))
}

// DirectRateEQ applies the EQ predicate on the "direct_rate" field.
func DirectRateEQ(v float64) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldEQ(FieldDirectRate, v))
}

// DirectRateNEQ applies the NEQ predicate on the "direct_rate" field.
func DirectRateNEQ(v float64) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldNEQ(FieldDirectRate, v))
}

// DirectRateIn applies the In predicate on the "direct_rate" field.
func DirectRateIn(vs ...float64) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldIn(FieldDirectRate, vs...))
}

// DirectRateNotIn applies the NotIn predicate on the "direct_rate" field.
func DirectRateNotIn(vs ...float64) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldNotIn(FieldDirectRate, vs...))
}

// DirectRateGT applies the GT predicate on the "direct_rate" field.
func DirectRateGT(v float64) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldGT(FieldDirectRate, v))
}

// DirectRateGTE applies the GTE predicate on the "direct_rate" field.
func DirectRateGTE(v float64) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldGTE(FieldDirectRate, v))
}

// DirectRateLT applies the LT predicate on the "direct_rate" field.
func DirectRateLT(v float64) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldLT(FieldDirectRate, v))
}

// DirectRateLTE applies the LTE predicate on the "direct_rate" field.
func DirectRateLTE(v float64) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldLTE(FieldDirectRate, v))
}

// IndirectRateEQ applies the EQ predicate on the "indirect_rate" field.
func IndirectRateEQ(v float64) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldEQ(FieldIndirectRate, v))
}

// IndirectRateNEQ applies the NEQ predicate on the "indirect_rate" field.
func IndirectRateNEQ(v float64) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldNEQ(FieldIndirectRate, v))
}

// IndirectRateIn applies the In predicate on the "indirect_rate" field.
func IndirectRateIn(vs ...float64) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldIn(FieldIndirectRate, vs...))
}

// IndirectRateNotIn applies the NotIn predicate on the "indirect_rate" field.
func IndirectRateNotIn(vs ...float64) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldNotIn(FieldIndirectRate, vs...))
}

// IndirectRateGT applies the GT predicate on the "indirect_rate" field.
func IndirectRateGT(v float64) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldGT(FieldIndirectRate, v))
}

// IndirectRateGTE applies the GTE predicate on the "indirect_rate" field.
func IndirectRateGTE(v float64) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldGTE(FieldIndirectRate, v))
}

// IndirectRateLT applies the LT predicate on the "indirect_rate" field.
func IndirectRateLT(v float64) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldLT(FieldIndirectRate, v))
}

// IndirectRateLTE applies the LTE predicate on the "indirect_rate" field.
func IndirectRateLTE(v float64) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldLTE(FieldIndirectRate, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldLTE(FieldSortOrder, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldNEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PromotionLevelConfig) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PromotionLevelConfig) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PromotionLevelConfig) predicate.PromotionLevelConfig {
	return predicate.PromotionLevelConfig(sql.NotPredicates(p))
}
