// Code generated by ent, DO NOT EDIT.

package promotionuser

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldLTE(FieldID, id))
}

// InviteCode applies equality check predicate on the "invite_code" field. It's identical to InviteCodeEQ.
func InviteCode(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldEQ(FieldInviteCode, v))
}

// ParentUserID applies equality check predicate on the "parent_user_id" field. It's identical to ParentUserIDEQ.
func ParentUserID(v int64) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldEQ(FieldParentUserID, v))
}

// BindingSource applies equality check predicate on the "binding_source" field. It's identical to BindingSourceEQ.
func BindingSource(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldEQ(FieldBindingSource, v))
}

// BoundNote applies equality check predicate on the "bound_note" field. It's identical to BoundNoteEQ.
func BoundNote(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldEQ(FieldBoundNote, v))
}

// BoundAt applies equality check predicate on the "bound_at" field. It's identical to BoundAtEQ.
func BoundAt(v time.Time) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldEQ(FieldBoundAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldEQ(FieldUpdatedAt, v))
}

// InviteCodeEQ applies the EQ predicate on the "invite_code" field.
func InviteCodeEQ(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldEQ(FieldInviteCode, v))
}

// InviteCodeNEQ applies the NEQ predicate on the "invite_code" field.
func InviteCodeNEQ(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldNEQ(FieldInviteCode, v))
}

// InviteCodeIn applies the In predicate on the "invite_code" field.
func InviteCodeIn(vs ...string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldIn(FieldInviteCode, vs...))
}

// InviteCodeNotIn applies the NotIn predicate on the "invite_code" field.
func InviteCodeNotIn(vs ...string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldNotIn(FieldInviteCode, vs...))
}

// InviteCodeGT applies the GT predicate on the "invite_code" field.
func InviteCodeGT(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldGT(FieldInviteCode, v))
}

// InviteCodeGTE applies the GTE predicate on the "invite_code" field.
func InviteCodeGTE(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldGTE(FieldInviteCode, v))
}

// InviteCodeLT applies the LT predicate on the "invite_code" field.
func InviteCodeLT(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldLT(FieldInviteCode, v))
}

// InviteCodeLTE applies the LTE predicate on the "invite_code" field.
func InviteCodeLTE(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldLTE(FieldInviteCode, v))
}

// InviteCodeContains applies the Contains predicate on the "invite_code" field.
func InviteCodeContains(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldContains(FieldInviteCode, v))
}

// InviteCodeHasPrefix applies the HasPrefix predicate on the "invite_code" field.
func InviteCodeHasPrefix(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldHasPrefix(FieldInviteCode, v))
}

// InviteCodeHasSuffix applies the HasSuffix predicate on the "invite_code" field.
func InviteCodeHasSuffix(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldHasSuffix(FieldInviteCode, v))
}

// InviteCodeEqualFold applies the EqualFold predicate on the "invite_code" field.
func InviteCodeEqualFold(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldEqualFold(FieldInviteCode, v))
}

// InviteCodeContainsFold applies the ContainsFold predicate on the "invite_code" field.
func InviteCodeContainsFold(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldContainsFold(FieldInviteCode, v))
}

// ParentUserIDEQ applies the EQ predicate on the "parent_user_id" field.
func ParentUserIDEQ(v int64) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldEQ(FieldParentUserID, v))
}

// ParentUserIDNEQ applies the NEQ predicate on the "parent_user_id" field.
func ParentUserIDNEQ(v int64) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldNEQ(FieldParentUserID, v))
}

// ParentUserIDIn applies the In predicate on the "parent_user_id" field.
func ParentUserIDIn(vs ...int64) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldIn(FieldParentUserID, vs...))
}

// ParentUserIDNotIn applies the NotIn predicate on the "parent_user_id" field.
func ParentUserIDNotIn(vs ...int64) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldNotIn(FieldParentUserID, vs...))
}

// ParentUserIDGT applies the GT predicate on the "parent_user_id" field.
func ParentUserIDGT(v int64) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldGT(FieldParentUserID, v))
}

// ParentUserIDGTE applies the GTE predicate on the "parent_user_id" field.
func ParentUserIDGTE(v int64) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldGTE(FieldParentUserID, v))
}

// ParentUserIDLT applies the LT predicate on the "parent_user_id" field.
func ParentUserIDLT(v int64) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldLT(FieldParentUserID, v))
}

// ParentUserIDLTE applies the LTE predicate on the "parent_user_id" field.
func ParentUserIDLTE(v int64) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldLTE(FieldParentUserID, v))
}

// ParentUserIDIsNil applies the IsNil predicate on the "parent_user_id" field.
func ParentUserIDIsNil() predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldIsNull(FieldParentUserID))
}

// ParentUserIDNotNil applies the NotNil predicate on the "parent_user_id" field.
func ParentUserIDNotNil() predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldNotNull(FieldParentUserID))
}

// BindingSourceEQ applies the EQ predicate on the "binding_source" field.
func BindingSourceEQ(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldEQ(FieldBindingSource, v))
}

// BindingSourceNEQ applies the NEQ predicate on the "binding_source" field.
func BindingSourceNEQ(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldNEQ(FieldBindingSource, v))
}

// BindingSourceIn applies the In predicate on the "binding_source" field.
func BindingSourceIn(vs ...string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldIn(FieldBindingSource, vs...))
}

// BindingSourceNotIn applies the NotIn predicate on the "binding_source" field.
func BindingSourceNotIn(vs ...string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldNotIn(FieldBindingSource, vs...))
}

// BindingSourceGT applies the GT predicate on the "binding_source" field.
func BindingSourceGT(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldGT(FieldBindingSource, v))
}

// BindingSourceGTE applies the GTE predicate on the "binding_source" field.
func BindingSourceGTE(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldGTE(FieldBindingSource, v))
}

// BindingSourceLT applies the LT predicate on the "binding_source" field.
func BindingSourceLT(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldLT(FieldBindingSource, v))
}

// BindingSourceLTE applies the LTE predicate on the "binding_source" field.
func BindingSourceLTE(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldLTE(FieldBindingSource, v))
}

// BindingSourceContains applies the Contains predicate on the "binding_source" field.
func BindingSourceContains(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldContains(FieldBindingSource, v))
}

// BindingSourceHasPrefix applies the HasPrefix predicate on the "binding_source" field.
func BindingSourceHasPrefix(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldHasPrefix(FieldBindingSource, v))
}

// BindingSourceHasSuffix applies the HasSuffix predicate on the "binding_source" field.
func BindingSourceHasSuffix(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldHasSuffix(FieldBindingSource, v))
}

// BindingSourceEqualFold applies the EqualFold predicate on the "binding_source" field.
func BindingSourceEqualFold(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldEqualFold(FieldBindingSource, v))
}

// BindingSourceContainsFold applies the ContainsFold predicate on the "binding_source" field.
func BindingSourceContainsFold(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldContainsFold(FieldBindingSource, v))
}

// BoundNoteEQ applies the EQ predicate on the "bound_note" field.
func BoundNoteEQ(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldEQ(FieldBoundNote, v))
}

// BoundNoteNEQ applies the NEQ predicate on the "bound_note" field.
func BoundNoteNEQ(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldNEQ(FieldBoundNote, v))
}

// BoundNoteIn applies the In predicate on the "bound_note" field.
func BoundNoteIn(vs ...string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldIn(FieldBoundNote, vs...))
}

// BoundNoteNotIn applies the NotIn predicate on the "bound_note" field.
func BoundNoteNotIn(vs ...string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldNotIn(FieldBoundNote, vs...))
}

// BoundNoteGT applies the GT predicate on the "bound_note" field.
func BoundNoteGT(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldGT(FieldBoundNote, v))
}

// BoundNoteGTE applies the GTE predicate on the "bound_note" field.
func BoundNoteGTE(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldGTE(FieldBoundNote, v))
}

// BoundNoteLT applies the LT predicate on the "bound_note" field.
func BoundNoteLT(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldLT(FieldBoundNote, v))
}

// BoundNoteLTE applies the LTE predicate on the "bound_note" field.
func BoundNoteLTE(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldLTE(FieldBoundNote, v))
}

// BoundNoteContains applies the Contains predicate on the "bound_note" field.
func BoundNoteContains(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldContains(FieldBoundNote, v))
}

// BoundNoteHasPrefix applies the HasPrefix predicate on the "bound_note" field.
func BoundNoteHasPrefix(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldHasPrefix(FieldBoundNote, v))
}

// BoundNoteHasSuffix applies the HasSuffix predicate on the "bound_note" field.
func BoundNoteHasSuffix(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldHasSuffix(FieldBoundNote, v))
}

// BoundNoteIsNil applies the IsNil predicate on the "bound_note" field.
func BoundNoteIsNil() predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldIsNull(FieldBoundNote))
}

// BoundNoteNotNil applies the NotNil predicate on the "bound_note" field.
func BoundNoteNotNil() predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldNotNull(FieldBoundNote))
}

// BoundNoteEqualFold applies the EqualFold predicate on the "bound_note" field.
func BoundNoteEqualFold(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldEqualFold(FieldBoundNote, v))
}

// BoundNoteContainsFold applies the ContainsFold predicate on the "bound_note" field.
func BoundNoteContainsFold(v string) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldContainsFold(FieldBoundNote, v))
}

// BoundAtEQ applies the EQ predicate on the "bound_at" field.
func BoundAtEQ(v time.Time) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldEQ(FieldBoundAt, v))
}

// BoundAtNEQ applies the NEQ predicate on the "bound_at" field.
func BoundAtNEQ(v time.Time) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldNEQ(FieldBoundAt, v))
}

// BoundAtIn applies the In predicate on the "bound_at" field.
func BoundAtIn(vs ...time.Time) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldIn(FieldBoundAt, vs...))
}

// BoundAtNotIn applies the NotIn predicate on the "bound_at" field.
func BoundAtNotIn(vs ...time.Time) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldNotIn(FieldBoundAt, vs...))
}

// BoundAtGT applies the GT predicate on the "bound_at" field.
func BoundAtGT(v time.Time) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldGT(FieldBoundAt, v))
}

// BoundAtGTE applies the GTE predicate on the "bound_at" field.
func BoundAtGTE(v time.Time) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldGTE(FieldBoundAt, v))
}

// BoundAtLT applies the LT predicate on the "bound_at" field.
func BoundAtLT(v time.Time) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldLT(FieldBoundAt, v))
}

// BoundAtLTE applies the LTE predicate on the "bound_at" field.
func BoundAtLTE(v time.Time) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldLTE(FieldBoundAt, v))
}

// BoundAtIsNil applies the IsNil predicate on the "bound_at" field.
func BoundAtIsNil() predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldIsNull(FieldBoundAt))
}

// BoundAtNotNil applies the NotNil predicate on the "bound_at" field.
func BoundAtNotNil() predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldNotNull(FieldBoundAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PromotionUser {
	return predicate.PromotionUser(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PromotionUser) predicate.PromotionUser {
	return predicate.PromotionUser(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PromotionUser) predicate.PromotionUser {
	return predicate.PromotionUser(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PromotionUser) predicate.PromotionUser {
	return predicate.PromotionUser(sql.NotPredicates(p))
}
