-- Migration: 090_drop_sora
-- Current code no longer uses Sora-related database objects. Keep legacy Sora
-- tables/columns when they exist so low-version upgrades do not destroy
-- historical media/task evidence. Extra legacy objects are ignored by current
-- ent schemas and repositories.
