// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/promotionsetting"
)

// PromotionSettingUpdate is the builder for updating PromotionSetting entities.
type PromotionSettingUpdate struct {
	config
	hooks    []Hook
	mutation *PromotionSettingMutation
}

// Where appends a list predicates to the PromotionSettingUpdate builder.
func (_u *PromotionSettingUpdate) Where(ps ...predicate.PromotionSetting) *PromotionSettingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetActivationThresholdAmount sets the "activation_threshold_amount" field.
func (_u *PromotionSettingUpdate) SetActivationThresholdAmount(v float64) *PromotionSettingUpdate {
	_u.mutation.ResetActivationThresholdAmount()
	_u.mutation.SetActivationThresholdAmount(v)
	return _u
}

// SetNillableActivationThresholdAmount sets the "activation_threshold_amount" field if the given value is not nil.
func (_u *PromotionSettingUpdate) SetNillableActivationThresholdAmount(v *float64) *PromotionSettingUpdate {
	if v != nil {
		_u.SetActivationThresholdAmount(*v)
	}
	return _u
}

// AddActivationThresholdAmount adds value to the "activation_threshold_amount" field.
func (_u *PromotionSettingUpdate) AddActivationThresholdAmount(v float64) *PromotionSettingUpdate {
	_u.mutation.AddActivationThresholdAmount(v)
	return _u
}

// SetActivationBonusAmount sets the "activation_bonus_amount" field.
func (_u *PromotionSettingUpdate) SetActivationBonusAmount(v float64) *PromotionSettingUpdate {
	_u.mutation.ResetActivationBonusAmount()
	_u.mutation.SetActivationBonusAmount(v)
	return _u
}

// SetNillableActivationBonusAmount sets the "activation_bonus_amount" field if the given value is not nil.
func (_u *PromotionSettingUpdate) SetNillableActivationBonusAmount(v *float64) *PromotionSettingUpdate {
	if v != nil {
		_u.SetActivationBonusAmount(*v)
	}
	return _u
}

// AddActivationBonusAmount adds value to the "activation_bonus_amount" field.
func (_u *PromotionSettingUpdate) AddActivationBonusAmount(v float64) *PromotionSettingUpdate {
	_u.mutation.AddActivationBonusAmount(v)
	return _u
}

// SetDailySettlementTime sets the "daily_settlement_time" field.
func (_u *PromotionSettingUpdate) SetDailySettlementTime(v time.Time) *PromotionSettingUpdate {
	_u.mutation.SetDailySettlementTime(v)
	return _u
}

// SetNillableDailySettlementTime sets the "daily_settlement_time" field if the given value is not nil.
func (_u *PromotionSettingUpdate) SetNillableDailySettlementTime(v *time.Time) *PromotionSettingUpdate {
	if v != nil {
		_u.SetDailySettlementTime(*v)
	}
	return _u
}

// SetSettlementEnabled sets the "settlement_enabled" field.
func (_u *PromotionSettingUpdate) SetSettlementEnabled(v bool) *PromotionSettingUpdate {
	_u.mutation.SetSettlementEnabled(v)
	return _u
}

// SetNillableSettlementEnabled sets the "settlement_enabled" field if the given value is not nil.
func (_u *PromotionSettingUpdate) SetNillableSettlementEnabled(v *bool) *PromotionSettingUpdate {
	if v != nil {
		_u.SetSettlementEnabled(*v)
	}
	return _u
}

// SetRuleActivationTemplate sets the "rule_activation_template" field.
func (_u *PromotionSettingUpdate) SetRuleActivationTemplate(v string) *PromotionSettingUpdate {
	_u.mutation.SetRuleActivationTemplate(v)
	return _u
}

// SetNillableRuleActivationTemplate sets the "rule_activation_template" field if the given value is not nil.
func (_u *PromotionSettingUpdate) SetNillableRuleActivationTemplate(v *string) *PromotionSettingUpdate {
	if v != nil {
		_u.SetRuleActivationTemplate(*v)
	}
	return _u
}

// ClearRuleActivationTemplate clears the value of the "rule_activation_template" field.
func (_u *PromotionSettingUpdate) ClearRuleActivationTemplate() *PromotionSettingUpdate {
	_u.mutation.ClearRuleActivationTemplate()
	return _u
}

// SetRuleDirectTemplate sets the "rule_direct_template" field.
func (_u *PromotionSettingUpdate) SetRuleDirectTemplate(v string) *PromotionSettingUpdate {
	_u.mutation.SetRuleDirectTemplate(v)
	return _u
}

// SetNillableRuleDirectTemplate sets the "rule_direct_template" field if the given value is not nil.
func (_u *PromotionSettingUpdate) SetNillableRuleDirectTemplate(v *string) *PromotionSettingUpdate {
	if v != nil {
		_u.SetRuleDirectTemplate(*v)
	}
	return _u
}

// ClearRuleDirectTemplate clears the value of the "rule_direct_template" field.
func (_u *PromotionSettingUpdate) ClearRuleDirectTemplate() *PromotionSettingUpdate {
	_u.mutation.ClearRuleDirectTemplate()
	return _u
}

// SetRuleIndirectTemplate sets the "rule_indirect_template" field.
func (_u *PromotionSettingUpdate) SetRuleIndirectTemplate(v string) *PromotionSettingUpdate {
	_u.mutation.SetRuleIndirectTemplate(v)
	return _u
}

// SetNillableRuleIndirectTemplate sets the "rule_indirect_template" field if the given value is not nil.
func (_u *PromotionSettingUpdate) SetNillableRuleIndirectTemplate(v *string) *PromotionSettingUpdate {
	if v != nil {
		_u.SetRuleIndirectTemplate(*v)
	}
	return _u
}

// ClearRuleIndirectTemplate clears the value of the "rule_indirect_template" field.
func (_u *PromotionSettingUpdate) ClearRuleIndirectTemplate() *PromotionSettingUpdate {
	_u.mutation.ClearRuleIndirectTemplate()
	return _u
}

// SetRuleLevelSummaryTemplate sets the "rule_level_summary_template" field.
func (_u *PromotionSettingUpdate) SetRuleLevelSummaryTemplate(v string) *PromotionSettingUpdate {
	_u.mutation.SetRuleLevelSummaryTemplate(v)
	return _u
}

// SetNillableRuleLevelSummaryTemplate sets the "rule_level_summary_template" field if the given value is not nil.
func (_u *PromotionSettingUpdate) SetNillableRuleLevelSummaryTemplate(v *string) *PromotionSettingUpdate {
	if v != nil {
		_u.SetRuleLevelSummaryTemplate(*v)
	}
	return _u
}

// ClearRuleLevelSummaryTemplate clears the value of the "rule_level_summary_template" field.
func (_u *PromotionSettingUpdate) ClearRuleLevelSummaryTemplate() *PromotionSettingUpdate {
	_u.mutation.ClearRuleLevelSummaryTemplate()
	return _u
}

// SetInviteBaseURL sets the "invite_base_url" field.
func (_u *PromotionSettingUpdate) SetInviteBaseURL(v string) *PromotionSettingUpdate {
	_u.mutation.SetInviteBaseURL(v)
	return _u
}

// SetNillableInviteBaseURL sets the "invite_base_url" field if the given value is not nil.
func (_u *PromotionSettingUpdate) SetNillableInviteBaseURL(v *string) *PromotionSettingUpdate {
	if v != nil {
		_u.SetInviteBaseURL(*v)
	}
	return _u
}

// ClearInviteBaseURL clears the value of the "invite_base_url" field.
func (_u *PromotionSettingUpdate) ClearInviteBaseURL() *PromotionSettingUpdate {
	_u.mutation.ClearInviteBaseURL()
	return _u
}

// SetPosterLogoURL sets the "poster_logo_url" field.
func (_u *PromotionSettingUpdate) SetPosterLogoURL(v string) *PromotionSettingUpdate {
	_u.mutation.SetPosterLogoURL(v)
	return _u
}

// SetNillablePosterLogoURL sets the "poster_logo_url" field if the given value is not nil.
func (_u *PromotionSettingUpdate) SetNillablePosterLogoURL(v *string) *PromotionSettingUpdate {
	if v != nil {
		_u.SetPosterLogoURL(*v)
	}
	return _u
}

// ClearPosterLogoURL clears the value of the "poster_logo_url" field.
func (_u *PromotionSettingUpdate) ClearPosterLogoURL() *PromotionSettingUpdate {
	_u.mutation.ClearPosterLogoURL()
	return _u
}

// SetPosterTitle sets the "poster_title" field.
func (_u *PromotionSettingUpdate) SetPosterTitle(v string) *PromotionSettingUpdate {
	_u.mutation.SetPosterTitle(v)
	return _u
}

// SetNillablePosterTitle sets the "poster_title" field if the given value is not nil.
func (_u *PromotionSettingUpdate) SetNillablePosterTitle(v *string) *PromotionSettingUpdate {
	if v != nil {
		_u.SetPosterTitle(*v)
	}
	return _u
}

// ClearPosterTitle clears the value of the "poster_title" field.
func (_u *PromotionSettingUpdate) ClearPosterTitle() *PromotionSettingUpdate {
	_u.mutation.ClearPosterTitle()
	return _u
}

// SetPosterHeadline sets the "poster_headline" field.
func (_u *PromotionSettingUpdate) SetPosterHeadline(v string) *PromotionSettingUpdate {
	_u.mutation.SetPosterHeadline(v)
	return _u
}

// SetNillablePosterHeadline sets the "poster_headline" field if the given value is not nil.
func (_u *PromotionSettingUpdate) SetNillablePosterHeadline(v *string) *PromotionSettingUpdate {
	if v != nil {
		_u.SetPosterHeadline(*v)
	}
	return _u
}

// ClearPosterHeadline clears the value of the "poster_headline" field.
func (_u *PromotionSettingUpdate) ClearPosterHeadline() *PromotionSettingUpdate {
	_u.mutation.ClearPosterHeadline()
	return _u
}

// SetPosterDescription sets the "poster_description" field.
func (_u *PromotionSettingUpdate) SetPosterDescription(v string) *PromotionSettingUpdate {
	_u.mutation.SetPosterDescription(v)
	return _u
}

// SetNillablePosterDescription sets the "poster_description" field if the given value is not nil.
func (_u *PromotionSettingUpdate) SetNillablePosterDescription(v *string) *PromotionSettingUpdate {
	if v != nil {
		_u.SetPosterDescription(*v)
	}
	return _u
}

// ClearPosterDescription clears the value of the "poster_description" field.
func (_u *PromotionSettingUpdate) ClearPosterDescription() *PromotionSettingUpdate {
	_u.mutation.ClearPosterDescription()
	return _u
}

// SetPosterScanHint sets the "poster_scan_hint" field.
func (_u *PromotionSettingUpdate) SetPosterScanHint(v string) *PromotionSettingUpdate {
	_u.mutation.SetPosterScanHint(v)
	return _u
}

// SetNillablePosterScanHint sets the "poster_scan_hint" field if the given value is not nil.
func (_u *PromotionSettingUpdate) SetNillablePosterScanHint(v *string) *PromotionSettingUpdate {
	if v != nil {
		_u.SetPosterScanHint(*v)
	}
	return _u
}

// ClearPosterScanHint clears the value of the "poster_scan_hint" field.
func (_u *PromotionSettingUpdate) ClearPosterScanHint() *PromotionSettingUpdate {
	_u.mutation.ClearPosterScanHint()
	return _u
}

// SetPosterTagsJSON sets the "poster_tags_json" field.
func (_u *PromotionSettingUpdate) SetPosterTagsJSON(v string) *PromotionSettingUpdate {
	_u.mutation.SetPosterTagsJSON(v)
	return _u
}

// SetNillablePosterTagsJSON sets the "poster_tags_json" field if the given value is not nil.
func (_u *PromotionSettingUpdate) SetNillablePosterTagsJSON(v *string) *PromotionSettingUpdate {
	if v != nil {
		_u.SetPosterTagsJSON(*v)
	}
	return _u
}

// ClearPosterTagsJSON clears the value of the "poster_tags_json" field.
func (_u *PromotionSettingUpdate) ClearPosterTagsJSON() *PromotionSettingUpdate {
	_u.mutation.ClearPosterTagsJSON()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PromotionSettingUpdate) SetUpdatedAt(v time.Time) *PromotionSettingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PromotionSettingMutation object of the builder.
func (_u *PromotionSettingUpdate) Mutation() *PromotionSettingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PromotionSettingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromotionSettingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PromotionSettingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromotionSettingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PromotionSettingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := promotionsetting.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *PromotionSettingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(promotionsetting.Table, promotionsetting.Columns, sqlgraph.NewFieldSpec(promotionsetting.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ActivationThresholdAmount(); ok {
		_spec.SetField(promotionsetting.FieldActivationThresholdAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActivationThresholdAmount(); ok {
		_spec.AddField(promotionsetting.FieldActivationThresholdAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ActivationBonusAmount(); ok {
		_spec.SetField(promotionsetting.FieldActivationBonusAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActivationBonusAmount(); ok {
		_spec.AddField(promotionsetting.FieldActivationBonusAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DailySettlementTime(); ok {
		_spec.SetField(promotionsetting.FieldDailySettlementTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SettlementEnabled(); ok {
		_spec.SetField(promotionsetting.FieldSettlementEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RuleActivationTemplate(); ok {
		_spec.SetField(promotionsetting.FieldRuleActivationTemplate, field.TypeString, value)
	}
	if _u.mutation.RuleActivationTemplateCleared() {
		_spec.ClearField(promotionsetting.FieldRuleActivationTemplate, field.TypeString)
	}
	if value, ok := _u.mutation.RuleDirectTemplate(); ok {
		_spec.SetField(promotionsetting.FieldRuleDirectTemplate, field.TypeString, value)
	}
	if _u.mutation.RuleDirectTemplateCleared() {
		_spec.ClearField(promotionsetting.FieldRuleDirectTemplate, field.TypeString)
	}
	if value, ok := _u.mutation.RuleIndirectTemplate(); ok {
		_spec.SetField(promotionsetting.FieldRuleIndirectTemplate, field.TypeString, value)
	}
	if _u.mutation.RuleIndirectTemplateCleared() {
		_spec.ClearField(promotionsetting.FieldRuleIndirectTemplate, field.TypeString)
	}
	if value, ok := _u.mutation.RuleLevelSummaryTemplate(); ok {
		_spec.SetField(promotionsetting.FieldRuleLevelSummaryTemplate, field.TypeString, value)
	}
	if _u.mutation.RuleLevelSummaryTemplateCleared() {
		_spec.ClearField(promotionsetting.FieldRuleLevelSummaryTemplate, field.TypeString)
	}
	if value, ok := _u.mutation.InviteBaseURL(); ok {
		_spec.SetField(promotionsetting.FieldInviteBaseURL, field.TypeString, value)
	}
	if _u.mutation.InviteBaseURLCleared() {
		_spec.ClearField(promotionsetting.FieldInviteBaseURL, field.TypeString)
	}
	if value, ok := _u.mutation.PosterLogoURL(); ok {
		_spec.SetField(promotionsetting.FieldPosterLogoURL, field.TypeString, value)
	}
	if _u.mutation.PosterLogoURLCleared() {
		_spec.ClearField(promotionsetting.FieldPosterLogoURL, field.TypeString)
	}
	if value, ok := _u.mutation.PosterTitle(); ok {
		_spec.SetField(promotionsetting.FieldPosterTitle, field.TypeString, value)
	}
	if _u.mutation.PosterTitleCleared() {
		_spec.ClearField(promotionsetting.FieldPosterTitle, field.TypeString)
	}
	if value, ok := _u.mutation.PosterHeadline(); ok {
		_spec.SetField(promotionsetting.FieldPosterHeadline, field.TypeString, value)
	}
	if _u.mutation.PosterHeadlineCleared() {
		_spec.ClearField(promotionsetting.FieldPosterHeadline, field.TypeString)
	}
	if value, ok := _u.mutation.PosterDescription(); ok {
		_spec.SetField(promotionsetting.FieldPosterDescription, field.TypeString, value)
	}
	if _u.mutation.PosterDescriptionCleared() {
		_spec.ClearField(promotionsetting.FieldPosterDescription, field.TypeString)
	}
	if value, ok := _u.mutation.PosterScanHint(); ok {
		_spec.SetField(promotionsetting.FieldPosterScanHint, field.TypeString, value)
	}
	if _u.mutation.PosterScanHintCleared() {
		_spec.ClearField(promotionsetting.FieldPosterScanHint, field.TypeString)
	}
	if value, ok := _u.mutation.PosterTagsJSON(); ok {
		_spec.SetField(promotionsetting.FieldPosterTagsJSON, field.TypeString, value)
	}
	if _u.mutation.PosterTagsJSONCleared() {
		_spec.ClearField(promotionsetting.FieldPosterTagsJSON, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(promotionsetting.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{promotionsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PromotionSettingUpdateOne is the builder for updating a single PromotionSetting entity.
type PromotionSettingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PromotionSettingMutation
}

// SetActivationThresholdAmount sets the "activation_threshold_amount" field.
func (_u *PromotionSettingUpdateOne) SetActivationThresholdAmount(v float64) *PromotionSettingUpdateOne {
	_u.mutation.ResetActivationThresholdAmount()
	_u.mutation.SetActivationThresholdAmount(v)
	return _u
}

// SetNillableActivationThresholdAmount sets the "activation_threshold_amount" field if the given value is not nil.
func (_u *PromotionSettingUpdateOne) SetNillableActivationThresholdAmount(v *float64) *PromotionSettingUpdateOne {
	if v != nil {
		_u.SetActivationThresholdAmount(*v)
	}
	return _u
}

// AddActivationThresholdAmount adds value to the "activation_threshold_amount" field.
func (_u *PromotionSettingUpdateOne) AddActivationThresholdAmount(v float64) *PromotionSettingUpdateOne {
	_u.mutation.AddActivationThresholdAmount(v)
	return _u
}

// SetActivationBonusAmount sets the "activation_bonus_amount" field.
func (_u *PromotionSettingUpdateOne) SetActivationBonusAmount(v float64) *PromotionSettingUpdateOne {
	_u.mutation.ResetActivationBonusAmount()
	_u.mutation.SetActivationBonusAmount(v)
	return _u
}

// SetNillableActivationBonusAmount sets the "activation_bonus_amount" field if the given value is not nil.
func (_u *PromotionSettingUpdateOne) SetNillableActivationBonusAmount(v *float64) *PromotionSettingUpdateOne {
	if v != nil {
		_u.SetActivationBonusAmount(*v)
	}
	return _u
}

// AddActivationBonusAmount adds value to the "activation_bonus_amount" field.
func (_u *PromotionSettingUpdateOne) AddActivationBonusAmount(v float64) *PromotionSettingUpdateOne {
	_u.mutation.AddActivationBonusAmount(v)
	return _u
}

// SetDailySettlementTime sets the "daily_settlement_time" field.
func (_u *PromotionSettingUpdateOne) SetDailySettlementTime(v time.Time) *PromotionSettingUpdateOne {
	_u.mutation.SetDailySettlementTime(v)
	return _u
}

// SetNillableDailySettlementTime sets the "daily_settlement_time" field if the given value is not nil.
func (_u *PromotionSettingUpdateOne) SetNillableDailySettlementTime(v *time.Time) *PromotionSettingUpdateOne {
	if v != nil {
		_u.SetDailySettlementTime(*v)
	}
	return _u
}

// SetSettlementEnabled sets the "settlement_enabled" field.
func (_u *PromotionSettingUpdateOne) SetSettlementEnabled(v bool) *PromotionSettingUpdateOne {
	_u.mutation.SetSettlementEnabled(v)
	return _u
}

// SetNillableSettlementEnabled sets the "settlement_enabled" field if the given value is not nil.
func (_u *PromotionSettingUpdateOne) SetNillableSettlementEnabled(v *bool) *PromotionSettingUpdateOne {
	if v != nil {
		_u.SetSettlementEnabled(*v)
	}
	return _u
}

// SetRuleActivationTemplate sets the "rule_activation_template" field.
func (_u *PromotionSettingUpdateOne) SetRuleActivationTemplate(v string) *PromotionSettingUpdateOne {
	_u.mutation.SetRuleActivationTemplate(v)
	return _u
}

// SetNillableRuleActivationTemplate sets the "rule_activation_template" field if the given value is not nil.
func (_u *PromotionSettingUpdateOne) SetNillableRuleActivationTemplate(v *string) *PromotionSettingUpdateOne {
	if v != nil {
		_u.SetRuleActivationTemplate(*v)
	}
	return _u
}

// ClearRuleActivationTemplate clears the value of the "rule_activation_template" field.
func (_u *PromotionSettingUpdateOne) ClearRuleActivationTemplate() *PromotionSettingUpdateOne {
	_u.mutation.ClearRuleActivationTemplate()
	return _u
}

// SetRuleDirectTemplate sets the "rule_direct_template" field.
func (_u *PromotionSettingUpdateOne) SetRuleDirectTemplate(v string) *PromotionSettingUpdateOne {
	_u.mutation.SetRuleDirectTemplate(v)
	return _u
}

// SetNillableRuleDirectTemplate sets the "rule_direct_template" field if the given value is not nil.
func (_u *PromotionSettingUpdateOne) SetNillableRuleDirectTemplate(v *string) *PromotionSettingUpdateOne {
	if v != nil {
		_u.SetRuleDirectTemplate(*v)
	}
	return _u
}

// ClearRuleDirectTemplate clears the value of the "rule_direct_template" field.
func (_u *PromotionSettingUpdateOne) ClearRuleDirectTemplate() *PromotionSettingUpdateOne {
	_u.mutation.ClearRuleDirectTemplate()
	return _u
}

// SetRuleIndirectTemplate sets the "rule_indirect_template" field.
func (_u *PromotionSettingUpdateOne) SetRuleIndirectTemplate(v string) *PromotionSettingUpdateOne {
	_u.mutation.SetRuleIndirectTemplate(v)
	return _u
}

// SetNillableRuleIndirectTemplate sets the "rule_indirect_template" field if the given value is not nil.
func (_u *PromotionSettingUpdateOne) SetNillableRuleIndirectTemplate(v *string) *PromotionSettingUpdateOne {
	if v != nil {
		_u.SetRuleIndirectTemplate(*v)
	}
	return _u
}

// ClearRuleIndirectTemplate clears the value of the "rule_indirect_template" field.
func (_u *PromotionSettingUpdateOne) ClearRuleIndirectTemplate() *PromotionSettingUpdateOne {
	_u.mutation.ClearRuleIndirectTemplate()
	return _u
}

// SetRuleLevelSummaryTemplate sets the "rule_level_summary_template" field.
func (_u *PromotionSettingUpdateOne) SetRuleLevelSummaryTemplate(v string) *PromotionSettingUpdateOne {
	_u.mutation.SetRuleLevelSummaryTemplate(v)
	return _u
}

// SetNillableRuleLevelSummaryTemplate sets the "rule_level_summary_template" field if the given value is not nil.
func (_u *PromotionSettingUpdateOne) SetNillableRuleLevelSummaryTemplate(v *string) *PromotionSettingUpdateOne {
	if v != nil {
		_u.SetRuleLevelSummaryTemplate(*v)
	}
	return _u
}

// ClearRuleLevelSummaryTemplate clears the value of the "rule_level_summary_template" field.
func (_u *PromotionSettingUpdateOne) ClearRuleLevelSummaryTemplate() *PromotionSettingUpdateOne {
	_u.mutation.ClearRuleLevelSummaryTemplate()
	return _u
}

// SetInviteBaseURL sets the "invite_base_url" field.
func (_u *PromotionSettingUpdateOne) SetInviteBaseURL(v string) *PromotionSettingUpdateOne {
	_u.mutation.SetInviteBaseURL(v)
	return _u
}

// SetNillableInviteBaseURL sets the "invite_base_url" field if the given value is not nil.
func (_u *PromotionSettingUpdateOne) SetNillableInviteBaseURL(v *string) *PromotionSettingUpdateOne {
	if v != nil {
		_u.SetInviteBaseURL(*v)
	}
	return _u
}

// ClearInviteBaseURL clears the value of the "invite_base_url" field.
func (_u *PromotionSettingUpdateOne) ClearInviteBaseURL() *PromotionSettingUpdateOne {
	_u.mutation.ClearInviteBaseURL()
	return _u
}

// SetPosterLogoURL sets the "poster_logo_url" field.
func (_u *PromotionSettingUpdateOne) SetPosterLogoURL(v string) *PromotionSettingUpdateOne {
	_u.mutation.SetPosterLogoURL(v)
	return _u
}

// SetNillablePosterLogoURL sets the "poster_logo_url" field if the given value is not nil.
func (_u *PromotionSettingUpdateOne) SetNillablePosterLogoURL(v *string) *PromotionSettingUpdateOne {
	if v != nil {
		_u.SetPosterLogoURL(*v)
	}
	return _u
}

// ClearPosterLogoURL clears the value of the "poster_logo_url" field.
func (_u *PromotionSettingUpdateOne) ClearPosterLogoURL() *PromotionSettingUpdateOne {
	_u.mutation.ClearPosterLogoURL()
	return _u
}

// SetPosterTitle sets the "poster_title" field.
func (_u *PromotionSettingUpdateOne) SetPosterTitle(v string) *PromotionSettingUpdateOne {
	_u.mutation.SetPosterTitle(v)
	return _u
}

// SetNillablePosterTitle sets the "poster_title" field if the given value is not nil.
func (_u *PromotionSettingUpdateOne) SetNillablePosterTitle(v *string) *PromotionSettingUpdateOne {
	if v != nil {
		_u.SetPosterTitle(*v)
	}
	return _u
}

// ClearPosterTitle clears the value of the "poster_title" field.
func (_u *PromotionSettingUpdateOne) ClearPosterTitle() *PromotionSettingUpdateOne {
	_u.mutation.ClearPosterTitle()
	return _u
}

// SetPosterHeadline sets the "poster_headline" field.
func (_u *PromotionSettingUpdateOne) SetPosterHeadline(v string) *PromotionSettingUpdateOne {
	_u.mutation.SetPosterHeadline(v)
	return _u
}

// SetNillablePosterHeadline sets the "poster_headline" field if the given value is not nil.
func (_u *PromotionSettingUpdateOne) SetNillablePosterHeadline(v *string) *PromotionSettingUpdateOne {
	if v != nil {
		_u.SetPosterHeadline(*v)
	}
	return _u
}

// ClearPosterHeadline clears the value of the "poster_headline" field.
func (_u *PromotionSettingUpdateOne) ClearPosterHeadline() *PromotionSettingUpdateOne {
	_u.mutation.ClearPosterHeadline()
	return _u
}

// SetPosterDescription sets the "poster_description" field.
func (_u *PromotionSettingUpdateOne) SetPosterDescription(v string) *PromotionSettingUpdateOne {
	_u.mutation.SetPosterDescription(v)
	return _u
}

// SetNillablePosterDescription sets the "poster_description" field if the given value is not nil.
func (_u *PromotionSettingUpdateOne) SetNillablePosterDescription(v *string) *PromotionSettingUpdateOne {
	if v != nil {
		_u.SetPosterDescription(*v)
	}
	return _u
}

// ClearPosterDescription clears the value of the "poster_description" field.
func (_u *PromotionSettingUpdateOne) ClearPosterDescription() *PromotionSettingUpdateOne {
	_u.mutation.ClearPosterDescription()
	return _u
}

// SetPosterScanHint sets the "poster_scan_hint" field.
func (_u *PromotionSettingUpdateOne) SetPosterScanHint(v string) *PromotionSettingUpdateOne {
	_u.mutation.SetPosterScanHint(v)
	return _u
}

// SetNillablePosterScanHint sets the "poster_scan_hint" field if the given value is not nil.
func (_u *PromotionSettingUpdateOne) SetNillablePosterScanHint(v *string) *PromotionSettingUpdateOne {
	if v != nil {
		_u.SetPosterScanHint(*v)
	}
	return _u
}

// ClearPosterScanHint clears the value of the "poster_scan_hint" field.
func (_u *PromotionSettingUpdateOne) ClearPosterScanHint() *PromotionSettingUpdateOne {
	_u.mutation.ClearPosterScanHint()
	return _u
}

// SetPosterTagsJSON sets the "poster_tags_json" field.
func (_u *PromotionSettingUpdateOne) SetPosterTagsJSON(v string) *PromotionSettingUpdateOne {
	_u.mutation.SetPosterTagsJSON(v)
	return _u
}

// SetNillablePosterTagsJSON sets the "poster_tags_json" field if the given value is not nil.
func (_u *PromotionSettingUpdateOne) SetNillablePosterTagsJSON(v *string) *PromotionSettingUpdateOne {
	if v != nil {
		_u.SetPosterTagsJSON(*v)
	}
	return _u
}

// ClearPosterTagsJSON clears the value of the "poster_tags_json" field.
func (_u *PromotionSettingUpdateOne) ClearPosterTagsJSON() *PromotionSettingUpdateOne {
	_u.mutation.ClearPosterTagsJSON()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PromotionSettingUpdateOne) SetUpdatedAt(v time.Time) *PromotionSettingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PromotionSettingMutation object of the builder.
func (_u *PromotionSettingUpdateOne) Mutation() *PromotionSettingMutation {
	return _u.mutation
}

// Where appends a list predicates to the PromotionSettingUpdate builder.
func (_u *PromotionSettingUpdateOne) Where(ps ...predicate.PromotionSetting) *PromotionSettingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PromotionSettingUpdateOne) Select(field string, fields ...string) *PromotionSettingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PromotionSetting entity.
func (_u *PromotionSettingUpdateOne) Save(ctx context.Context) (*PromotionSetting, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromotionSettingUpdateOne) SaveX(ctx context.Context) *PromotionSetting {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PromotionSettingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromotionSettingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PromotionSettingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := promotionsetting.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *PromotionSettingUpdateOne) sqlSave(ctx context.Context) (_node *PromotionSetting, err error) {
	_spec := sqlgraph.NewUpdateSpec(promotionsetting.Table, promotionsetting.Columns, sqlgraph.NewFieldSpec(promotionsetting.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PromotionSetting.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, promotionsetting.FieldID)
		for _, f := range fields {
			if !promotionsetting.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != promotionsetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ActivationThresholdAmount(); ok {
		_spec.SetField(promotionsetting.FieldActivationThresholdAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActivationThresholdAmount(); ok {
		_spec.AddField(promotionsetting.FieldActivationThresholdAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ActivationBonusAmount(); ok {
		_spec.SetField(promotionsetting.FieldActivationBonusAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActivationBonusAmount(); ok {
		_spec.AddField(promotionsetting.FieldActivationBonusAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DailySettlementTime(); ok {
		_spec.SetField(promotionsetting.FieldDailySettlementTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SettlementEnabled(); ok {
		_spec.SetField(promotionsetting.FieldSettlementEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RuleActivationTemplate(); ok {
		_spec.SetField(promotionsetting.FieldRuleActivationTemplate, field.TypeString, value)
	}
	if _u.mutation.RuleActivationTemplateCleared() {
		_spec.ClearField(promotionsetting.FieldRuleActivationTemplate, field.TypeString)
	}
	if value, ok := _u.mutation.RuleDirectTemplate(); ok {
		_spec.SetField(promotionsetting.FieldRuleDirectTemplate, field.TypeString, value)
	}
	if _u.mutation.RuleDirectTemplateCleared() {
		_spec.ClearField(promotionsetting.FieldRuleDirectTemplate, field.TypeString)
	}
	if value, ok := _u.mutation.RuleIndirectTemplate(); ok {
		_spec.SetField(promotionsetting.FieldRuleIndirectTemplate, field.TypeString, value)
	}
	if _u.mutation.RuleIndirectTemplateCleared() {
		_spec.ClearField(promotionsetting.FieldRuleIndirectTemplate, field.TypeString)
	}
	if value, ok := _u.mutation.RuleLevelSummaryTemplate(); ok {
		_spec.SetField(promotionsetting.FieldRuleLevelSummaryTemplate, field.TypeString, value)
	}
	if _u.mutation.RuleLevelSummaryTemplateCleared() {
		_spec.ClearField(promotionsetting.FieldRuleLevelSummaryTemplate, field.TypeString)
	}
	if value, ok := _u.mutation.InviteBaseURL(); ok {
		_spec.SetField(promotionsetting.FieldInviteBaseURL, field.TypeString, value)
	}
	if _u.mutation.InviteBaseURLCleared() {
		_spec.ClearField(promotionsetting.FieldInviteBaseURL, field.TypeString)
	}
	if value, ok := _u.mutation.PosterLogoURL(); ok {
		_spec.SetField(promotionsetting.FieldPosterLogoURL, field.TypeString, value)
	}
	if _u.mutation.PosterLogoURLCleared() {
		_spec.ClearField(promotionsetting.FieldPosterLogoURL, field.TypeString)
	}
	if value, ok := _u.mutation.PosterTitle(); ok {
		_spec.SetField(promotionsetting.FieldPosterTitle, field.TypeString, value)
	}
	if _u.mutation.PosterTitleCleared() {
		_spec.ClearField(promotionsetting.FieldPosterTitle, field.TypeString)
	}
	if value, ok := _u.mutation.PosterHeadline(); ok {
		_spec.SetField(promotionsetting.FieldPosterHeadline, field.TypeString, value)
	}
	if _u.mutation.PosterHeadlineCleared() {
		_spec.ClearField(promotionsetting.FieldPosterHeadline, field.TypeString)
	}
	if value, ok := _u.mutation.PosterDescription(); ok {
		_spec.SetField(promotionsetting.FieldPosterDescription, field.TypeString, value)
	}
	if _u.mutation.PosterDescriptionCleared() {
		_spec.ClearField(promotionsetting.FieldPosterDescription, field.TypeString)
	}
	if value, ok := _u.mutation.PosterScanHint(); ok {
		_spec.SetField(promotionsetting.FieldPosterScanHint, field.TypeString, value)
	}
	if _u.mutation.PosterScanHintCleared() {
		_spec.ClearField(promotionsetting.FieldPosterScanHint, field.TypeString)
	}
	if value, ok := _u.mutation.PosterTagsJSON(); ok {
		_spec.SetField(promotionsetting.FieldPosterTagsJSON, field.TypeString, value)
	}
	if _u.mutation.PosterTagsJSONCleared() {
		_spec.ClearField(promotionsetting.FieldPosterTagsJSON, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(promotionsetting.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &PromotionSetting{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{promotionsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
