// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/promotionuser"
)

// PromotionUser is the model entity for the PromotionUser schema.
type PromotionUser struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// InviteCode holds the value of the "invite_code" field.
	InviteCode string `json:"invite_code,omitempty"`
	// ParentUserID holds the value of the "parent_user_id" field.
	ParentUserID *int64 `json:"parent_user_id,omitempty"`
	// BindingSource holds the value of the "binding_source" field.
	BindingSource string `json:"binding_source,omitempty"`
	// BoundNote holds the value of the "bound_note" field.
	BoundNote *string `json:"bound_note,omitempty"`
	// BoundAt holds the value of the "bound_at" field.
	BoundAt *time.Time `json:"bound_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PromotionUser) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case promotionuser.FieldID, promotionuser.FieldParentUserID:
			values[i] = new(sql.NullInt64)
		case promotionuser.FieldInviteCode, promotionuser.FieldBindingSource, promotionuser.FieldBoundNote:
			values[i] = new(sql.NullString)
		case promotionuser.FieldBoundAt, promotionuser.FieldCreatedAt, promotionuser.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PromotionUser fields.
func (_m *PromotionUser) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case promotionuser.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case promotionuser.FieldInviteCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invite_code", values[i])
			} else if value.Valid {
				_m.InviteCode = value.String
			}
		case promotionuser.FieldParentUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parent_user_id", values[i])
			} else if value.Valid {
				_m.ParentUserID = new(int64)
				*_m.ParentUserID = value.Int64
			}
		case promotionuser.FieldBindingSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field binding_source", values[i])
			} else if value.Valid {
				_m.BindingSource = value.String
			}
		case promotionuser.FieldBoundNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bound_note", values[i])
			} else if value.Valid {
				_m.BoundNote = new(string)
				*_m.BoundNote = value.String
			}
		case promotionuser.FieldBoundAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field bound_at", values[i])
			} else if value.Valid {
				_m.BoundAt = new(time.Time)
				*_m.BoundAt = value.Time
			}
		case promotionuser.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case promotionuser.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PromotionUser.
// This includes values selected through modifiers, order, etc.
func (_m *PromotionUser) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PromotionUser.
// Note that you need to call PromotionUser.Unwrap() before calling this method if this PromotionUser
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PromotionUser) Update() *PromotionUserUpdateOne {
	return NewPromotionUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PromotionUser entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PromotionUser) Unwrap() *PromotionUser {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PromotionUser is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PromotionUser) String() string {
	var builder strings.Builder
	builder.WriteString("PromotionUser(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("invite_code=")
	builder.WriteString(_m.InviteCode)
	builder.WriteString(", ")
	if v := _m.ParentUserID; v != nil {
		builder.WriteString("parent_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("binding_source=")
	builder.WriteString(_m.BindingSource)
	builder.WriteString(", ")
	if v := _m.BoundNote; v != nil {
		builder.WriteString("bound_note=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.BoundAt; v != nil {
		builder.WriteString("bound_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PromotionUsers is a parsable slice of PromotionUser.
type PromotionUsers []*PromotionUser
