// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/promotionsettlementbatch"
)

// PromotionSettlementBatchCreate is the builder for creating a PromotionSettlementBatch entity.
type PromotionSettlementBatchCreate struct {
	config
	mutation *PromotionSettlementBatchMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetBusinessDate sets the "business_date" field.
func (_c *PromotionSettlementBatchCreate) SetBusinessDate(v time.Time) *PromotionSettlementBatchCreate {
	_c.mutation.SetBusinessDate(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *PromotionSettlementBatchCreate) SetStatus(v string) *PromotionSettlementBatchCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PromotionSettlementBatchCreate) SetNillableStatus(v *string) *PromotionSettlementBatchCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetTotalRecords sets the "total_records" field.
func (_c *PromotionSettlementBatchCreate) SetTotalRecords(v int) *PromotionSettlementBatchCreate {
	_c.mutation.SetTotalRecords(v)
	return _c
}

// SetNillableTotalRecords sets the "total_records" field if the given value is not nil.
func (_c *PromotionSettlementBatchCreate) SetNillableTotalRecords(v *int) *PromotionSettlementBatchCreate {
	if v != nil {
		_c.SetTotalRecords(*v)
	}
	return _c
}

// SetTotalAmount sets the "total_amount" field.
func (_c *PromotionSettlementBatchCreate) SetTotalAmount(v float64) *PromotionSettlementBatchCreate {
	_c.mutation.SetTotalAmount(v)
	return _c
}

// SetNillableTotalAmount sets the "total_amount" field if the given value is not nil.
func (_c *PromotionSettlementBatchCreate) SetNillableTotalAmount(v *float64) *PromotionSettlementBatchCreate {
	if v != nil {
		_c.SetTotalAmount(*v)
	}
	return _c
}

// SetExecutedByUserID sets the "executed_by_user_id" field.
func (_c *PromotionSettlementBatchCreate) SetExecutedByUserID(v int64) *PromotionSettlementBatchCreate {
	_c.mutation.SetExecutedByUserID(v)
	return _c
}

// SetNillableExecutedByUserID sets the "executed_by_user_id" field if the given value is not nil.
func (_c *PromotionSettlementBatchCreate) SetNillableExecutedByUserID(v *int64) *PromotionSettlementBatchCreate {
	if v != nil {
		_c.SetExecutedByUserID(*v)
	}
	return _c
}

// SetExecutedAt sets the "executed_at" field.
func (_c *PromotionSettlementBatchCreate) SetExecutedAt(v time.Time) *PromotionSettlementBatchCreate {
	_c.mutation.SetExecutedAt(v)
	return _c
}

// SetNillableExecutedAt sets the "executed_at" field if the given value is not nil.
func (_c *PromotionSettlementBatchCreate) SetNillableExecutedAt(v *time.Time) *PromotionSettlementBatchCreate {
	if v != nil {
		_c.SetExecutedAt(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *PromotionSettlementBatchCreate) SetNote(v string) *PromotionSettlementBatchCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *PromotionSettlementBatchCreate) SetNillableNote(v *string) *PromotionSettlementBatchCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PromotionSettlementBatchCreate) SetCreatedAt(v time.Time) *PromotionSettlementBatchCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PromotionSettlementBatchCreate) SetNillableCreatedAt(v *time.Time) *PromotionSettlementBatchCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PromotionSettlementBatchCreate) SetUpdatedAt(v time.Time) *PromotionSettlementBatchCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PromotionSettlementBatchCreate) SetNillableUpdatedAt(v *time.Time) *PromotionSettlementBatchCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PromotionSettlementBatchCreate) SetID(v int64) *PromotionSettlementBatchCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the PromotionSettlementBatchMutation object of the builder.
func (_c *PromotionSettlementBatchCreate) Mutation() *PromotionSettlementBatchMutation {
	return _c.mutation
}

// Save creates the PromotionSettlementBatch in the database.
func (_c *PromotionSettlementBatchCreate) Save(ctx context.Context) (*PromotionSettlementBatch, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PromotionSettlementBatchCreate) SaveX(ctx context.Context) *PromotionSettlementBatch {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromotionSettlementBatchCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromotionSettlementBatchCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PromotionSettlementBatchCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := promotionsettlementbatch.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.TotalRecords(); !ok {
		v := promotionsettlementbatch.DefaultTotalRecords
		_c.mutation.SetTotalRecords(v)
	}
	if _, ok := _c.mutation.TotalAmount(); !ok {
		v := promotionsettlementbatch.DefaultTotalAmount
		_c.mutation.SetTotalAmount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := promotionsettlementbatch.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := promotionsettlementbatch.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PromotionSettlementBatchCreate) check() error {
	if _, ok := _c.mutation.BusinessDate(); !ok {
		return &ValidationError{Name: "business_date", err: errors.New(`ent: missing required field "PromotionSettlementBatch.business_date"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PromotionSettlementBatch.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := promotionsettlementbatch.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PromotionSettlementBatch.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TotalRecords(); !ok {
		return &ValidationError{Name: "total_records", err: errors.New(`ent: missing required field "PromotionSettlementBatch.total_records"`)}
	}
	if _, ok := _c.mutation.TotalAmount(); !ok {
		return &ValidationError{Name: "total_amount", err: errors.New(`ent: missing required field "PromotionSettlementBatch.total_amount"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PromotionSettlementBatch.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PromotionSettlementBatch.updated_at"`)}
	}
	return nil
}

func (_c *PromotionSettlementBatchCreate) sqlSave(ctx context.Context) (*PromotionSettlementBatch, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PromotionSettlementBatchCreate) createSpec() (*PromotionSettlementBatch, *sqlgraph.CreateSpec) {
	var (
		_node = &PromotionSettlementBatch{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(promotionsettlementbatch.Table, sqlgraph.NewFieldSpec(promotionsettlementbatch.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.BusinessDate(); ok {
		_spec.SetField(promotionsettlementbatch.FieldBusinessDate, field.TypeTime, value)
		_node.BusinessDate = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(promotionsettlementbatch.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.TotalRecords(); ok {
		_spec.SetField(promotionsettlementbatch.FieldTotalRecords, field.TypeInt, value)
		_node.TotalRecords = value
	}
	if value, ok := _c.mutation.TotalAmount(); ok {
		_spec.SetField(promotionsettlementbatch.FieldTotalAmount, field.TypeFloat64, value)
		_node.TotalAmount = value
	}
	if value, ok := _c.mutation.ExecutedByUserID(); ok {
		_spec.SetField(promotionsettlementbatch.FieldExecutedByUserID, field.TypeInt64, value)
		_node.ExecutedByUserID = &value
	}
	if value, ok := _c.mutation.ExecutedAt(); ok {
		_spec.SetField(promotionsettlementbatch.FieldExecutedAt, field.TypeTime, value)
		_node.ExecutedAt = &value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(promotionsettlementbatch.FieldNote, field.TypeString, value)
		_node.Note = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(promotionsettlementbatch.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(promotionsettlementbatch.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PromotionSettlementBatch.Create().
//		SetBusinessDate(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromotionSettlementBatchUpsert) {
//			SetBusinessDate(v+v).
//		}).
//		Exec(ctx)
func (_c *PromotionSettlementBatchCreate) OnConflict(opts ...sql.ConflictOption) *PromotionSettlementBatchUpsertOne {
	_c.conflict = opts
	return &PromotionSettlementBatchUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PromotionSettlementBatch.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromotionSettlementBatchCreate) OnConflictColumns(columns ...string) *PromotionSettlementBatchUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromotionSettlementBatchUpsertOne{
		create: _c,
	}
}

type (
	// PromotionSettlementBatchUpsertOne is the builder for "upsert"-ing
	//  one PromotionSettlementBatch node.
	PromotionSettlementBatchUpsertOne struct {
		create *PromotionSettlementBatchCreate
	}

	// PromotionSettlementBatchUpsert is the "OnConflict" setter.
	PromotionSettlementBatchUpsert struct {
		*sql.UpdateSet
	}
)

// SetBusinessDate sets the "business_date" field.
func (u *PromotionSettlementBatchUpsert) SetBusinessDate(v time.Time) *PromotionSettlementBatchUpsert {
	u.Set(promotionsettlementbatch.FieldBusinessDate, v)
	return u
}

// UpdateBusinessDate sets the "business_date" field to the value that was provided on create.
func (u *PromotionSettlementBatchUpsert) UpdateBusinessDate() *PromotionSettlementBatchUpsert {
	u.SetExcluded(promotionsettlementbatch.FieldBusinessDate)
	return u
}

// SetStatus sets the "status" field.
func (u *PromotionSettlementBatchUpsert) SetStatus(v string) *PromotionSettlementBatchUpsert {
	u.Set(promotionsettlementbatch.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PromotionSettlementBatchUpsert) UpdateStatus() *PromotionSettlementBatchUpsert {
	u.SetExcluded(promotionsettlementbatch.FieldStatus)
	return u
}

// SetTotalRecords sets the "total_records" field.
func (u *PromotionSettlementBatchUpsert) SetTotalRecords(v int) *PromotionSettlementBatchUpsert {
	u.Set(promotionsettlementbatch.FieldTotalRecords, v)
	return u
}

// UpdateTotalRecords sets the "total_records" field to the value that was provided on create.
func (u *PromotionSettlementBatchUpsert) UpdateTotalRecords() *PromotionSettlementBatchUpsert {
	u.SetExcluded(promotionsettlementbatch.FieldTotalRecords)
	return u
}

// AddTotalRecords adds v to the "total_records" field.
func (u *PromotionSettlementBatchUpsert) AddTotalRecords(v int) *PromotionSettlementBatchUpsert {
	u.Add(promotionsettlementbatch.FieldTotalRecords, v)
	return u
}

// SetTotalAmount sets the "total_amount" field.
func (u *PromotionSettlementBatchUpsert) SetTotalAmount(v float64) *PromotionSettlementBatchUpsert {
	u.Set(promotionsettlementbatch.FieldTotalAmount, v)
	return u
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *PromotionSettlementBatchUpsert) UpdateTotalAmount() *PromotionSettlementBatchUpsert {
	u.SetExcluded(promotionsettlementbatch.FieldTotalAmount)
	return u
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *PromotionSettlementBatchUpsert) AddTotalAmount(v float64) *PromotionSettlementBatchUpsert {
	u.Add(promotionsettlementbatch.FieldTotalAmount, v)
	return u
}

// SetExecutedByUserID sets the "executed_by_user_id" field.
func (u *PromotionSettlementBatchUpsert) SetExecutedByUserID(v int64) *PromotionSettlementBatchUpsert {
	u.Set(promotionsettlementbatch.FieldExecutedByUserID, v)
	return u
}

// UpdateExecutedByUserID sets the "executed_by_user_id" field to the value that was provided on create.
func (u *PromotionSettlementBatchUpsert) UpdateExecutedByUserID() *PromotionSettlementBatchUpsert {
	u.SetExcluded(promotionsettlementbatch.FieldExecutedByUserID)
	return u
}

// AddExecutedByUserID adds v to the "executed_by_user_id" field.
func (u *PromotionSettlementBatchUpsert) AddExecutedByUserID(v int64) *PromotionSettlementBatchUpsert {
	u.Add(promotionsettlementbatch.FieldExecutedByUserID, v)
	return u
}

// ClearExecutedByUserID clears the value of the "executed_by_user_id" field.
func (u *PromotionSettlementBatchUpsert) ClearExecutedByUserID() *PromotionSettlementBatchUpsert {
	u.SetNull(promotionsettlementbatch.FieldExecutedByUserID)
	return u
}

// SetExecutedAt sets the "executed_at" field.
func (u *PromotionSettlementBatchUpsert) SetExecutedAt(v time.Time) *PromotionSettlementBatchUpsert {
	u.Set(promotionsettlementbatch.FieldExecutedAt, v)
	return u
}

// UpdateExecutedAt sets the "executed_at" field to the value that was provided on create.
func (u *PromotionSettlementBatchUpsert) UpdateExecutedAt() *PromotionSettlementBatchUpsert {
	u.SetExcluded(promotionsettlementbatch.FieldExecutedAt)
	return u
}

// ClearExecutedAt clears the value of the "executed_at" field.
func (u *PromotionSettlementBatchUpsert) ClearExecutedAt() *PromotionSettlementBatchUpsert {
	u.SetNull(promotionsettlementbatch.FieldExecutedAt)
	return u
}

// SetNote sets the "note" field.
func (u *PromotionSettlementBatchUpsert) SetNote(v string) *PromotionSettlementBatchUpsert {
	u.Set(promotionsettlementbatch.FieldNote, v)
	return u
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *PromotionSettlementBatchUpsert) UpdateNote() *PromotionSettlementBatchUpsert {
	u.SetExcluded(promotionsettlementbatch.FieldNote)
	return u
}

// ClearNote clears the value of the "note" field.
func (u *PromotionSettlementBatchUpsert) ClearNote() *PromotionSettlementBatchUpsert {
	u.SetNull(promotionsettlementbatch.FieldNote)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromotionSettlementBatchUpsert) SetUpdatedAt(v time.Time) *PromotionSettlementBatchUpsert {
	u.Set(promotionsettlementbatch.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromotionSettlementBatchUpsert) UpdateUpdatedAt() *PromotionSettlementBatchUpsert {
	u.SetExcluded(promotionsettlementbatch.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PromotionSettlementBatch.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(promotionsettlementbatch.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PromotionSettlementBatchUpsertOne) UpdateNewValues() *PromotionSettlementBatchUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(promotionsettlementbatch.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(promotionsettlementbatch.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PromotionSettlementBatch.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PromotionSettlementBatchUpsertOne) Ignore() *PromotionSettlementBatchUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromotionSettlementBatchUpsertOne) DoNothing() *PromotionSettlementBatchUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromotionSettlementBatchCreate.OnConflict
// documentation for more info.
func (u *PromotionSettlementBatchUpsertOne) Update(set func(*PromotionSettlementBatchUpsert)) *PromotionSettlementBatchUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromotionSettlementBatchUpsert{UpdateSet: update})
	}))
	return u
}

// SetBusinessDate sets the "business_date" field.
func (u *PromotionSettlementBatchUpsertOne) SetBusinessDate(v time.Time) *PromotionSettlementBatchUpsertOne {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.SetBusinessDate(v)
	})
}

// UpdateBusinessDate sets the "business_date" field to the value that was provided on create.
func (u *PromotionSettlementBatchUpsertOne) UpdateBusinessDate() *PromotionSettlementBatchUpsertOne {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.UpdateBusinessDate()
	})
}

// SetStatus sets the "status" field.
func (u *PromotionSettlementBatchUpsertOne) SetStatus(v string) *PromotionSettlementBatchUpsertOne {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PromotionSettlementBatchUpsertOne) UpdateStatus() *PromotionSettlementBatchUpsertOne {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.UpdateStatus()
	})
}

// SetTotalRecords sets the "total_records" field.
func (u *PromotionSettlementBatchUpsertOne) SetTotalRecords(v int) *PromotionSettlementBatchUpsertOne {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.SetTotalRecords(v)
	})
}

// AddTotalRecords adds v to the "total_records" field.
func (u *PromotionSettlementBatchUpsertOne) AddTotalRecords(v int) *PromotionSettlementBatchUpsertOne {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.AddTotalRecords(v)
	})
}

// UpdateTotalRecords sets the "total_records" field to the value that was provided on create.
func (u *PromotionSettlementBatchUpsertOne) UpdateTotalRecords() *PromotionSettlementBatchUpsertOne {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.UpdateTotalRecords()
	})
}

// SetTotalAmount sets the "total_amount" field.
func (u *PromotionSettlementBatchUpsertOne) SetTotalAmount(v float64) *PromotionSettlementBatchUpsertOne {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.SetTotalAmount(v)
	})
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *PromotionSettlementBatchUpsertOne) AddTotalAmount(v float64) *PromotionSettlementBatchUpsertOne {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.AddTotalAmount(v)
	})
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *PromotionSettlementBatchUpsertOne) UpdateTotalAmount() *PromotionSettlementBatchUpsertOne {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.UpdateTotalAmount()
	})
}

// SetExecutedByUserID sets the "executed_by_user_id" field.
func (u *PromotionSettlementBatchUpsertOne) SetExecutedByUserID(v int64) *PromotionSettlementBatchUpsertOne {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.SetExecutedByUserID(v)
	})
}

// AddExecutedByUserID adds v to the "executed_by_user_id" field.
func (u *PromotionSettlementBatchUpsertOne) AddExecutedByUserID(v int64) *PromotionSettlementBatchUpsertOne {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.AddExecutedByUserID(v)
	})
}

// UpdateExecutedByUserID sets the "executed_by_user_id" field to the value that was provided on create.
func (u *PromotionSettlementBatchUpsertOne) UpdateExecutedByUserID() *PromotionSettlementBatchUpsertOne {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.UpdateExecutedByUserID()
	})
}

// ClearExecutedByUserID clears the value of the "executed_by_user_id" field.
func (u *PromotionSettlementBatchUpsertOne) ClearExecutedByUserID() *PromotionSettlementBatchUpsertOne {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.ClearExecutedByUserID()
	})
}

// SetExecutedAt sets the "executed_at" field.
func (u *PromotionSettlementBatchUpsertOne) SetExecutedAt(v time.Time) *PromotionSettlementBatchUpsertOne {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.SetExecutedAt(v)
	})
}

// UpdateExecutedAt sets the "executed_at" field to the value that was provided on create.
func (u *PromotionSettlementBatchUpsertOne) UpdateExecutedAt() *PromotionSettlementBatchUpsertOne {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.UpdateExecutedAt()
	})
}

// ClearExecutedAt clears the value of the "executed_at" field.
func (u *PromotionSettlementBatchUpsertOne) ClearExecutedAt() *PromotionSettlementBatchUpsertOne {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.ClearExecutedAt()
	})
}

// SetNote sets the "note" field.
func (u *PromotionSettlementBatchUpsertOne) SetNote(v string) *PromotionSettlementBatchUpsertOne {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *PromotionSettlementBatchUpsertOne) UpdateNote() *PromotionSettlementBatchUpsertOne {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.UpdateNote()
	})
}

// ClearNote clears the value of the "note" field.
func (u *PromotionSettlementBatchUpsertOne) ClearNote() *PromotionSettlementBatchUpsertOne {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.ClearNote()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromotionSettlementBatchUpsertOne) SetUpdatedAt(v time.Time) *PromotionSettlementBatchUpsertOne {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromotionSettlementBatchUpsertOne) UpdateUpdatedAt() *PromotionSettlementBatchUpsertOne {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PromotionSettlementBatchUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromotionSettlementBatchCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromotionSettlementBatchUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PromotionSettlementBatchUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PromotionSettlementBatchUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PromotionSettlementBatchCreateBulk is the builder for creating many PromotionSettlementBatch entities in bulk.
type PromotionSettlementBatchCreateBulk struct {
	config
	err      error
	builders []*PromotionSettlementBatchCreate
	conflict []sql.ConflictOption
}

// Save creates the PromotionSettlementBatch entities in the database.
func (_c *PromotionSettlementBatchCreateBulk) Save(ctx context.Context) ([]*PromotionSettlementBatch, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PromotionSettlementBatch, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PromotionSettlementBatchMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PromotionSettlementBatchCreateBulk) SaveX(ctx context.Context) []*PromotionSettlementBatch {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromotionSettlementBatchCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromotionSettlementBatchCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PromotionSettlementBatch.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromotionSettlementBatchUpsert) {
//			SetBusinessDate(v+v).
//		}).
//		Exec(ctx)
func (_c *PromotionSettlementBatchCreateBulk) OnConflict(opts ...sql.ConflictOption) *PromotionSettlementBatchUpsertBulk {
	_c.conflict = opts
	return &PromotionSettlementBatchUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PromotionSettlementBatch.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromotionSettlementBatchCreateBulk) OnConflictColumns(columns ...string) *PromotionSettlementBatchUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromotionSettlementBatchUpsertBulk{
		create: _c,
	}
}

// PromotionSettlementBatchUpsertBulk is the builder for "upsert"-ing
// a bulk of PromotionSettlementBatch nodes.
type PromotionSettlementBatchUpsertBulk struct {
	create *PromotionSettlementBatchCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PromotionSettlementBatch.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(promotionsettlementbatch.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PromotionSettlementBatchUpsertBulk) UpdateNewValues() *PromotionSettlementBatchUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(promotionsettlementbatch.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(promotionsettlementbatch.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PromotionSettlementBatch.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PromotionSettlementBatchUpsertBulk) Ignore() *PromotionSettlementBatchUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromotionSettlementBatchUpsertBulk) DoNothing() *PromotionSettlementBatchUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromotionSettlementBatchCreateBulk.OnConflict
// documentation for more info.
func (u *PromotionSettlementBatchUpsertBulk) Update(set func(*PromotionSettlementBatchUpsert)) *PromotionSettlementBatchUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromotionSettlementBatchUpsert{UpdateSet: update})
	}))
	return u
}

// SetBusinessDate sets the "business_date" field.
func (u *PromotionSettlementBatchUpsertBulk) SetBusinessDate(v time.Time) *PromotionSettlementBatchUpsertBulk {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.SetBusinessDate(v)
	})
}

// UpdateBusinessDate sets the "business_date" field to the value that was provided on create.
func (u *PromotionSettlementBatchUpsertBulk) UpdateBusinessDate() *PromotionSettlementBatchUpsertBulk {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.UpdateBusinessDate()
	})
}

// SetStatus sets the "status" field.
func (u *PromotionSettlementBatchUpsertBulk) SetStatus(v string) *PromotionSettlementBatchUpsertBulk {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PromotionSettlementBatchUpsertBulk) UpdateStatus() *PromotionSettlementBatchUpsertBulk {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.UpdateStatus()
	})
}

// SetTotalRecords sets the "total_records" field.
func (u *PromotionSettlementBatchUpsertBulk) SetTotalRecords(v int) *PromotionSettlementBatchUpsertBulk {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.SetTotalRecords(v)
	})
}

// AddTotalRecords adds v to the "total_records" field.
func (u *PromotionSettlementBatchUpsertBulk) AddTotalRecords(v int) *PromotionSettlementBatchUpsertBulk {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.AddTotalRecords(v)
	})
}

// UpdateTotalRecords sets the "total_records" field to the value that was provided on create.
func (u *PromotionSettlementBatchUpsertBulk) UpdateTotalRecords() *PromotionSettlementBatchUpsertBulk {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.UpdateTotalRecords()
	})
}

// SetTotalAmount sets the "total_amount" field.
func (u *PromotionSettlementBatchUpsertBulk) SetTotalAmount(v float64) *PromotionSettlementBatchUpsertBulk {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.SetTotalAmount(v)
	})
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *PromotionSettlementBatchUpsertBulk) AddTotalAmount(v float64) *PromotionSettlementBatchUpsertBulk {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.AddTotalAmount(v)
	})
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *PromotionSettlementBatchUpsertBulk) UpdateTotalAmount() *PromotionSettlementBatchUpsertBulk {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.UpdateTotalAmount()
	})
}

// SetExecutedByUserID sets the "executed_by_user_id" field.
func (u *PromotionSettlementBatchUpsertBulk) SetExecutedByUserID(v int64) *PromotionSettlementBatchUpsertBulk {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.SetExecutedByUserID(v)
	})
}

// AddExecutedByUserID adds v to the "executed_by_user_id" field.
func (u *PromotionSettlementBatchUpsertBulk) AddExecutedByUserID(v int64) *PromotionSettlementBatchUpsertBulk {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.AddExecutedByUserID(v)
	})
}

// UpdateExecutedByUserID sets the "executed_by_user_id" field to the value that was provided on create.
func (u *PromotionSettlementBatchUpsertBulk) UpdateExecutedByUserID() *PromotionSettlementBatchUpsertBulk {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.UpdateExecutedByUserID()
	})
}

// ClearExecutedByUserID clears the value of the "executed_by_user_id" field.
func (u *PromotionSettlementBatchUpsertBulk) ClearExecutedByUserID() *PromotionSettlementBatchUpsertBulk {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.ClearExecutedByUserID()
	})
}

// SetExecutedAt sets the "executed_at" field.
func (u *PromotionSettlementBatchUpsertBulk) SetExecutedAt(v time.Time) *PromotionSettlementBatchUpsertBulk {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.SetExecutedAt(v)
	})
}

// UpdateExecutedAt sets the "executed_at" field to the value that was provided on create.
func (u *PromotionSettlementBatchUpsertBulk) UpdateExecutedAt() *PromotionSettlementBatchUpsertBulk {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.UpdateExecutedAt()
	})
}

// ClearExecutedAt clears the value of the "executed_at" field.
func (u *PromotionSettlementBatchUpsertBulk) ClearExecutedAt() *PromotionSettlementBatchUpsertBulk {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.ClearExecutedAt()
	})
}

// SetNote sets the "note" field.
func (u *PromotionSettlementBatchUpsertBulk) SetNote(v string) *PromotionSettlementBatchUpsertBulk {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *PromotionSettlementBatchUpsertBulk) UpdateNote() *PromotionSettlementBatchUpsertBulk {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.UpdateNote()
	})
}

// ClearNote clears the value of the "note" field.
func (u *PromotionSettlementBatchUpsertBulk) ClearNote() *PromotionSettlementBatchUpsertBulk {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.ClearNote()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromotionSettlementBatchUpsertBulk) SetUpdatedAt(v time.Time) *PromotionSettlementBatchUpsertBulk {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromotionSettlementBatchUpsertBulk) UpdateUpdatedAt() *PromotionSettlementBatchUpsertBulk {
	return u.Update(func(s *PromotionSettlementBatchUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PromotionSettlementBatchUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PromotionSettlementBatchCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromotionSettlementBatchCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromotionSettlementBatchUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
