// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/promotionsettlementbatch"
)

// PromotionSettlementBatch is the model entity for the PromotionSettlementBatch schema.
type PromotionSettlementBatch struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// BusinessDate holds the value of the "business_date" field.
	BusinessDate time.Time `json:"business_date,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// TotalRecords holds the value of the "total_records" field.
	TotalRecords int `json:"total_records,omitempty"`
	// TotalAmount holds the value of the "total_amount" field.
	TotalAmount float64 `json:"total_amount,omitempty"`
	// ExecutedByUserID holds the value of the "executed_by_user_id" field.
	ExecutedByUserID *int64 `json:"executed_by_user_id,omitempty"`
	// ExecutedAt holds the value of the "executed_at" field.
	ExecutedAt *time.Time `json:"executed_at,omitempty"`
	// Note holds the value of the "note" field.
	Note *string `json:"note,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PromotionSettlementBatch) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case promotionsettlementbatch.FieldTotalAmount:
			values[i] = new(sql.NullFloat64)
		case promotionsettlementbatch.FieldID, promotionsettlementbatch.FieldTotalRecords, promotionsettlementbatch.FieldExecutedByUserID:
			values[i] = new(sql.NullInt64)
		case promotionsettlementbatch.FieldStatus, promotionsettlementbatch.FieldNote:
			values[i] = new(sql.NullString)
		case promotionsettlementbatch.FieldBusinessDate, promotionsettlementbatch.FieldExecutedAt, promotionsettlementbatch.FieldCreatedAt, promotionsettlementbatch.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PromotionSettlementBatch fields.
func (_m *PromotionSettlementBatch) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case promotionsettlementbatch.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case promotionsettlementbatch.FieldBusinessDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field business_date", values[i])
			} else if value.Valid {
				_m.BusinessDate = value.Time
			}
		case promotionsettlementbatch.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case promotionsettlementbatch.FieldTotalRecords:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_records", values[i])
			} else if value.Valid {
				_m.TotalRecords = int(value.Int64)
			}
		case promotionsettlementbatch.FieldTotalAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_amount", values[i])
			} else if value.Valid {
				_m.TotalAmount = value.Float64
			}
		case promotionsettlementbatch.FieldExecutedByUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field executed_by_user_id", values[i])
			} else if value.Valid {
				_m.ExecutedByUserID = new(int64)
				*_m.ExecutedByUserID = value.Int64
			}
		case promotionsettlementbatch.FieldExecutedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field executed_at", values[i])
			} else if value.Valid {
				_m.ExecutedAt = new(time.Time)
				*_m.ExecutedAt = value.Time
			}
		case promotionsettlementbatch.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = new(string)
				*_m.Note = value.String
			}
		case promotionsettlementbatch.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case promotionsettlementbatch.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PromotionSettlementBatch.
// This includes values selected through modifiers, order, etc.
func (_m *PromotionSettlementBatch) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PromotionSettlementBatch.
// Note that you need to call PromotionSettlementBatch.Unwrap() before calling this method if this PromotionSettlementBatch
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PromotionSettlementBatch) Update() *PromotionSettlementBatchUpdateOne {
	return NewPromotionSettlementBatchClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PromotionSettlementBatch entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PromotionSettlementBatch) Unwrap() *PromotionSettlementBatch {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PromotionSettlementBatch is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PromotionSettlementBatch) String() string {
	var builder strings.Builder
	builder.WriteString("PromotionSettlementBatch(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("business_date=")
	builder.WriteString(_m.BusinessDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("total_records=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalRecords))
	builder.WriteString(", ")
	builder.WriteString("total_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalAmount))
	builder.WriteString(", ")
	if v := _m.ExecutedByUserID; v != nil {
		builder.WriteString("executed_by_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ExecutedAt; v != nil {
		builder.WriteString("executed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.Note; v != nil {
		builder.WriteString("note=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PromotionSettlementBatches is a parsable slice of PromotionSettlementBatch.
type PromotionSettlementBatches []*PromotionSettlementBatch
