// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/promotionscript"
)

// PromotionScriptCreate is the builder for creating a PromotionScript entity.
type PromotionScriptCreate struct {
	config
	mutation *PromotionScriptMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *PromotionScriptCreate) SetName(v string) *PromotionScriptCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *PromotionScriptCreate) SetCategory(v string) *PromotionScriptCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_c *PromotionScriptCreate) SetNillableCategory(v *string) *PromotionScriptCreate {
	if v != nil {
		_c.SetCategory(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *PromotionScriptCreate) SetContent(v string) *PromotionScriptCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetUseCount sets the "use_count" field.
func (_c *PromotionScriptCreate) SetUseCount(v int64) *PromotionScriptCreate {
	_c.mutation.SetUseCount(v)
	return _c
}

// SetNillableUseCount sets the "use_count" field if the given value is not nil.
func (_c *PromotionScriptCreate) SetNillableUseCount(v *int64) *PromotionScriptCreate {
	if v != nil {
		_c.SetUseCount(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *PromotionScriptCreate) SetEnabled(v bool) *PromotionScriptCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *PromotionScriptCreate) SetNillableEnabled(v *bool) *PromotionScriptCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (_c *PromotionScriptCreate) SetCreatedByUserID(v int64) *PromotionScriptCreate {
	_c.mutation.SetCreatedByUserID(v)
	return _c
}

// SetNillableCreatedByUserID sets the "created_by_user_id" field if the given value is not nil.
func (_c *PromotionScriptCreate) SetNillableCreatedByUserID(v *int64) *PromotionScriptCreate {
	if v != nil {
		_c.SetCreatedByUserID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PromotionScriptCreate) SetCreatedAt(v time.Time) *PromotionScriptCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PromotionScriptCreate) SetNillableCreatedAt(v *time.Time) *PromotionScriptCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PromotionScriptCreate) SetUpdatedAt(v time.Time) *PromotionScriptCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PromotionScriptCreate) SetNillableUpdatedAt(v *time.Time) *PromotionScriptCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PromotionScriptCreate) SetID(v int64) *PromotionScriptCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the PromotionScriptMutation object of the builder.
func (_c *PromotionScriptCreate) Mutation() *PromotionScriptMutation {
	return _c.mutation
}

// Save creates the PromotionScript in the database.
func (_c *PromotionScriptCreate) Save(ctx context.Context) (*PromotionScript, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PromotionScriptCreate) SaveX(ctx context.Context) *PromotionScript {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromotionScriptCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromotionScriptCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PromotionScriptCreate) defaults() {
	if _, ok := _c.mutation.Category(); !ok {
		v := promotionscript.DefaultCategory
		_c.mutation.SetCategory(v)
	}
	if _, ok := _c.mutation.UseCount(); !ok {
		v := promotionscript.DefaultUseCount
		_c.mutation.SetUseCount(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := promotionscript.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := promotionscript.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := promotionscript.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PromotionScriptCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "PromotionScript.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := promotionscript.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PromotionScript.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "PromotionScript.category"`)}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := promotionscript.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "PromotionScript.category": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "PromotionScript.content"`)}
	}
	if _, ok := _c.mutation.UseCount(); !ok {
		return &ValidationError{Name: "use_count", err: errors.New(`ent: missing required field "PromotionScript.use_count"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "PromotionScript.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PromotionScript.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PromotionScript.updated_at"`)}
	}
	return nil
}

func (_c *PromotionScriptCreate) sqlSave(ctx context.Context) (*PromotionScript, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PromotionScriptCreate) createSpec() (*PromotionScript, *sqlgraph.CreateSpec) {
	var (
		_node = &PromotionScript{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(promotionscript.Table, sqlgraph.NewFieldSpec(promotionscript.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(promotionscript.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(promotionscript.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(promotionscript.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.UseCount(); ok {
		_spec.SetField(promotionscript.FieldUseCount, field.TypeInt64, value)
		_node.UseCount = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(promotionscript.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.CreatedByUserID(); ok {
		_spec.SetField(promotionscript.FieldCreatedByUserID, field.TypeInt64, value)
		_node.CreatedByUserID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(promotionscript.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(promotionscript.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PromotionScript.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromotionScriptUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *PromotionScriptCreate) OnConflict(opts ...sql.ConflictOption) *PromotionScriptUpsertOne {
	_c.conflict = opts
	return &PromotionScriptUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PromotionScript.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromotionScriptCreate) OnConflictColumns(columns ...string) *PromotionScriptUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromotionScriptUpsertOne{
		create: _c,
	}
}

type (
	// PromotionScriptUpsertOne is the builder for "upsert"-ing
	//  one PromotionScript node.
	PromotionScriptUpsertOne struct {
		create *PromotionScriptCreate
	}

	// PromotionScriptUpsert is the "OnConflict" setter.
	PromotionScriptUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *PromotionScriptUpsert) SetName(v string) *PromotionScriptUpsert {
	u.Set(promotionscript.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PromotionScriptUpsert) UpdateName() *PromotionScriptUpsert {
	u.SetExcluded(promotionscript.FieldName)
	return u
}

// SetCategory sets the "category" field.
func (u *PromotionScriptUpsert) SetCategory(v string) *PromotionScriptUpsert {
	u.Set(promotionscript.FieldCategory, v)
	return u
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *PromotionScriptUpsert) UpdateCategory() *PromotionScriptUpsert {
	u.SetExcluded(promotionscript.FieldCategory)
	return u
}

// SetContent sets the "content" field.
func (u *PromotionScriptUpsert) SetContent(v string) *PromotionScriptUpsert {
	u.Set(promotionscript.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *PromotionScriptUpsert) UpdateContent() *PromotionScriptUpsert {
	u.SetExcluded(promotionscript.FieldContent)
	return u
}

// SetUseCount sets the "use_count" field.
func (u *PromotionScriptUpsert) SetUseCount(v int64) *PromotionScriptUpsert {
	u.Set(promotionscript.FieldUseCount, v)
	return u
}

// UpdateUseCount sets the "use_count" field to the value that was provided on create.
func (u *PromotionScriptUpsert) UpdateUseCount() *PromotionScriptUpsert {
	u.SetExcluded(promotionscript.FieldUseCount)
	return u
}

// AddUseCount adds v to the "use_count" field.
func (u *PromotionScriptUpsert) AddUseCount(v int64) *PromotionScriptUpsert {
	u.Add(promotionscript.FieldUseCount, v)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *PromotionScriptUpsert) SetEnabled(v bool) *PromotionScriptUpsert {
	u.Set(promotionscript.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PromotionScriptUpsert) UpdateEnabled() *PromotionScriptUpsert {
	u.SetExcluded(promotionscript.FieldEnabled)
	return u
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (u *PromotionScriptUpsert) SetCreatedByUserID(v int64) *PromotionScriptUpsert {
	u.Set(promotionscript.FieldCreatedByUserID, v)
	return u
}

// UpdateCreatedByUserID sets the "created_by_user_id" field to the value that was provided on create.
func (u *PromotionScriptUpsert) UpdateCreatedByUserID() *PromotionScriptUpsert {
	u.SetExcluded(promotionscript.FieldCreatedByUserID)
	return u
}

// AddCreatedByUserID adds v to the "created_by_user_id" field.
func (u *PromotionScriptUpsert) AddCreatedByUserID(v int64) *PromotionScriptUpsert {
	u.Add(promotionscript.FieldCreatedByUserID, v)
	return u
}

// ClearCreatedByUserID clears the value of the "created_by_user_id" field.
func (u *PromotionScriptUpsert) ClearCreatedByUserID() *PromotionScriptUpsert {
	u.SetNull(promotionscript.FieldCreatedByUserID)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromotionScriptUpsert) SetUpdatedAt(v time.Time) *PromotionScriptUpsert {
	u.Set(promotionscript.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromotionScriptUpsert) UpdateUpdatedAt() *PromotionScriptUpsert {
	u.SetExcluded(promotionscript.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PromotionScript.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(promotionscript.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PromotionScriptUpsertOne) UpdateNewValues() *PromotionScriptUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(promotionscript.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(promotionscript.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PromotionScript.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PromotionScriptUpsertOne) Ignore() *PromotionScriptUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromotionScriptUpsertOne) DoNothing() *PromotionScriptUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromotionScriptCreate.OnConflict
// documentation for more info.
func (u *PromotionScriptUpsertOne) Update(set func(*PromotionScriptUpsert)) *PromotionScriptUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromotionScriptUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *PromotionScriptUpsertOne) SetName(v string) *PromotionScriptUpsertOne {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PromotionScriptUpsertOne) UpdateName() *PromotionScriptUpsertOne {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.UpdateName()
	})
}

// SetCategory sets the "category" field.
func (u *PromotionScriptUpsertOne) SetCategory(v string) *PromotionScriptUpsertOne {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *PromotionScriptUpsertOne) UpdateCategory() *PromotionScriptUpsertOne {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.UpdateCategory()
	})
}

// SetContent sets the "content" field.
func (u *PromotionScriptUpsertOne) SetContent(v string) *PromotionScriptUpsertOne {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *PromotionScriptUpsertOne) UpdateContent() *PromotionScriptUpsertOne {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.UpdateContent()
	})
}

// SetUseCount sets the "use_count" field.
func (u *PromotionScriptUpsertOne) SetUseCount(v int64) *PromotionScriptUpsertOne {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.SetUseCount(v)
	})
}

// AddUseCount adds v to the "use_count" field.
func (u *PromotionScriptUpsertOne) AddUseCount(v int64) *PromotionScriptUpsertOne {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.AddUseCount(v)
	})
}

// UpdateUseCount sets the "use_count" field to the value that was provided on create.
func (u *PromotionScriptUpsertOne) UpdateUseCount() *PromotionScriptUpsertOne {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.UpdateUseCount()
	})
}

// SetEnabled sets the "enabled" field.
func (u *PromotionScriptUpsertOne) SetEnabled(v bool) *PromotionScriptUpsertOne {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PromotionScriptUpsertOne) UpdateEnabled() *PromotionScriptUpsertOne {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.UpdateEnabled()
	})
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (u *PromotionScriptUpsertOne) SetCreatedByUserID(v int64) *PromotionScriptUpsertOne {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.SetCreatedByUserID(v)
	})
}

// AddCreatedByUserID adds v to the "created_by_user_id" field.
func (u *PromotionScriptUpsertOne) AddCreatedByUserID(v int64) *PromotionScriptUpsertOne {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.AddCreatedByUserID(v)
	})
}

// UpdateCreatedByUserID sets the "created_by_user_id" field to the value that was provided on create.
func (u *PromotionScriptUpsertOne) UpdateCreatedByUserID() *PromotionScriptUpsertOne {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.UpdateCreatedByUserID()
	})
}

// ClearCreatedByUserID clears the value of the "created_by_user_id" field.
func (u *PromotionScriptUpsertOne) ClearCreatedByUserID() *PromotionScriptUpsertOne {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.ClearCreatedByUserID()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromotionScriptUpsertOne) SetUpdatedAt(v time.Time) *PromotionScriptUpsertOne {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromotionScriptUpsertOne) UpdateUpdatedAt() *PromotionScriptUpsertOne {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PromotionScriptUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromotionScriptCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromotionScriptUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PromotionScriptUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PromotionScriptUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PromotionScriptCreateBulk is the builder for creating many PromotionScript entities in bulk.
type PromotionScriptCreateBulk struct {
	config
	err      error
	builders []*PromotionScriptCreate
	conflict []sql.ConflictOption
}

// Save creates the PromotionScript entities in the database.
func (_c *PromotionScriptCreateBulk) Save(ctx context.Context) ([]*PromotionScript, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PromotionScript, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PromotionScriptMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PromotionScriptCreateBulk) SaveX(ctx context.Context) []*PromotionScript {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromotionScriptCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromotionScriptCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PromotionScript.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromotionScriptUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *PromotionScriptCreateBulk) OnConflict(opts ...sql.ConflictOption) *PromotionScriptUpsertBulk {
	_c.conflict = opts
	return &PromotionScriptUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PromotionScript.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromotionScriptCreateBulk) OnConflictColumns(columns ...string) *PromotionScriptUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromotionScriptUpsertBulk{
		create: _c,
	}
}

// PromotionScriptUpsertBulk is the builder for "upsert"-ing
// a bulk of PromotionScript nodes.
type PromotionScriptUpsertBulk struct {
	create *PromotionScriptCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PromotionScript.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(promotionscript.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PromotionScriptUpsertBulk) UpdateNewValues() *PromotionScriptUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(promotionscript.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(promotionscript.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PromotionScript.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PromotionScriptUpsertBulk) Ignore() *PromotionScriptUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromotionScriptUpsertBulk) DoNothing() *PromotionScriptUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromotionScriptCreateBulk.OnConflict
// documentation for more info.
func (u *PromotionScriptUpsertBulk) Update(set func(*PromotionScriptUpsert)) *PromotionScriptUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromotionScriptUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *PromotionScriptUpsertBulk) SetName(v string) *PromotionScriptUpsertBulk {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PromotionScriptUpsertBulk) UpdateName() *PromotionScriptUpsertBulk {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.UpdateName()
	})
}

// SetCategory sets the "category" field.
func (u *PromotionScriptUpsertBulk) SetCategory(v string) *PromotionScriptUpsertBulk {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *PromotionScriptUpsertBulk) UpdateCategory() *PromotionScriptUpsertBulk {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.UpdateCategory()
	})
}

// SetContent sets the "content" field.
func (u *PromotionScriptUpsertBulk) SetContent(v string) *PromotionScriptUpsertBulk {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *PromotionScriptUpsertBulk) UpdateContent() *PromotionScriptUpsertBulk {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.UpdateContent()
	})
}

// SetUseCount sets the "use_count" field.
func (u *PromotionScriptUpsertBulk) SetUseCount(v int64) *PromotionScriptUpsertBulk {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.SetUseCount(v)
	})
}

// AddUseCount adds v to the "use_count" field.
func (u *PromotionScriptUpsertBulk) AddUseCount(v int64) *PromotionScriptUpsertBulk {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.AddUseCount(v)
	})
}

// UpdateUseCount sets the "use_count" field to the value that was provided on create.
func (u *PromotionScriptUpsertBulk) UpdateUseCount() *PromotionScriptUpsertBulk {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.UpdateUseCount()
	})
}

// SetEnabled sets the "enabled" field.
func (u *PromotionScriptUpsertBulk) SetEnabled(v bool) *PromotionScriptUpsertBulk {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PromotionScriptUpsertBulk) UpdateEnabled() *PromotionScriptUpsertBulk {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.UpdateEnabled()
	})
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (u *PromotionScriptUpsertBulk) SetCreatedByUserID(v int64) *PromotionScriptUpsertBulk {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.SetCreatedByUserID(v)
	})
}

// AddCreatedByUserID adds v to the "created_by_user_id" field.
func (u *PromotionScriptUpsertBulk) AddCreatedByUserID(v int64) *PromotionScriptUpsertBulk {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.AddCreatedByUserID(v)
	})
}

// UpdateCreatedByUserID sets the "created_by_user_id" field to the value that was provided on create.
func (u *PromotionScriptUpsertBulk) UpdateCreatedByUserID() *PromotionScriptUpsertBulk {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.UpdateCreatedByUserID()
	})
}

// ClearCreatedByUserID clears the value of the "created_by_user_id" field.
func (u *PromotionScriptUpsertBulk) ClearCreatedByUserID() *PromotionScriptUpsertBulk {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.ClearCreatedByUserID()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromotionScriptUpsertBulk) SetUpdatedAt(v time.Time) *PromotionScriptUpsertBulk {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromotionScriptUpsertBulk) UpdateUpdatedAt() *PromotionScriptUpsertBulk {
	return u.Update(func(s *PromotionScriptUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PromotionScriptUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PromotionScriptCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromotionScriptCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromotionScriptUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
