// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/promotionsetting"
)

// PromotionSettingCreate is the builder for creating a PromotionSetting entity.
type PromotionSettingCreate struct {
	config
	mutation *PromotionSettingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetActivationThresholdAmount sets the "activation_threshold_amount" field.
func (_c *PromotionSettingCreate) SetActivationThresholdAmount(v float64) *PromotionSettingCreate {
	_c.mutation.SetActivationThresholdAmount(v)
	return _c
}

// SetNillableActivationThresholdAmount sets the "activation_threshold_amount" field if the given value is not nil.
func (_c *PromotionSettingCreate) SetNillableActivationThresholdAmount(v *float64) *PromotionSettingCreate {
	if v != nil {
		_c.SetActivationThresholdAmount(*v)
	}
	return _c
}

// SetActivationBonusAmount sets the "activation_bonus_amount" field.
func (_c *PromotionSettingCreate) SetActivationBonusAmount(v float64) *PromotionSettingCreate {
	_c.mutation.SetActivationBonusAmount(v)
	return _c
}

// SetNillableActivationBonusAmount sets the "activation_bonus_amount" field if the given value is not nil.
func (_c *PromotionSettingCreate) SetNillableActivationBonusAmount(v *float64) *PromotionSettingCreate {
	if v != nil {
		_c.SetActivationBonusAmount(*v)
	}
	return _c
}

// SetDailySettlementTime sets the "daily_settlement_time" field.
func (_c *PromotionSettingCreate) SetDailySettlementTime(v time.Time) *PromotionSettingCreate {
	_c.mutation.SetDailySettlementTime(v)
	return _c
}

// SetSettlementEnabled sets the "settlement_enabled" field.
func (_c *PromotionSettingCreate) SetSettlementEnabled(v bool) *PromotionSettingCreate {
	_c.mutation.SetSettlementEnabled(v)
	return _c
}

// SetNillableSettlementEnabled sets the "settlement_enabled" field if the given value is not nil.
func (_c *PromotionSettingCreate) SetNillableSettlementEnabled(v *bool) *PromotionSettingCreate {
	if v != nil {
		_c.SetSettlementEnabled(*v)
	}
	return _c
}

// SetRuleActivationTemplate sets the "rule_activation_template" field.
func (_c *PromotionSettingCreate) SetRuleActivationTemplate(v string) *PromotionSettingCreate {
	_c.mutation.SetRuleActivationTemplate(v)
	return _c
}

// SetNillableRuleActivationTemplate sets the "rule_activation_template" field if the given value is not nil.
func (_c *PromotionSettingCreate) SetNillableRuleActivationTemplate(v *string) *PromotionSettingCreate {
	if v != nil {
		_c.SetRuleActivationTemplate(*v)
	}
	return _c
}

// SetRuleDirectTemplate sets the "rule_direct_template" field.
func (_c *PromotionSettingCreate) SetRuleDirectTemplate(v string) *PromotionSettingCreate {
	_c.mutation.SetRuleDirectTemplate(v)
	return _c
}

// SetNillableRuleDirectTemplate sets the "rule_direct_template" field if the given value is not nil.
func (_c *PromotionSettingCreate) SetNillableRuleDirectTemplate(v *string) *PromotionSettingCreate {
	if v != nil {
		_c.SetRuleDirectTemplate(*v)
	}
	return _c
}

// SetRuleIndirectTemplate sets the "rule_indirect_template" field.
func (_c *PromotionSettingCreate) SetRuleIndirectTemplate(v string) *PromotionSettingCreate {
	_c.mutation.SetRuleIndirectTemplate(v)
	return _c
}

// SetNillableRuleIndirectTemplate sets the "rule_indirect_template" field if the given value is not nil.
func (_c *PromotionSettingCreate) SetNillableRuleIndirectTemplate(v *string) *PromotionSettingCreate {
	if v != nil {
		_c.SetRuleIndirectTemplate(*v)
	}
	return _c
}

// SetRuleLevelSummaryTemplate sets the "rule_level_summary_template" field.
func (_c *PromotionSettingCreate) SetRuleLevelSummaryTemplate(v string) *PromotionSettingCreate {
	_c.mutation.SetRuleLevelSummaryTemplate(v)
	return _c
}

// SetNillableRuleLevelSummaryTemplate sets the "rule_level_summary_template" field if the given value is not nil.
func (_c *PromotionSettingCreate) SetNillableRuleLevelSummaryTemplate(v *string) *PromotionSettingCreate {
	if v != nil {
		_c.SetRuleLevelSummaryTemplate(*v)
	}
	return _c
}

// SetInviteBaseURL sets the "invite_base_url" field.
func (_c *PromotionSettingCreate) SetInviteBaseURL(v string) *PromotionSettingCreate {
	_c.mutation.SetInviteBaseURL(v)
	return _c
}

// SetNillableInviteBaseURL sets the "invite_base_url" field if the given value is not nil.
func (_c *PromotionSettingCreate) SetNillableInviteBaseURL(v *string) *PromotionSettingCreate {
	if v != nil {
		_c.SetInviteBaseURL(*v)
	}
	return _c
}

// SetPosterLogoURL sets the "poster_logo_url" field.
func (_c *PromotionSettingCreate) SetPosterLogoURL(v string) *PromotionSettingCreate {
	_c.mutation.SetPosterLogoURL(v)
	return _c
}

// SetNillablePosterLogoURL sets the "poster_logo_url" field if the given value is not nil.
func (_c *PromotionSettingCreate) SetNillablePosterLogoURL(v *string) *PromotionSettingCreate {
	if v != nil {
		_c.SetPosterLogoURL(*v)
	}
	return _c
}

// SetPosterTitle sets the "poster_title" field.
func (_c *PromotionSettingCreate) SetPosterTitle(v string) *PromotionSettingCreate {
	_c.mutation.SetPosterTitle(v)
	return _c
}

// SetNillablePosterTitle sets the "poster_title" field if the given value is not nil.
func (_c *PromotionSettingCreate) SetNillablePosterTitle(v *string) *PromotionSettingCreate {
	if v != nil {
		_c.SetPosterTitle(*v)
	}
	return _c
}

// SetPosterHeadline sets the "poster_headline" field.
func (_c *PromotionSettingCreate) SetPosterHeadline(v string) *PromotionSettingCreate {
	_c.mutation.SetPosterHeadline(v)
	return _c
}

// SetNillablePosterHeadline sets the "poster_headline" field if the given value is not nil.
func (_c *PromotionSettingCreate) SetNillablePosterHeadline(v *string) *PromotionSettingCreate {
	if v != nil {
		_c.SetPosterHeadline(*v)
	}
	return _c
}

// SetPosterDescription sets the "poster_description" field.
func (_c *PromotionSettingCreate) SetPosterDescription(v string) *PromotionSettingCreate {
	_c.mutation.SetPosterDescription(v)
	return _c
}

// SetNillablePosterDescription sets the "poster_description" field if the given value is not nil.
func (_c *PromotionSettingCreate) SetNillablePosterDescription(v *string) *PromotionSettingCreate {
	if v != nil {
		_c.SetPosterDescription(*v)
	}
	return _c
}

// SetPosterScanHint sets the "poster_scan_hint" field.
func (_c *PromotionSettingCreate) SetPosterScanHint(v string) *PromotionSettingCreate {
	_c.mutation.SetPosterScanHint(v)
	return _c
}

// SetNillablePosterScanHint sets the "poster_scan_hint" field if the given value is not nil.
func (_c *PromotionSettingCreate) SetNillablePosterScanHint(v *string) *PromotionSettingCreate {
	if v != nil {
		_c.SetPosterScanHint(*v)
	}
	return _c
}

// SetPosterTagsJSON sets the "poster_tags_json" field.
func (_c *PromotionSettingCreate) SetPosterTagsJSON(v string) *PromotionSettingCreate {
	_c.mutation.SetPosterTagsJSON(v)
	return _c
}

// SetNillablePosterTagsJSON sets the "poster_tags_json" field if the given value is not nil.
func (_c *PromotionSettingCreate) SetNillablePosterTagsJSON(v *string) *PromotionSettingCreate {
	if v != nil {
		_c.SetPosterTagsJSON(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PromotionSettingCreate) SetCreatedAt(v time.Time) *PromotionSettingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PromotionSettingCreate) SetNillableCreatedAt(v *time.Time) *PromotionSettingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PromotionSettingCreate) SetUpdatedAt(v time.Time) *PromotionSettingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PromotionSettingCreate) SetNillableUpdatedAt(v *time.Time) *PromotionSettingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PromotionSettingCreate) SetID(v int64) *PromotionSettingCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PromotionSettingCreate) SetNillableID(v *int64) *PromotionSettingCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the PromotionSettingMutation object of the builder.
func (_c *PromotionSettingCreate) Mutation() *PromotionSettingMutation {
	return _c.mutation
}

// Save creates the PromotionSetting in the database.
func (_c *PromotionSettingCreate) Save(ctx context.Context) (*PromotionSetting, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PromotionSettingCreate) SaveX(ctx context.Context) *PromotionSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromotionSettingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromotionSettingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PromotionSettingCreate) defaults() {
	if _, ok := _c.mutation.ActivationThresholdAmount(); !ok {
		v := promotionsetting.DefaultActivationThresholdAmount
		_c.mutation.SetActivationThresholdAmount(v)
	}
	if _, ok := _c.mutation.ActivationBonusAmount(); !ok {
		v := promotionsetting.DefaultActivationBonusAmount
		_c.mutation.SetActivationBonusAmount(v)
	}
	if _, ok := _c.mutation.SettlementEnabled(); !ok {
		v := promotionsetting.DefaultSettlementEnabled
		_c.mutation.SetSettlementEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := promotionsetting.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := promotionsetting.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := promotionsetting.DefaultID
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PromotionSettingCreate) check() error {
	if _, ok := _c.mutation.ActivationThresholdAmount(); !ok {
		return &ValidationError{Name: "activation_threshold_amount", err: errors.New(`ent: missing required field "PromotionSetting.activation_threshold_amount"`)}
	}
	if _, ok := _c.mutation.ActivationBonusAmount(); !ok {
		return &ValidationError{Name: "activation_bonus_amount", err: errors.New(`ent: missing required field "PromotionSetting.activation_bonus_amount"`)}
	}
	if _, ok := _c.mutation.DailySettlementTime(); !ok {
		return &ValidationError{Name: "daily_settlement_time", err: errors.New(`ent: missing required field "PromotionSetting.daily_settlement_time"`)}
	}
	if _, ok := _c.mutation.SettlementEnabled(); !ok {
		return &ValidationError{Name: "settlement_enabled", err: errors.New(`ent: missing required field "PromotionSetting.settlement_enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PromotionSetting.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PromotionSetting.updated_at"`)}
	}
	return nil
}

func (_c *PromotionSettingCreate) sqlSave(ctx context.Context) (*PromotionSetting, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PromotionSettingCreate) createSpec() (*PromotionSetting, *sqlgraph.CreateSpec) {
	var (
		_node = &PromotionSetting{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(promotionsetting.Table, sqlgraph.NewFieldSpec(promotionsetting.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ActivationThresholdAmount(); ok {
		_spec.SetField(promotionsetting.FieldActivationThresholdAmount, field.TypeFloat64, value)
		_node.ActivationThresholdAmount = value
	}
	if value, ok := _c.mutation.ActivationBonusAmount(); ok {
		_spec.SetField(promotionsetting.FieldActivationBonusAmount, field.TypeFloat64, value)
		_node.ActivationBonusAmount = value
	}
	if value, ok := _c.mutation.DailySettlementTime(); ok {
		_spec.SetField(promotionsetting.FieldDailySettlementTime, field.TypeTime, value)
		_node.DailySettlementTime = value
	}
	if value, ok := _c.mutation.SettlementEnabled(); ok {
		_spec.SetField(promotionsetting.FieldSettlementEnabled, field.TypeBool, value)
		_node.SettlementEnabled = value
	}
	if value, ok := _c.mutation.RuleActivationTemplate(); ok {
		_spec.SetField(promotionsetting.FieldRuleActivationTemplate, field.TypeString, value)
		_node.RuleActivationTemplate = &value
	}
	if value, ok := _c.mutation.RuleDirectTemplate(); ok {
		_spec.SetField(promotionsetting.FieldRuleDirectTemplate, field.TypeString, value)
		_node.RuleDirectTemplate = &value
	}
	if value, ok := _c.mutation.RuleIndirectTemplate(); ok {
		_spec.SetField(promotionsetting.FieldRuleIndirectTemplate, field.TypeString, value)
		_node.RuleIndirectTemplate = &value
	}
	if value, ok := _c.mutation.RuleLevelSummaryTemplate(); ok {
		_spec.SetField(promotionsetting.FieldRuleLevelSummaryTemplate, field.TypeString, value)
		_node.RuleLevelSummaryTemplate = &value
	}
	if value, ok := _c.mutation.InviteBaseURL(); ok {
		_spec.SetField(promotionsetting.FieldInviteBaseURL, field.TypeString, value)
		_node.InviteBaseURL = &value
	}
	if value, ok := _c.mutation.PosterLogoURL(); ok {
		_spec.SetField(promotionsetting.FieldPosterLogoURL, field.TypeString, value)
		_node.PosterLogoURL = &value
	}
	if value, ok := _c.mutation.PosterTitle(); ok {
		_spec.SetField(promotionsetting.FieldPosterTitle, field.TypeString, value)
		_node.PosterTitle = &value
	}
	if value, ok := _c.mutation.PosterHeadline(); ok {
		_spec.SetField(promotionsetting.FieldPosterHeadline, field.TypeString, value)
		_node.PosterHeadline = &value
	}
	if value, ok := _c.mutation.PosterDescription(); ok {
		_spec.SetField(promotionsetting.FieldPosterDescription, field.TypeString, value)
		_node.PosterDescription = &value
	}
	if value, ok := _c.mutation.PosterScanHint(); ok {
		_spec.SetField(promotionsetting.FieldPosterScanHint, field.TypeString, value)
		_node.PosterScanHint = &value
	}
	if value, ok := _c.mutation.PosterTagsJSON(); ok {
		_spec.SetField(promotionsetting.FieldPosterTagsJSON, field.TypeString, value)
		_node.PosterTagsJSON = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(promotionsetting.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(promotionsetting.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PromotionSetting.Create().
//		SetActivationThresholdAmount(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromotionSettingUpsert) {
//			SetActivationThresholdAmount(v+v).
//		}).
//		Exec(ctx)
func (_c *PromotionSettingCreate) OnConflict(opts ...sql.ConflictOption) *PromotionSettingUpsertOne {
	_c.conflict = opts
	return &PromotionSettingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PromotionSetting.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromotionSettingCreate) OnConflictColumns(columns ...string) *PromotionSettingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromotionSettingUpsertOne{
		create: _c,
	}
}

type (
	// PromotionSettingUpsertOne is the builder for "upsert"-ing
	//  one PromotionSetting node.
	PromotionSettingUpsertOne struct {
		create *PromotionSettingCreate
	}

	// PromotionSettingUpsert is the "OnConflict" setter.
	PromotionSettingUpsert struct {
		*sql.UpdateSet
	}
)

// SetActivationThresholdAmount sets the "activation_threshold_amount" field.
func (u *PromotionSettingUpsert) SetActivationThresholdAmount(v float64) *PromotionSettingUpsert {
	u.Set(promotionsetting.FieldActivationThresholdAmount, v)
	return u
}

// UpdateActivationThresholdAmount sets the "activation_threshold_amount" field to the value that was provided on create.
func (u *PromotionSettingUpsert) UpdateActivationThresholdAmount() *PromotionSettingUpsert {
	u.SetExcluded(promotionsetting.FieldActivationThresholdAmount)
	return u
}

// AddActivationThresholdAmount adds v to the "activation_threshold_amount" field.
func (u *PromotionSettingUpsert) AddActivationThresholdAmount(v float64) *PromotionSettingUpsert {
	u.Add(promotionsetting.FieldActivationThresholdAmount, v)
	return u
}

// SetActivationBonusAmount sets the "activation_bonus_amount" field.
func (u *PromotionSettingUpsert) SetActivationBonusAmount(v float64) *PromotionSettingUpsert {
	u.Set(promotionsetting.FieldActivationBonusAmount, v)
	return u
}

// UpdateActivationBonusAmount sets the "activation_bonus_amount" field to the value that was provided on create.
func (u *PromotionSettingUpsert) UpdateActivationBonusAmount() *PromotionSettingUpsert {
	u.SetExcluded(promotionsetting.FieldActivationBonusAmount)
	return u
}

// AddActivationBonusAmount adds v to the "activation_bonus_amount" field.
func (u *PromotionSettingUpsert) AddActivationBonusAmount(v float64) *PromotionSettingUpsert {
	u.Add(promotionsetting.FieldActivationBonusAmount, v)
	return u
}

// SetDailySettlementTime sets the "daily_settlement_time" field.
func (u *PromotionSettingUpsert) SetDailySettlementTime(v time.Time) *PromotionSettingUpsert {
	u.Set(promotionsetting.FieldDailySettlementTime, v)
	return u
}

// UpdateDailySettlementTime sets the "daily_settlement_time" field to the value that was provided on create.
func (u *PromotionSettingUpsert) UpdateDailySettlementTime() *PromotionSettingUpsert {
	u.SetExcluded(promotionsetting.FieldDailySettlementTime)
	return u
}

// SetSettlementEnabled sets the "settlement_enabled" field.
func (u *PromotionSettingUpsert) SetSettlementEnabled(v bool) *PromotionSettingUpsert {
	u.Set(promotionsetting.FieldSettlementEnabled, v)
	return u
}

// UpdateSettlementEnabled sets the "settlement_enabled" field to the value that was provided on create.
func (u *PromotionSettingUpsert) UpdateSettlementEnabled() *PromotionSettingUpsert {
	u.SetExcluded(promotionsetting.FieldSettlementEnabled)
	return u
}

// SetRuleActivationTemplate sets the "rule_activation_template" field.
func (u *PromotionSettingUpsert) SetRuleActivationTemplate(v string) *PromotionSettingUpsert {
	u.Set(promotionsetting.FieldRuleActivationTemplate, v)
	return u
}

// UpdateRuleActivationTemplate sets the "rule_activation_template" field to the value that was provided on create.
func (u *PromotionSettingUpsert) UpdateRuleActivationTemplate() *PromotionSettingUpsert {
	u.SetExcluded(promotionsetting.FieldRuleActivationTemplate)
	return u
}

// ClearRuleActivationTemplate clears the value of the "rule_activation_template" field.
func (u *PromotionSettingUpsert) ClearRuleActivationTemplate() *PromotionSettingUpsert {
	u.SetNull(promotionsetting.FieldRuleActivationTemplate)
	return u
}

// SetRuleDirectTemplate sets the "rule_direct_template" field.
func (u *PromotionSettingUpsert) SetRuleDirectTemplate(v string) *PromotionSettingUpsert {
	u.Set(promotionsetting.FieldRuleDirectTemplate, v)
	return u
}

// UpdateRuleDirectTemplate sets the "rule_direct_template" field to the value that was provided on create.
func (u *PromotionSettingUpsert) UpdateRuleDirectTemplate() *PromotionSettingUpsert {
	u.SetExcluded(promotionsetting.FieldRuleDirectTemplate)
	return u
}

// ClearRuleDirectTemplate clears the value of the "rule_direct_template" field.
func (u *PromotionSettingUpsert) ClearRuleDirectTemplate() *PromotionSettingUpsert {
	u.SetNull(promotionsetting.FieldRuleDirectTemplate)
	return u
}

// SetRuleIndirectTemplate sets the "rule_indirect_template" field.
func (u *PromotionSettingUpsert) SetRuleIndirectTemplate(v string) *PromotionSettingUpsert {
	u.Set(promotionsetting.FieldRuleIndirectTemplate, v)
	return u
}

// UpdateRuleIndirectTemplate sets the "rule_indirect_template" field to the value that was provided on create.
func (u *PromotionSettingUpsert) UpdateRuleIndirectTemplate() *PromotionSettingUpsert {
	u.SetExcluded(promotionsetting.FieldRuleIndirectTemplate)
	return u
}

// ClearRuleIndirectTemplate clears the value of the "rule_indirect_template" field.
func (u *PromotionSettingUpsert) ClearRuleIndirectTemplate() *PromotionSettingUpsert {
	u.SetNull(promotionsetting.FieldRuleIndirectTemplate)
	return u
}

// SetRuleLevelSummaryTemplate sets the "rule_level_summary_template" field.
func (u *PromotionSettingUpsert) SetRuleLevelSummaryTemplate(v string) *PromotionSettingUpsert {
	u.Set(promotionsetting.FieldRuleLevelSummaryTemplate, v)
	return u
}

// UpdateRuleLevelSummaryTemplate sets the "rule_level_summary_template" field to the value that was provided on create.
func (u *PromotionSettingUpsert) UpdateRuleLevelSummaryTemplate() *PromotionSettingUpsert {
	u.SetExcluded(promotionsetting.FieldRuleLevelSummaryTemplate)
	return u
}

// ClearRuleLevelSummaryTemplate clears the value of the "rule_level_summary_template" field.
func (u *PromotionSettingUpsert) ClearRuleLevelSummaryTemplate() *PromotionSettingUpsert {
	u.SetNull(promotionsetting.FieldRuleLevelSummaryTemplate)
	return u
}

// SetInviteBaseURL sets the "invite_base_url" field.
func (u *PromotionSettingUpsert) SetInviteBaseURL(v string) *PromotionSettingUpsert {
	u.Set(promotionsetting.FieldInviteBaseURL, v)
	return u
}

// UpdateInviteBaseURL sets the "invite_base_url" field to the value that was provided on create.
func (u *PromotionSettingUpsert) UpdateInviteBaseURL() *PromotionSettingUpsert {
	u.SetExcluded(promotionsetting.FieldInviteBaseURL)
	return u
}

// ClearInviteBaseURL clears the value of the "invite_base_url" field.
func (u *PromotionSettingUpsert) ClearInviteBaseURL() *PromotionSettingUpsert {
	u.SetNull(promotionsetting.FieldInviteBaseURL)
	return u
}

// SetPosterLogoURL sets the "poster_logo_url" field.
func (u *PromotionSettingUpsert) SetPosterLogoURL(v string) *PromotionSettingUpsert {
	u.Set(promotionsetting.FieldPosterLogoURL, v)
	return u
}

// UpdatePosterLogoURL sets the "poster_logo_url" field to the value that was provided on create.
func (u *PromotionSettingUpsert) UpdatePosterLogoURL() *PromotionSettingUpsert {
	u.SetExcluded(promotionsetting.FieldPosterLogoURL)
	return u
}

// ClearPosterLogoURL clears the value of the "poster_logo_url" field.
func (u *PromotionSettingUpsert) ClearPosterLogoURL() *PromotionSettingUpsert {
	u.SetNull(promotionsetting.FieldPosterLogoURL)
	return u
}

// SetPosterTitle sets the "poster_title" field.
func (u *PromotionSettingUpsert) SetPosterTitle(v string) *PromotionSettingUpsert {
	u.Set(promotionsetting.FieldPosterTitle, v)
	return u
}

// UpdatePosterTitle sets the "poster_title" field to the value that was provided on create.
func (u *PromotionSettingUpsert) UpdatePosterTitle() *PromotionSettingUpsert {
	u.SetExcluded(promotionsetting.FieldPosterTitle)
	return u
}

// ClearPosterTitle clears the value of the "poster_title" field.
func (u *PromotionSettingUpsert) ClearPosterTitle() *PromotionSettingUpsert {
	u.SetNull(promotionsetting.FieldPosterTitle)
	return u
}

// SetPosterHeadline sets the "poster_headline" field.
func (u *PromotionSettingUpsert) SetPosterHeadline(v string) *PromotionSettingUpsert {
	u.Set(promotionsetting.FieldPosterHeadline, v)
	return u
}

// UpdatePosterHeadline sets the "poster_headline" field to the value that was provided on create.
func (u *PromotionSettingUpsert) UpdatePosterHeadline() *PromotionSettingUpsert {
	u.SetExcluded(promotionsetting.FieldPosterHeadline)
	return u
}

// ClearPosterHeadline clears the value of the "poster_headline" field.
func (u *PromotionSettingUpsert) ClearPosterHeadline() *PromotionSettingUpsert {
	u.SetNull(promotionsetting.FieldPosterHeadline)
	return u
}

// SetPosterDescription sets the "poster_description" field.
func (u *PromotionSettingUpsert) SetPosterDescription(v string) *PromotionSettingUpsert {
	u.Set(promotionsetting.FieldPosterDescription, v)
	return u
}

// UpdatePosterDescription sets the "poster_description" field to the value that was provided on create.
func (u *PromotionSettingUpsert) UpdatePosterDescription() *PromotionSettingUpsert {
	u.SetExcluded(promotionsetting.FieldPosterDescription)
	return u
}

// ClearPosterDescription clears the value of the "poster_description" field.
func (u *PromotionSettingUpsert) ClearPosterDescription() *PromotionSettingUpsert {
	u.SetNull(promotionsetting.FieldPosterDescription)
	return u
}

// SetPosterScanHint sets the "poster_scan_hint" field.
func (u *PromotionSettingUpsert) SetPosterScanHint(v string) *PromotionSettingUpsert {
	u.Set(promotionsetting.FieldPosterScanHint, v)
	return u
}

// UpdatePosterScanHint sets the "poster_scan_hint" field to the value that was provided on create.
func (u *PromotionSettingUpsert) UpdatePosterScanHint() *PromotionSettingUpsert {
	u.SetExcluded(promotionsetting.FieldPosterScanHint)
	return u
}

// ClearPosterScanHint clears the value of the "poster_scan_hint" field.
func (u *PromotionSettingUpsert) ClearPosterScanHint() *PromotionSettingUpsert {
	u.SetNull(promotionsetting.FieldPosterScanHint)
	return u
}

// SetPosterTagsJSON sets the "poster_tags_json" field.
func (u *PromotionSettingUpsert) SetPosterTagsJSON(v string) *PromotionSettingUpsert {
	u.Set(promotionsetting.FieldPosterTagsJSON, v)
	return u
}

// UpdatePosterTagsJSON sets the "poster_tags_json" field to the value that was provided on create.
func (u *PromotionSettingUpsert) UpdatePosterTagsJSON() *PromotionSettingUpsert {
	u.SetExcluded(promotionsetting.FieldPosterTagsJSON)
	return u
}

// ClearPosterTagsJSON clears the value of the "poster_tags_json" field.
func (u *PromotionSettingUpsert) ClearPosterTagsJSON() *PromotionSettingUpsert {
	u.SetNull(promotionsetting.FieldPosterTagsJSON)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromotionSettingUpsert) SetUpdatedAt(v time.Time) *PromotionSettingUpsert {
	u.Set(promotionsetting.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromotionSettingUpsert) UpdateUpdatedAt() *PromotionSettingUpsert {
	u.SetExcluded(promotionsetting.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PromotionSetting.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(promotionsetting.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PromotionSettingUpsertOne) UpdateNewValues() *PromotionSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(promotionsetting.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(promotionsetting.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PromotionSetting.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PromotionSettingUpsertOne) Ignore() *PromotionSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromotionSettingUpsertOne) DoNothing() *PromotionSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromotionSettingCreate.OnConflict
// documentation for more info.
func (u *PromotionSettingUpsertOne) Update(set func(*PromotionSettingUpsert)) *PromotionSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromotionSettingUpsert{UpdateSet: update})
	}))
	return u
}

// SetActivationThresholdAmount sets the "activation_threshold_amount" field.
func (u *PromotionSettingUpsertOne) SetActivationThresholdAmount(v float64) *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetActivationThresholdAmount(v)
	})
}

// AddActivationThresholdAmount adds v to the "activation_threshold_amount" field.
func (u *PromotionSettingUpsertOne) AddActivationThresholdAmount(v float64) *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.AddActivationThresholdAmount(v)
	})
}

// UpdateActivationThresholdAmount sets the "activation_threshold_amount" field to the value that was provided on create.
func (u *PromotionSettingUpsertOne) UpdateActivationThresholdAmount() *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdateActivationThresholdAmount()
	})
}

// SetActivationBonusAmount sets the "activation_bonus_amount" field.
func (u *PromotionSettingUpsertOne) SetActivationBonusAmount(v float64) *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetActivationBonusAmount(v)
	})
}

// AddActivationBonusAmount adds v to the "activation_bonus_amount" field.
func (u *PromotionSettingUpsertOne) AddActivationBonusAmount(v float64) *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.AddActivationBonusAmount(v)
	})
}

// UpdateActivationBonusAmount sets the "activation_bonus_amount" field to the value that was provided on create.
func (u *PromotionSettingUpsertOne) UpdateActivationBonusAmount() *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdateActivationBonusAmount()
	})
}

// SetDailySettlementTime sets the "daily_settlement_time" field.
func (u *PromotionSettingUpsertOne) SetDailySettlementTime(v time.Time) *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetDailySettlementTime(v)
	})
}

// UpdateDailySettlementTime sets the "daily_settlement_time" field to the value that was provided on create.
func (u *PromotionSettingUpsertOne) UpdateDailySettlementTime() *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdateDailySettlementTime()
	})
}

// SetSettlementEnabled sets the "settlement_enabled" field.
func (u *PromotionSettingUpsertOne) SetSettlementEnabled(v bool) *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetSettlementEnabled(v)
	})
}

// UpdateSettlementEnabled sets the "settlement_enabled" field to the value that was provided on create.
func (u *PromotionSettingUpsertOne) UpdateSettlementEnabled() *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdateSettlementEnabled()
	})
}

// SetRuleActivationTemplate sets the "rule_activation_template" field.
func (u *PromotionSettingUpsertOne) SetRuleActivationTemplate(v string) *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetRuleActivationTemplate(v)
	})
}

// UpdateRuleActivationTemplate sets the "rule_activation_template" field to the value that was provided on create.
func (u *PromotionSettingUpsertOne) UpdateRuleActivationTemplate() *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdateRuleActivationTemplate()
	})
}

// ClearRuleActivationTemplate clears the value of the "rule_activation_template" field.
func (u *PromotionSettingUpsertOne) ClearRuleActivationTemplate() *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.ClearRuleActivationTemplate()
	})
}

// SetRuleDirectTemplate sets the "rule_direct_template" field.
func (u *PromotionSettingUpsertOne) SetRuleDirectTemplate(v string) *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetRuleDirectTemplate(v)
	})
}

// UpdateRuleDirectTemplate sets the "rule_direct_template" field to the value that was provided on create.
func (u *PromotionSettingUpsertOne) UpdateRuleDirectTemplate() *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdateRuleDirectTemplate()
	})
}

// ClearRuleDirectTemplate clears the value of the "rule_direct_template" field.
func (u *PromotionSettingUpsertOne) ClearRuleDirectTemplate() *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.ClearRuleDirectTemplate()
	})
}

// SetRuleIndirectTemplate sets the "rule_indirect_template" field.
func (u *PromotionSettingUpsertOne) SetRuleIndirectTemplate(v string) *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetRuleIndirectTemplate(v)
	})
}

// UpdateRuleIndirectTemplate sets the "rule_indirect_template" field to the value that was provided on create.
func (u *PromotionSettingUpsertOne) UpdateRuleIndirectTemplate() *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdateRuleIndirectTemplate()
	})
}

// ClearRuleIndirectTemplate clears the value of the "rule_indirect_template" field.
func (u *PromotionSettingUpsertOne) ClearRuleIndirectTemplate() *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.ClearRuleIndirectTemplate()
	})
}

// SetRuleLevelSummaryTemplate sets the "rule_level_summary_template" field.
func (u *PromotionSettingUpsertOne) SetRuleLevelSummaryTemplate(v string) *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetRuleLevelSummaryTemplate(v)
	})
}

// UpdateRuleLevelSummaryTemplate sets the "rule_level_summary_template" field to the value that was provided on create.
func (u *PromotionSettingUpsertOne) UpdateRuleLevelSummaryTemplate() *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdateRuleLevelSummaryTemplate()
	})
}

// ClearRuleLevelSummaryTemplate clears the value of the "rule_level_summary_template" field.
func (u *PromotionSettingUpsertOne) ClearRuleLevelSummaryTemplate() *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.ClearRuleLevelSummaryTemplate()
	})
}

// SetInviteBaseURL sets the "invite_base_url" field.
func (u *PromotionSettingUpsertOne) SetInviteBaseURL(v string) *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetInviteBaseURL(v)
	})
}

// UpdateInviteBaseURL sets the "invite_base_url" field to the value that was provided on create.
func (u *PromotionSettingUpsertOne) UpdateInviteBaseURL() *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdateInviteBaseURL()
	})
}

// ClearInviteBaseURL clears the value of the "invite_base_url" field.
func (u *PromotionSettingUpsertOne) ClearInviteBaseURL() *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.ClearInviteBaseURL()
	})
}

// SetPosterLogoURL sets the "poster_logo_url" field.
func (u *PromotionSettingUpsertOne) SetPosterLogoURL(v string) *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetPosterLogoURL(v)
	})
}

// UpdatePosterLogoURL sets the "poster_logo_url" field to the value that was provided on create.
func (u *PromotionSettingUpsertOne) UpdatePosterLogoURL() *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdatePosterLogoURL()
	})
}

// ClearPosterLogoURL clears the value of the "poster_logo_url" field.
func (u *PromotionSettingUpsertOne) ClearPosterLogoURL() *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.ClearPosterLogoURL()
	})
}

// SetPosterTitle sets the "poster_title" field.
func (u *PromotionSettingUpsertOne) SetPosterTitle(v string) *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetPosterTitle(v)
	})
}

// UpdatePosterTitle sets the "poster_title" field to the value that was provided on create.
func (u *PromotionSettingUpsertOne) UpdatePosterTitle() *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdatePosterTitle()
	})
}

// ClearPosterTitle clears the value of the "poster_title" field.
func (u *PromotionSettingUpsertOne) ClearPosterTitle() *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.ClearPosterTitle()
	})
}

// SetPosterHeadline sets the "poster_headline" field.
func (u *PromotionSettingUpsertOne) SetPosterHeadline(v string) *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetPosterHeadline(v)
	})
}

// UpdatePosterHeadline sets the "poster_headline" field to the value that was provided on create.
func (u *PromotionSettingUpsertOne) UpdatePosterHeadline() *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdatePosterHeadline()
	})
}

// ClearPosterHeadline clears the value of the "poster_headline" field.
func (u *PromotionSettingUpsertOne) ClearPosterHeadline() *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.ClearPosterHeadline()
	})
}

// SetPosterDescription sets the "poster_description" field.
func (u *PromotionSettingUpsertOne) SetPosterDescription(v string) *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetPosterDescription(v)
	})
}

// UpdatePosterDescription sets the "poster_description" field to the value that was provided on create.
func (u *PromotionSettingUpsertOne) UpdatePosterDescription() *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdatePosterDescription()
	})
}

// ClearPosterDescription clears the value of the "poster_description" field.
func (u *PromotionSettingUpsertOne) ClearPosterDescription() *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.ClearPosterDescription()
	})
}

// SetPosterScanHint sets the "poster_scan_hint" field.
func (u *PromotionSettingUpsertOne) SetPosterScanHint(v string) *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetPosterScanHint(v)
	})
}

// UpdatePosterScanHint sets the "poster_scan_hint" field to the value that was provided on create.
func (u *PromotionSettingUpsertOne) UpdatePosterScanHint() *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdatePosterScanHint()
	})
}

// ClearPosterScanHint clears the value of the "poster_scan_hint" field.
func (u *PromotionSettingUpsertOne) ClearPosterScanHint() *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.ClearPosterScanHint()
	})
}

// SetPosterTagsJSON sets the "poster_tags_json" field.
func (u *PromotionSettingUpsertOne) SetPosterTagsJSON(v string) *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetPosterTagsJSON(v)
	})
}

// UpdatePosterTagsJSON sets the "poster_tags_json" field to the value that was provided on create.
func (u *PromotionSettingUpsertOne) UpdatePosterTagsJSON() *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdatePosterTagsJSON()
	})
}

// ClearPosterTagsJSON clears the value of the "poster_tags_json" field.
func (u *PromotionSettingUpsertOne) ClearPosterTagsJSON() *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.ClearPosterTagsJSON()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromotionSettingUpsertOne) SetUpdatedAt(v time.Time) *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromotionSettingUpsertOne) UpdateUpdatedAt() *PromotionSettingUpsertOne {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PromotionSettingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromotionSettingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromotionSettingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PromotionSettingUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PromotionSettingUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PromotionSettingCreateBulk is the builder for creating many PromotionSetting entities in bulk.
type PromotionSettingCreateBulk struct {
	config
	err      error
	builders []*PromotionSettingCreate
	conflict []sql.ConflictOption
}

// Save creates the PromotionSetting entities in the database.
func (_c *PromotionSettingCreateBulk) Save(ctx context.Context) ([]*PromotionSetting, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PromotionSetting, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PromotionSettingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PromotionSettingCreateBulk) SaveX(ctx context.Context) []*PromotionSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromotionSettingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromotionSettingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PromotionSetting.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromotionSettingUpsert) {
//			SetActivationThresholdAmount(v+v).
//		}).
//		Exec(ctx)
func (_c *PromotionSettingCreateBulk) OnConflict(opts ...sql.ConflictOption) *PromotionSettingUpsertBulk {
	_c.conflict = opts
	return &PromotionSettingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PromotionSetting.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromotionSettingCreateBulk) OnConflictColumns(columns ...string) *PromotionSettingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromotionSettingUpsertBulk{
		create: _c,
	}
}

// PromotionSettingUpsertBulk is the builder for "upsert"-ing
// a bulk of PromotionSetting nodes.
type PromotionSettingUpsertBulk struct {
	create *PromotionSettingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PromotionSetting.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(promotionsetting.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PromotionSettingUpsertBulk) UpdateNewValues() *PromotionSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(promotionsetting.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(promotionsetting.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PromotionSetting.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PromotionSettingUpsertBulk) Ignore() *PromotionSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromotionSettingUpsertBulk) DoNothing() *PromotionSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromotionSettingCreateBulk.OnConflict
// documentation for more info.
func (u *PromotionSettingUpsertBulk) Update(set func(*PromotionSettingUpsert)) *PromotionSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromotionSettingUpsert{UpdateSet: update})
	}))
	return u
}

// SetActivationThresholdAmount sets the "activation_threshold_amount" field.
func (u *PromotionSettingUpsertBulk) SetActivationThresholdAmount(v float64) *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetActivationThresholdAmount(v)
	})
}

// AddActivationThresholdAmount adds v to the "activation_threshold_amount" field.
func (u *PromotionSettingUpsertBulk) AddActivationThresholdAmount(v float64) *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.AddActivationThresholdAmount(v)
	})
}

// UpdateActivationThresholdAmount sets the "activation_threshold_amount" field to the value that was provided on create.
func (u *PromotionSettingUpsertBulk) UpdateActivationThresholdAmount() *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdateActivationThresholdAmount()
	})
}

// SetActivationBonusAmount sets the "activation_bonus_amount" field.
func (u *PromotionSettingUpsertBulk) SetActivationBonusAmount(v float64) *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetActivationBonusAmount(v)
	})
}

// AddActivationBonusAmount adds v to the "activation_bonus_amount" field.
func (u *PromotionSettingUpsertBulk) AddActivationBonusAmount(v float64) *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.AddActivationBonusAmount(v)
	})
}

// UpdateActivationBonusAmount sets the "activation_bonus_amount" field to the value that was provided on create.
func (u *PromotionSettingUpsertBulk) UpdateActivationBonusAmount() *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdateActivationBonusAmount()
	})
}

// SetDailySettlementTime sets the "daily_settlement_time" field.
func (u *PromotionSettingUpsertBulk) SetDailySettlementTime(v time.Time) *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetDailySettlementTime(v)
	})
}

// UpdateDailySettlementTime sets the "daily_settlement_time" field to the value that was provided on create.
func (u *PromotionSettingUpsertBulk) UpdateDailySettlementTime() *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdateDailySettlementTime()
	})
}

// SetSettlementEnabled sets the "settlement_enabled" field.
func (u *PromotionSettingUpsertBulk) SetSettlementEnabled(v bool) *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetSettlementEnabled(v)
	})
}

// UpdateSettlementEnabled sets the "settlement_enabled" field to the value that was provided on create.
func (u *PromotionSettingUpsertBulk) UpdateSettlementEnabled() *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdateSettlementEnabled()
	})
}

// SetRuleActivationTemplate sets the "rule_activation_template" field.
func (u *PromotionSettingUpsertBulk) SetRuleActivationTemplate(v string) *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetRuleActivationTemplate(v)
	})
}

// UpdateRuleActivationTemplate sets the "rule_activation_template" field to the value that was provided on create.
func (u *PromotionSettingUpsertBulk) UpdateRuleActivationTemplate() *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdateRuleActivationTemplate()
	})
}

// ClearRuleActivationTemplate clears the value of the "rule_activation_template" field.
func (u *PromotionSettingUpsertBulk) ClearRuleActivationTemplate() *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.ClearRuleActivationTemplate()
	})
}

// SetRuleDirectTemplate sets the "rule_direct_template" field.
func (u *PromotionSettingUpsertBulk) SetRuleDirectTemplate(v string) *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetRuleDirectTemplate(v)
	})
}

// UpdateRuleDirectTemplate sets the "rule_direct_template" field to the value that was provided on create.
func (u *PromotionSettingUpsertBulk) UpdateRuleDirectTemplate() *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdateRuleDirectTemplate()
	})
}

// ClearRuleDirectTemplate clears the value of the "rule_direct_template" field.
func (u *PromotionSettingUpsertBulk) ClearRuleDirectTemplate() *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.ClearRuleDirectTemplate()
	})
}

// SetRuleIndirectTemplate sets the "rule_indirect_template" field.
func (u *PromotionSettingUpsertBulk) SetRuleIndirectTemplate(v string) *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetRuleIndirectTemplate(v)
	})
}

// UpdateRuleIndirectTemplate sets the "rule_indirect_template" field to the value that was provided on create.
func (u *PromotionSettingUpsertBulk) UpdateRuleIndirectTemplate() *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdateRuleIndirectTemplate()
	})
}

// ClearRuleIndirectTemplate clears the value of the "rule_indirect_template" field.
func (u *PromotionSettingUpsertBulk) ClearRuleIndirectTemplate() *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.ClearRuleIndirectTemplate()
	})
}

// SetRuleLevelSummaryTemplate sets the "rule_level_summary_template" field.
func (u *PromotionSettingUpsertBulk) SetRuleLevelSummaryTemplate(v string) *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetRuleLevelSummaryTemplate(v)
	})
}

// UpdateRuleLevelSummaryTemplate sets the "rule_level_summary_template" field to the value that was provided on create.
func (u *PromotionSettingUpsertBulk) UpdateRuleLevelSummaryTemplate() *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdateRuleLevelSummaryTemplate()
	})
}

// ClearRuleLevelSummaryTemplate clears the value of the "rule_level_summary_template" field.
func (u *PromotionSettingUpsertBulk) ClearRuleLevelSummaryTemplate() *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.ClearRuleLevelSummaryTemplate()
	})
}

// SetInviteBaseURL sets the "invite_base_url" field.
func (u *PromotionSettingUpsertBulk) SetInviteBaseURL(v string) *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetInviteBaseURL(v)
	})
}

// UpdateInviteBaseURL sets the "invite_base_url" field to the value that was provided on create.
func (u *PromotionSettingUpsertBulk) UpdateInviteBaseURL() *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdateInviteBaseURL()
	})
}

// ClearInviteBaseURL clears the value of the "invite_base_url" field.
func (u *PromotionSettingUpsertBulk) ClearInviteBaseURL() *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.ClearInviteBaseURL()
	})
}

// SetPosterLogoURL sets the "poster_logo_url" field.
func (u *PromotionSettingUpsertBulk) SetPosterLogoURL(v string) *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetPosterLogoURL(v)
	})
}

// UpdatePosterLogoURL sets the "poster_logo_url" field to the value that was provided on create.
func (u *PromotionSettingUpsertBulk) UpdatePosterLogoURL() *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdatePosterLogoURL()
	})
}

// ClearPosterLogoURL clears the value of the "poster_logo_url" field.
func (u *PromotionSettingUpsertBulk) ClearPosterLogoURL() *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.ClearPosterLogoURL()
	})
}

// SetPosterTitle sets the "poster_title" field.
func (u *PromotionSettingUpsertBulk) SetPosterTitle(v string) *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetPosterTitle(v)
	})
}

// UpdatePosterTitle sets the "poster_title" field to the value that was provided on create.
func (u *PromotionSettingUpsertBulk) UpdatePosterTitle() *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdatePosterTitle()
	})
}

// ClearPosterTitle clears the value of the "poster_title" field.
func (u *PromotionSettingUpsertBulk) ClearPosterTitle() *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.ClearPosterTitle()
	})
}

// SetPosterHeadline sets the "poster_headline" field.
func (u *PromotionSettingUpsertBulk) SetPosterHeadline(v string) *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetPosterHeadline(v)
	})
}

// UpdatePosterHeadline sets the "poster_headline" field to the value that was provided on create.
func (u *PromotionSettingUpsertBulk) UpdatePosterHeadline() *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdatePosterHeadline()
	})
}

// ClearPosterHeadline clears the value of the "poster_headline" field.
func (u *PromotionSettingUpsertBulk) ClearPosterHeadline() *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.ClearPosterHeadline()
	})
}

// SetPosterDescription sets the "poster_description" field.
func (u *PromotionSettingUpsertBulk) SetPosterDescription(v string) *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetPosterDescription(v)
	})
}

// UpdatePosterDescription sets the "poster_description" field to the value that was provided on create.
func (u *PromotionSettingUpsertBulk) UpdatePosterDescription() *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdatePosterDescription()
	})
}

// ClearPosterDescription clears the value of the "poster_description" field.
func (u *PromotionSettingUpsertBulk) ClearPosterDescription() *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.ClearPosterDescription()
	})
}

// SetPosterScanHint sets the "poster_scan_hint" field.
func (u *PromotionSettingUpsertBulk) SetPosterScanHint(v string) *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetPosterScanHint(v)
	})
}

// UpdatePosterScanHint sets the "poster_scan_hint" field to the value that was provided on create.
func (u *PromotionSettingUpsertBulk) UpdatePosterScanHint() *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdatePosterScanHint()
	})
}

// ClearPosterScanHint clears the value of the "poster_scan_hint" field.
func (u *PromotionSettingUpsertBulk) ClearPosterScanHint() *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.ClearPosterScanHint()
	})
}

// SetPosterTagsJSON sets the "poster_tags_json" field.
func (u *PromotionSettingUpsertBulk) SetPosterTagsJSON(v string) *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetPosterTagsJSON(v)
	})
}

// UpdatePosterTagsJSON sets the "poster_tags_json" field to the value that was provided on create.
func (u *PromotionSettingUpsertBulk) UpdatePosterTagsJSON() *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdatePosterTagsJSON()
	})
}

// ClearPosterTagsJSON clears the value of the "poster_tags_json" field.
func (u *PromotionSettingUpsertBulk) ClearPosterTagsJSON() *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.ClearPosterTagsJSON()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromotionSettingUpsertBulk) SetUpdatedAt(v time.Time) *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromotionSettingUpsertBulk) UpdateUpdatedAt() *PromotionSettingUpsertBulk {
	return u.Update(func(s *PromotionSettingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PromotionSettingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PromotionSettingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromotionSettingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromotionSettingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
