// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/promotionuser"
)

// PromotionUserCreate is the builder for creating a PromotionUser entity.
type PromotionUserCreate struct {
	config
	mutation *PromotionUserMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetInviteCode sets the "invite_code" field.
func (_c *PromotionUserCreate) SetInviteCode(v string) *PromotionUserCreate {
	_c.mutation.SetInviteCode(v)
	return _c
}

// SetParentUserID sets the "parent_user_id" field.
func (_c *PromotionUserCreate) SetParentUserID(v int64) *PromotionUserCreate {
	_c.mutation.SetParentUserID(v)
	return _c
}

// SetNillableParentUserID sets the "parent_user_id" field if the given value is not nil.
func (_c *PromotionUserCreate) SetNillableParentUserID(v *int64) *PromotionUserCreate {
	if v != nil {
		_c.SetParentUserID(*v)
	}
	return _c
}

// SetBindingSource sets the "binding_source" field.
func (_c *PromotionUserCreate) SetBindingSource(v string) *PromotionUserCreate {
	_c.mutation.SetBindingSource(v)
	return _c
}

// SetNillableBindingSource sets the "binding_source" field if the given value is not nil.
func (_c *PromotionUserCreate) SetNillableBindingSource(v *string) *PromotionUserCreate {
	if v != nil {
		_c.SetBindingSource(*v)
	}
	return _c
}

// SetBoundNote sets the "bound_note" field.
func (_c *PromotionUserCreate) SetBoundNote(v string) *PromotionUserCreate {
	_c.mutation.SetBoundNote(v)
	return _c
}

// SetNillableBoundNote sets the "bound_note" field if the given value is not nil.
func (_c *PromotionUserCreate) SetNillableBoundNote(v *string) *PromotionUserCreate {
	if v != nil {
		_c.SetBoundNote(*v)
	}
	return _c
}

// SetBoundAt sets the "bound_at" field.
func (_c *PromotionUserCreate) SetBoundAt(v time.Time) *PromotionUserCreate {
	_c.mutation.SetBoundAt(v)
	return _c
}

// SetNillableBoundAt sets the "bound_at" field if the given value is not nil.
func (_c *PromotionUserCreate) SetNillableBoundAt(v *time.Time) *PromotionUserCreate {
	if v != nil {
		_c.SetBoundAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PromotionUserCreate) SetCreatedAt(v time.Time) *PromotionUserCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PromotionUserCreate) SetNillableCreatedAt(v *time.Time) *PromotionUserCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PromotionUserCreate) SetUpdatedAt(v time.Time) *PromotionUserCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PromotionUserCreate) SetNillableUpdatedAt(v *time.Time) *PromotionUserCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PromotionUserCreate) SetID(v int64) *PromotionUserCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the PromotionUserMutation object of the builder.
func (_c *PromotionUserCreate) Mutation() *PromotionUserMutation {
	return _c.mutation
}

// Save creates the PromotionUser in the database.
func (_c *PromotionUserCreate) Save(ctx context.Context) (*PromotionUser, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PromotionUserCreate) SaveX(ctx context.Context) *PromotionUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromotionUserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromotionUserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PromotionUserCreate) defaults() {
	if _, ok := _c.mutation.BindingSource(); !ok {
		v := promotionuser.DefaultBindingSource
		_c.mutation.SetBindingSource(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := promotionuser.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := promotionuser.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PromotionUserCreate) check() error {
	if _, ok := _c.mutation.InviteCode(); !ok {
		return &ValidationError{Name: "invite_code", err: errors.New(`ent: missing required field "PromotionUser.invite_code"`)}
	}
	if v, ok := _c.mutation.InviteCode(); ok {
		if err := promotionuser.InviteCodeValidator(v); err != nil {
			return &ValidationError{Name: "invite_code", err: fmt.Errorf(`ent: validator failed for field "PromotionUser.invite_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BindingSource(); !ok {
		return &ValidationError{Name: "binding_source", err: errors.New(`ent: missing required field "PromotionUser.binding_source"`)}
	}
	if v, ok := _c.mutation.BindingSource(); ok {
		if err := promotionuser.BindingSourceValidator(v); err != nil {
			return &ValidationError{Name: "binding_source", err: fmt.Errorf(`ent: validator failed for field "PromotionUser.binding_source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PromotionUser.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PromotionUser.updated_at"`)}
	}
	return nil
}

func (_c *PromotionUserCreate) sqlSave(ctx context.Context) (*PromotionUser, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PromotionUserCreate) createSpec() (*PromotionUser, *sqlgraph.CreateSpec) {
	var (
		_node = &PromotionUser{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(promotionuser.Table, sqlgraph.NewFieldSpec(promotionuser.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.InviteCode(); ok {
		_spec.SetField(promotionuser.FieldInviteCode, field.TypeString, value)
		_node.InviteCode = value
	}
	if value, ok := _c.mutation.ParentUserID(); ok {
		_spec.SetField(promotionuser.FieldParentUserID, field.TypeInt64, value)
		_node.ParentUserID = &value
	}
	if value, ok := _c.mutation.BindingSource(); ok {
		_spec.SetField(promotionuser.FieldBindingSource, field.TypeString, value)
		_node.BindingSource = value
	}
	if value, ok := _c.mutation.BoundNote(); ok {
		_spec.SetField(promotionuser.FieldBoundNote, field.TypeString, value)
		_node.BoundNote = &value
	}
	if value, ok := _c.mutation.BoundAt(); ok {
		_spec.SetField(promotionuser.FieldBoundAt, field.TypeTime, value)
		_node.BoundAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(promotionuser.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(promotionuser.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PromotionUser.Create().
//		SetInviteCode(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromotionUserUpsert) {
//			SetInviteCode(v+v).
//		}).
//		Exec(ctx)
func (_c *PromotionUserCreate) OnConflict(opts ...sql.ConflictOption) *PromotionUserUpsertOne {
	_c.conflict = opts
	return &PromotionUserUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PromotionUser.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromotionUserCreate) OnConflictColumns(columns ...string) *PromotionUserUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromotionUserUpsertOne{
		create: _c,
	}
}

type (
	// PromotionUserUpsertOne is the builder for "upsert"-ing
	//  one PromotionUser node.
	PromotionUserUpsertOne struct {
		create *PromotionUserCreate
	}

	// PromotionUserUpsert is the "OnConflict" setter.
	PromotionUserUpsert struct {
		*sql.UpdateSet
	}
)

// SetInviteCode sets the "invite_code" field.
func (u *PromotionUserUpsert) SetInviteCode(v string) *PromotionUserUpsert {
	u.Set(promotionuser.FieldInviteCode, v)
	return u
}

// UpdateInviteCode sets the "invite_code" field to the value that was provided on create.
func (u *PromotionUserUpsert) UpdateInviteCode() *PromotionUserUpsert {
	u.SetExcluded(promotionuser.FieldInviteCode)
	return u
}

// SetParentUserID sets the "parent_user_id" field.
func (u *PromotionUserUpsert) SetParentUserID(v int64) *PromotionUserUpsert {
	u.Set(promotionuser.FieldParentUserID, v)
	return u
}

// UpdateParentUserID sets the "parent_user_id" field to the value that was provided on create.
func (u *PromotionUserUpsert) UpdateParentUserID() *PromotionUserUpsert {
	u.SetExcluded(promotionuser.FieldParentUserID)
	return u
}

// AddParentUserID adds v to the "parent_user_id" field.
func (u *PromotionUserUpsert) AddParentUserID(v int64) *PromotionUserUpsert {
	u.Add(promotionuser.FieldParentUserID, v)
	return u
}

// ClearParentUserID clears the value of the "parent_user_id" field.
func (u *PromotionUserUpsert) ClearParentUserID() *PromotionUserUpsert {
	u.SetNull(promotionuser.FieldParentUserID)
	return u
}

// SetBindingSource sets the "binding_source" field.
func (u *PromotionUserUpsert) SetBindingSource(v string) *PromotionUserUpsert {
	u.Set(promotionuser.FieldBindingSource, v)
	return u
}

// UpdateBindingSource sets the "binding_source" field to the value that was provided on create.
func (u *PromotionUserUpsert) UpdateBindingSource() *PromotionUserUpsert {
	u.SetExcluded(promotionuser.FieldBindingSource)
	return u
}

// SetBoundNote sets the "bound_note" field.
func (u *PromotionUserUpsert) SetBoundNote(v string) *PromotionUserUpsert {
	u.Set(promotionuser.FieldBoundNote, v)
	return u
}

// UpdateBoundNote sets the "bound_note" field to the value that was provided on create.
func (u *PromotionUserUpsert) UpdateBoundNote() *PromotionUserUpsert {
	u.SetExcluded(promotionuser.FieldBoundNote)
	return u
}

// ClearBoundNote clears the value of the "bound_note" field.
func (u *PromotionUserUpsert) ClearBoundNote() *PromotionUserUpsert {
	u.SetNull(promotionuser.FieldBoundNote)
	return u
}

// SetBoundAt sets the "bound_at" field.
func (u *PromotionUserUpsert) SetBoundAt(v time.Time) *PromotionUserUpsert {
	u.Set(promotionuser.FieldBoundAt, v)
	return u
}

// UpdateBoundAt sets the "bound_at" field to the value that was provided on create.
func (u *PromotionUserUpsert) UpdateBoundAt() *PromotionUserUpsert {
	u.SetExcluded(promotionuser.FieldBoundAt)
	return u
}

// ClearBoundAt clears the value of the "bound_at" field.
func (u *PromotionUserUpsert) ClearBoundAt() *PromotionUserUpsert {
	u.SetNull(promotionuser.FieldBoundAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromotionUserUpsert) SetUpdatedAt(v time.Time) *PromotionUserUpsert {
	u.Set(promotionuser.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromotionUserUpsert) UpdateUpdatedAt() *PromotionUserUpsert {
	u.SetExcluded(promotionuser.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PromotionUser.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(promotionuser.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PromotionUserUpsertOne) UpdateNewValues() *PromotionUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(promotionuser.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(promotionuser.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PromotionUser.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PromotionUserUpsertOne) Ignore() *PromotionUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromotionUserUpsertOne) DoNothing() *PromotionUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromotionUserCreate.OnConflict
// documentation for more info.
func (u *PromotionUserUpsertOne) Update(set func(*PromotionUserUpsert)) *PromotionUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromotionUserUpsert{UpdateSet: update})
	}))
	return u
}

// SetInviteCode sets the "invite_code" field.
func (u *PromotionUserUpsertOne) SetInviteCode(v string) *PromotionUserUpsertOne {
	return u.Update(func(s *PromotionUserUpsert) {
		s.SetInviteCode(v)
	})
}

// UpdateInviteCode sets the "invite_code" field to the value that was provided on create.
func (u *PromotionUserUpsertOne) UpdateInviteCode() *PromotionUserUpsertOne {
	return u.Update(func(s *PromotionUserUpsert) {
		s.UpdateInviteCode()
	})
}

// SetParentUserID sets the "parent_user_id" field.
func (u *PromotionUserUpsertOne) SetParentUserID(v int64) *PromotionUserUpsertOne {
	return u.Update(func(s *PromotionUserUpsert) {
		s.SetParentUserID(v)
	})
}

// AddParentUserID adds v to the "parent_user_id" field.
func (u *PromotionUserUpsertOne) AddParentUserID(v int64) *PromotionUserUpsertOne {
	return u.Update(func(s *PromotionUserUpsert) {
		s.AddParentUserID(v)
	})
}

// UpdateParentUserID sets the "parent_user_id" field to the value that was provided on create.
func (u *PromotionUserUpsertOne) UpdateParentUserID() *PromotionUserUpsertOne {
	return u.Update(func(s *PromotionUserUpsert) {
		s.UpdateParentUserID()
	})
}

// ClearParentUserID clears the value of the "parent_user_id" field.
func (u *PromotionUserUpsertOne) ClearParentUserID() *PromotionUserUpsertOne {
	return u.Update(func(s *PromotionUserUpsert) {
		s.ClearParentUserID()
	})
}

// SetBindingSource sets the "binding_source" field.
func (u *PromotionUserUpsertOne) SetBindingSource(v string) *PromotionUserUpsertOne {
	return u.Update(func(s *PromotionUserUpsert) {
		s.SetBindingSource(v)
	})
}

// UpdateBindingSource sets the "binding_source" field to the value that was provided on create.
func (u *PromotionUserUpsertOne) UpdateBindingSource() *PromotionUserUpsertOne {
	return u.Update(func(s *PromotionUserUpsert) {
		s.UpdateBindingSource()
	})
}

// SetBoundNote sets the "bound_note" field.
func (u *PromotionUserUpsertOne) SetBoundNote(v string) *PromotionUserUpsertOne {
	return u.Update(func(s *PromotionUserUpsert) {
		s.SetBoundNote(v)
	})
}

// UpdateBoundNote sets the "bound_note" field to the value that was provided on create.
func (u *PromotionUserUpsertOne) UpdateBoundNote() *PromotionUserUpsertOne {
	return u.Update(func(s *PromotionUserUpsert) {
		s.UpdateBoundNote()
	})
}

// ClearBoundNote clears the value of the "bound_note" field.
func (u *PromotionUserUpsertOne) ClearBoundNote() *PromotionUserUpsertOne {
	return u.Update(func(s *PromotionUserUpsert) {
		s.ClearBoundNote()
	})
}

// SetBoundAt sets the "bound_at" field.
func (u *PromotionUserUpsertOne) SetBoundAt(v time.Time) *PromotionUserUpsertOne {
	return u.Update(func(s *PromotionUserUpsert) {
		s.SetBoundAt(v)
	})
}

// UpdateBoundAt sets the "bound_at" field to the value that was provided on create.
func (u *PromotionUserUpsertOne) UpdateBoundAt() *PromotionUserUpsertOne {
	return u.Update(func(s *PromotionUserUpsert) {
		s.UpdateBoundAt()
	})
}

// ClearBoundAt clears the value of the "bound_at" field.
func (u *PromotionUserUpsertOne) ClearBoundAt() *PromotionUserUpsertOne {
	return u.Update(func(s *PromotionUserUpsert) {
		s.ClearBoundAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromotionUserUpsertOne) SetUpdatedAt(v time.Time) *PromotionUserUpsertOne {
	return u.Update(func(s *PromotionUserUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromotionUserUpsertOne) UpdateUpdatedAt() *PromotionUserUpsertOne {
	return u.Update(func(s *PromotionUserUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PromotionUserUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromotionUserCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromotionUserUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PromotionUserUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PromotionUserUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PromotionUserCreateBulk is the builder for creating many PromotionUser entities in bulk.
type PromotionUserCreateBulk struct {
	config
	err      error
	builders []*PromotionUserCreate
	conflict []sql.ConflictOption
}

// Save creates the PromotionUser entities in the database.
func (_c *PromotionUserCreateBulk) Save(ctx context.Context) ([]*PromotionUser, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PromotionUser, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PromotionUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PromotionUserCreateBulk) SaveX(ctx context.Context) []*PromotionUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromotionUserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromotionUserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PromotionUser.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromotionUserUpsert) {
//			SetInviteCode(v+v).
//		}).
//		Exec(ctx)
func (_c *PromotionUserCreateBulk) OnConflict(opts ...sql.ConflictOption) *PromotionUserUpsertBulk {
	_c.conflict = opts
	return &PromotionUserUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PromotionUser.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromotionUserCreateBulk) OnConflictColumns(columns ...string) *PromotionUserUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromotionUserUpsertBulk{
		create: _c,
	}
}

// PromotionUserUpsertBulk is the builder for "upsert"-ing
// a bulk of PromotionUser nodes.
type PromotionUserUpsertBulk struct {
	create *PromotionUserCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PromotionUser.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(promotionuser.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PromotionUserUpsertBulk) UpdateNewValues() *PromotionUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(promotionuser.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(promotionuser.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PromotionUser.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PromotionUserUpsertBulk) Ignore() *PromotionUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromotionUserUpsertBulk) DoNothing() *PromotionUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromotionUserCreateBulk.OnConflict
// documentation for more info.
func (u *PromotionUserUpsertBulk) Update(set func(*PromotionUserUpsert)) *PromotionUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromotionUserUpsert{UpdateSet: update})
	}))
	return u
}

// SetInviteCode sets the "invite_code" field.
func (u *PromotionUserUpsertBulk) SetInviteCode(v string) *PromotionUserUpsertBulk {
	return u.Update(func(s *PromotionUserUpsert) {
		s.SetInviteCode(v)
	})
}

// UpdateInviteCode sets the "invite_code" field to the value that was provided on create.
func (u *PromotionUserUpsertBulk) UpdateInviteCode() *PromotionUserUpsertBulk {
	return u.Update(func(s *PromotionUserUpsert) {
		s.UpdateInviteCode()
	})
}

// SetParentUserID sets the "parent_user_id" field.
func (u *PromotionUserUpsertBulk) SetParentUserID(v int64) *PromotionUserUpsertBulk {
	return u.Update(func(s *PromotionUserUpsert) {
		s.SetParentUserID(v)
	})
}

// AddParentUserID adds v to the "parent_user_id" field.
func (u *PromotionUserUpsertBulk) AddParentUserID(v int64) *PromotionUserUpsertBulk {
	return u.Update(func(s *PromotionUserUpsert) {
		s.AddParentUserID(v)
	})
}

// UpdateParentUserID sets the "parent_user_id" field to the value that was provided on create.
func (u *PromotionUserUpsertBulk) UpdateParentUserID() *PromotionUserUpsertBulk {
	return u.Update(func(s *PromotionUserUpsert) {
		s.UpdateParentUserID()
	})
}

// ClearParentUserID clears the value of the "parent_user_id" field.
func (u *PromotionUserUpsertBulk) ClearParentUserID() *PromotionUserUpsertBulk {
	return u.Update(func(s *PromotionUserUpsert) {
		s.ClearParentUserID()
	})
}

// SetBindingSource sets the "binding_source" field.
func (u *PromotionUserUpsertBulk) SetBindingSource(v string) *PromotionUserUpsertBulk {
	return u.Update(func(s *PromotionUserUpsert) {
		s.SetBindingSource(v)
	})
}

// UpdateBindingSource sets the "binding_source" field to the value that was provided on create.
func (u *PromotionUserUpsertBulk) UpdateBindingSource() *PromotionUserUpsertBulk {
	return u.Update(func(s *PromotionUserUpsert) {
		s.UpdateBindingSource()
	})
}

// SetBoundNote sets the "bound_note" field.
func (u *PromotionUserUpsertBulk) SetBoundNote(v string) *PromotionUserUpsertBulk {
	return u.Update(func(s *PromotionUserUpsert) {
		s.SetBoundNote(v)
	})
}

// UpdateBoundNote sets the "bound_note" field to the value that was provided on create.
func (u *PromotionUserUpsertBulk) UpdateBoundNote() *PromotionUserUpsertBulk {
	return u.Update(func(s *PromotionUserUpsert) {
		s.UpdateBoundNote()
	})
}

// ClearBoundNote clears the value of the "bound_note" field.
func (u *PromotionUserUpsertBulk) ClearBoundNote() *PromotionUserUpsertBulk {
	return u.Update(func(s *PromotionUserUpsert) {
		s.ClearBoundNote()
	})
}

// SetBoundAt sets the "bound_at" field.
func (u *PromotionUserUpsertBulk) SetBoundAt(v time.Time) *PromotionUserUpsertBulk {
	return u.Update(func(s *PromotionUserUpsert) {
		s.SetBoundAt(v)
	})
}

// UpdateBoundAt sets the "bound_at" field to the value that was provided on create.
func (u *PromotionUserUpsertBulk) UpdateBoundAt() *PromotionUserUpsertBulk {
	return u.Update(func(s *PromotionUserUpsert) {
		s.UpdateBoundAt()
	})
}

// ClearBoundAt clears the value of the "bound_at" field.
func (u *PromotionUserUpsertBulk) ClearBoundAt() *PromotionUserUpsertBulk {
	return u.Update(func(s *PromotionUserUpsert) {
		s.ClearBoundAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromotionUserUpsertBulk) SetUpdatedAt(v time.Time) *PromotionUserUpsertBulk {
	return u.Update(func(s *PromotionUserUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromotionUserUpsertBulk) UpdateUpdatedAt() *PromotionUserUpsertBulk {
	return u.Update(func(s *PromotionUserUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PromotionUserUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PromotionUserCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromotionUserCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromotionUserUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
