// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/promotionsettlementbatch"
)

// PromotionSettlementBatchDelete is the builder for deleting a PromotionSettlementBatch entity.
type PromotionSettlementBatchDelete struct {
	config
	hooks    []Hook
	mutation *PromotionSettlementBatchMutation
}

// Where appends a list predicates to the PromotionSettlementBatchDelete builder.
func (_d *PromotionSettlementBatchDelete) Where(ps ...predicate.PromotionSettlementBatch) *PromotionSettlementBatchDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PromotionSettlementBatchDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PromotionSettlementBatchDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PromotionSettlementBatchDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(promotionsettlementbatch.Table, sqlgraph.NewFieldSpec(promotionsettlementbatch.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PromotionSettlementBatchDeleteOne is the builder for deleting a single PromotionSettlementBatch entity.
type PromotionSettlementBatchDeleteOne struct {
	_d *PromotionSettlementBatchDelete
}

// Where appends a list predicates to the PromotionSettlementBatchDelete builder.
func (_d *PromotionSettlementBatchDeleteOne) Where(ps ...predicate.PromotionSettlementBatch) *PromotionSettlementBatchDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PromotionSettlementBatchDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{promotionsettlementbatch.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PromotionSettlementBatchDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
