// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/promotionactivation"
)

// PromotionActivationCreate is the builder for creating a PromotionActivation entity.
type PromotionActivationCreate struct {
	config
	mutation *PromotionActivationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPromoterUserID sets the "promoter_user_id" field.
func (_c *PromotionActivationCreate) SetPromoterUserID(v int64) *PromotionActivationCreate {
	_c.mutation.SetPromoterUserID(v)
	return _c
}

// SetActivatedAt sets the "activated_at" field.
func (_c *PromotionActivationCreate) SetActivatedAt(v time.Time) *PromotionActivationCreate {
	_c.mutation.SetActivatedAt(v)
	return _c
}

// SetThresholdAmount sets the "threshold_amount" field.
func (_c *PromotionActivationCreate) SetThresholdAmount(v float64) *PromotionActivationCreate {
	_c.mutation.SetThresholdAmount(v)
	return _c
}

// SetTriggerUsageAmount sets the "trigger_usage_amount" field.
func (_c *PromotionActivationCreate) SetTriggerUsageAmount(v float64) *PromotionActivationCreate {
	_c.mutation.SetTriggerUsageAmount(v)
	return _c
}

// SetCommissionRecordID sets the "commission_record_id" field.
func (_c *PromotionActivationCreate) SetCommissionRecordID(v int64) *PromotionActivationCreate {
	_c.mutation.SetCommissionRecordID(v)
	return _c
}

// SetNillableCommissionRecordID sets the "commission_record_id" field if the given value is not nil.
func (_c *PromotionActivationCreate) SetNillableCommissionRecordID(v *int64) *PromotionActivationCreate {
	if v != nil {
		_c.SetCommissionRecordID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PromotionActivationCreate) SetCreatedAt(v time.Time) *PromotionActivationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PromotionActivationCreate) SetNillableCreatedAt(v *time.Time) *PromotionActivationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PromotionActivationCreate) SetUpdatedAt(v time.Time) *PromotionActivationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PromotionActivationCreate) SetNillableUpdatedAt(v *time.Time) *PromotionActivationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PromotionActivationCreate) SetID(v int64) *PromotionActivationCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the PromotionActivationMutation object of the builder.
func (_c *PromotionActivationCreate) Mutation() *PromotionActivationMutation {
	return _c.mutation
}

// Save creates the PromotionActivation in the database.
func (_c *PromotionActivationCreate) Save(ctx context.Context) (*PromotionActivation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PromotionActivationCreate) SaveX(ctx context.Context) *PromotionActivation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromotionActivationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromotionActivationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PromotionActivationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := promotionactivation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := promotionactivation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PromotionActivationCreate) check() error {
	if _, ok := _c.mutation.PromoterUserID(); !ok {
		return &ValidationError{Name: "promoter_user_id", err: errors.New(`ent: missing required field "PromotionActivation.promoter_user_id"`)}
	}
	if _, ok := _c.mutation.ActivatedAt(); !ok {
		return &ValidationError{Name: "activated_at", err: errors.New(`ent: missing required field "PromotionActivation.activated_at"`)}
	}
	if _, ok := _c.mutation.ThresholdAmount(); !ok {
		return &ValidationError{Name: "threshold_amount", err: errors.New(`ent: missing required field "PromotionActivation.threshold_amount"`)}
	}
	if _, ok := _c.mutation.TriggerUsageAmount(); !ok {
		return &ValidationError{Name: "trigger_usage_amount", err: errors.New(`ent: missing required field "PromotionActivation.trigger_usage_amount"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PromotionActivation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PromotionActivation.updated_at"`)}
	}
	return nil
}

func (_c *PromotionActivationCreate) sqlSave(ctx context.Context) (*PromotionActivation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PromotionActivationCreate) createSpec() (*PromotionActivation, *sqlgraph.CreateSpec) {
	var (
		_node = &PromotionActivation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(promotionactivation.Table, sqlgraph.NewFieldSpec(promotionactivation.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.PromoterUserID(); ok {
		_spec.SetField(promotionactivation.FieldPromoterUserID, field.TypeInt64, value)
		_node.PromoterUserID = value
	}
	if value, ok := _c.mutation.ActivatedAt(); ok {
		_spec.SetField(promotionactivation.FieldActivatedAt, field.TypeTime, value)
		_node.ActivatedAt = value
	}
	if value, ok := _c.mutation.ThresholdAmount(); ok {
		_spec.SetField(promotionactivation.FieldThresholdAmount, field.TypeFloat64, value)
		_node.ThresholdAmount = value
	}
	if value, ok := _c.mutation.TriggerUsageAmount(); ok {
		_spec.SetField(promotionactivation.FieldTriggerUsageAmount, field.TypeFloat64, value)
		_node.TriggerUsageAmount = value
	}
	if value, ok := _c.mutation.CommissionRecordID(); ok {
		_spec.SetField(promotionactivation.FieldCommissionRecordID, field.TypeInt64, value)
		_node.CommissionRecordID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(promotionactivation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(promotionactivation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PromotionActivation.Create().
//		SetPromoterUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromotionActivationUpsert) {
//			SetPromoterUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *PromotionActivationCreate) OnConflict(opts ...sql.ConflictOption) *PromotionActivationUpsertOne {
	_c.conflict = opts
	return &PromotionActivationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PromotionActivation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromotionActivationCreate) OnConflictColumns(columns ...string) *PromotionActivationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromotionActivationUpsertOne{
		create: _c,
	}
}

type (
	// PromotionActivationUpsertOne is the builder for "upsert"-ing
	//  one PromotionActivation node.
	PromotionActivationUpsertOne struct {
		create *PromotionActivationCreate
	}

	// PromotionActivationUpsert is the "OnConflict" setter.
	PromotionActivationUpsert struct {
		*sql.UpdateSet
	}
)

// SetPromoterUserID sets the "promoter_user_id" field.
func (u *PromotionActivationUpsert) SetPromoterUserID(v int64) *PromotionActivationUpsert {
	u.Set(promotionactivation.FieldPromoterUserID, v)
	return u
}

// UpdatePromoterUserID sets the "promoter_user_id" field to the value that was provided on create.
func (u *PromotionActivationUpsert) UpdatePromoterUserID() *PromotionActivationUpsert {
	u.SetExcluded(promotionactivation.FieldPromoterUserID)
	return u
}

// AddPromoterUserID adds v to the "promoter_user_id" field.
func (u *PromotionActivationUpsert) AddPromoterUserID(v int64) *PromotionActivationUpsert {
	u.Add(promotionactivation.FieldPromoterUserID, v)
	return u
}

// SetActivatedAt sets the "activated_at" field.
func (u *PromotionActivationUpsert) SetActivatedAt(v time.Time) *PromotionActivationUpsert {
	u.Set(promotionactivation.FieldActivatedAt, v)
	return u
}

// UpdateActivatedAt sets the "activated_at" field to the value that was provided on create.
func (u *PromotionActivationUpsert) UpdateActivatedAt() *PromotionActivationUpsert {
	u.SetExcluded(promotionactivation.FieldActivatedAt)
	return u
}

// SetThresholdAmount sets the "threshold_amount" field.
func (u *PromotionActivationUpsert) SetThresholdAmount(v float64) *PromotionActivationUpsert {
	u.Set(promotionactivation.FieldThresholdAmount, v)
	return u
}

// UpdateThresholdAmount sets the "threshold_amount" field to the value that was provided on create.
func (u *PromotionActivationUpsert) UpdateThresholdAmount() *PromotionActivationUpsert {
	u.SetExcluded(promotionactivation.FieldThresholdAmount)
	return u
}

// AddThresholdAmount adds v to the "threshold_amount" field.
func (u *PromotionActivationUpsert) AddThresholdAmount(v float64) *PromotionActivationUpsert {
	u.Add(promotionactivation.FieldThresholdAmount, v)
	return u
}

// SetTriggerUsageAmount sets the "trigger_usage_amount" field.
func (u *PromotionActivationUpsert) SetTriggerUsageAmount(v float64) *PromotionActivationUpsert {
	u.Set(promotionactivation.FieldTriggerUsageAmount, v)
	return u
}

// UpdateTriggerUsageAmount sets the "trigger_usage_amount" field to the value that was provided on create.
func (u *PromotionActivationUpsert) UpdateTriggerUsageAmount() *PromotionActivationUpsert {
	u.SetExcluded(promotionactivation.FieldTriggerUsageAmount)
	return u
}

// AddTriggerUsageAmount adds v to the "trigger_usage_amount" field.
func (u *PromotionActivationUpsert) AddTriggerUsageAmount(v float64) *PromotionActivationUpsert {
	u.Add(promotionactivation.FieldTriggerUsageAmount, v)
	return u
}

// SetCommissionRecordID sets the "commission_record_id" field.
func (u *PromotionActivationUpsert) SetCommissionRecordID(v int64) *PromotionActivationUpsert {
	u.Set(promotionactivation.FieldCommissionRecordID, v)
	return u
}

// UpdateCommissionRecordID sets the "commission_record_id" field to the value that was provided on create.
func (u *PromotionActivationUpsert) UpdateCommissionRecordID() *PromotionActivationUpsert {
	u.SetExcluded(promotionactivation.FieldCommissionRecordID)
	return u
}

// AddCommissionRecordID adds v to the "commission_record_id" field.
func (u *PromotionActivationUpsert) AddCommissionRecordID(v int64) *PromotionActivationUpsert {
	u.Add(promotionactivation.FieldCommissionRecordID, v)
	return u
}

// ClearCommissionRecordID clears the value of the "commission_record_id" field.
func (u *PromotionActivationUpsert) ClearCommissionRecordID() *PromotionActivationUpsert {
	u.SetNull(promotionactivation.FieldCommissionRecordID)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromotionActivationUpsert) SetUpdatedAt(v time.Time) *PromotionActivationUpsert {
	u.Set(promotionactivation.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromotionActivationUpsert) UpdateUpdatedAt() *PromotionActivationUpsert {
	u.SetExcluded(promotionactivation.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PromotionActivation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(promotionactivation.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PromotionActivationUpsertOne) UpdateNewValues() *PromotionActivationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(promotionactivation.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(promotionactivation.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PromotionActivation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PromotionActivationUpsertOne) Ignore() *PromotionActivationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromotionActivationUpsertOne) DoNothing() *PromotionActivationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromotionActivationCreate.OnConflict
// documentation for more info.
func (u *PromotionActivationUpsertOne) Update(set func(*PromotionActivationUpsert)) *PromotionActivationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromotionActivationUpsert{UpdateSet: update})
	}))
	return u
}

// SetPromoterUserID sets the "promoter_user_id" field.
func (u *PromotionActivationUpsertOne) SetPromoterUserID(v int64) *PromotionActivationUpsertOne {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.SetPromoterUserID(v)
	})
}

// AddPromoterUserID adds v to the "promoter_user_id" field.
func (u *PromotionActivationUpsertOne) AddPromoterUserID(v int64) *PromotionActivationUpsertOne {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.AddPromoterUserID(v)
	})
}

// UpdatePromoterUserID sets the "promoter_user_id" field to the value that was provided on create.
func (u *PromotionActivationUpsertOne) UpdatePromoterUserID() *PromotionActivationUpsertOne {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.UpdatePromoterUserID()
	})
}

// SetActivatedAt sets the "activated_at" field.
func (u *PromotionActivationUpsertOne) SetActivatedAt(v time.Time) *PromotionActivationUpsertOne {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.SetActivatedAt(v)
	})
}

// UpdateActivatedAt sets the "activated_at" field to the value that was provided on create.
func (u *PromotionActivationUpsertOne) UpdateActivatedAt() *PromotionActivationUpsertOne {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.UpdateActivatedAt()
	})
}

// SetThresholdAmount sets the "threshold_amount" field.
func (u *PromotionActivationUpsertOne) SetThresholdAmount(v float64) *PromotionActivationUpsertOne {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.SetThresholdAmount(v)
	})
}

// AddThresholdAmount adds v to the "threshold_amount" field.
func (u *PromotionActivationUpsertOne) AddThresholdAmount(v float64) *PromotionActivationUpsertOne {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.AddThresholdAmount(v)
	})
}

// UpdateThresholdAmount sets the "threshold_amount" field to the value that was provided on create.
func (u *PromotionActivationUpsertOne) UpdateThresholdAmount() *PromotionActivationUpsertOne {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.UpdateThresholdAmount()
	})
}

// SetTriggerUsageAmount sets the "trigger_usage_amount" field.
func (u *PromotionActivationUpsertOne) SetTriggerUsageAmount(v float64) *PromotionActivationUpsertOne {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.SetTriggerUsageAmount(v)
	})
}

// AddTriggerUsageAmount adds v to the "trigger_usage_amount" field.
func (u *PromotionActivationUpsertOne) AddTriggerUsageAmount(v float64) *PromotionActivationUpsertOne {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.AddTriggerUsageAmount(v)
	})
}

// UpdateTriggerUsageAmount sets the "trigger_usage_amount" field to the value that was provided on create.
func (u *PromotionActivationUpsertOne) UpdateTriggerUsageAmount() *PromotionActivationUpsertOne {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.UpdateTriggerUsageAmount()
	})
}

// SetCommissionRecordID sets the "commission_record_id" field.
func (u *PromotionActivationUpsertOne) SetCommissionRecordID(v int64) *PromotionActivationUpsertOne {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.SetCommissionRecordID(v)
	})
}

// AddCommissionRecordID adds v to the "commission_record_id" field.
func (u *PromotionActivationUpsertOne) AddCommissionRecordID(v int64) *PromotionActivationUpsertOne {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.AddCommissionRecordID(v)
	})
}

// UpdateCommissionRecordID sets the "commission_record_id" field to the value that was provided on create.
func (u *PromotionActivationUpsertOne) UpdateCommissionRecordID() *PromotionActivationUpsertOne {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.UpdateCommissionRecordID()
	})
}

// ClearCommissionRecordID clears the value of the "commission_record_id" field.
func (u *PromotionActivationUpsertOne) ClearCommissionRecordID() *PromotionActivationUpsertOne {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.ClearCommissionRecordID()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromotionActivationUpsertOne) SetUpdatedAt(v time.Time) *PromotionActivationUpsertOne {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromotionActivationUpsertOne) UpdateUpdatedAt() *PromotionActivationUpsertOne {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PromotionActivationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromotionActivationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromotionActivationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PromotionActivationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PromotionActivationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PromotionActivationCreateBulk is the builder for creating many PromotionActivation entities in bulk.
type PromotionActivationCreateBulk struct {
	config
	err      error
	builders []*PromotionActivationCreate
	conflict []sql.ConflictOption
}

// Save creates the PromotionActivation entities in the database.
func (_c *PromotionActivationCreateBulk) Save(ctx context.Context) ([]*PromotionActivation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PromotionActivation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PromotionActivationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PromotionActivationCreateBulk) SaveX(ctx context.Context) []*PromotionActivation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromotionActivationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromotionActivationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PromotionActivation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromotionActivationUpsert) {
//			SetPromoterUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *PromotionActivationCreateBulk) OnConflict(opts ...sql.ConflictOption) *PromotionActivationUpsertBulk {
	_c.conflict = opts
	return &PromotionActivationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PromotionActivation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromotionActivationCreateBulk) OnConflictColumns(columns ...string) *PromotionActivationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromotionActivationUpsertBulk{
		create: _c,
	}
}

// PromotionActivationUpsertBulk is the builder for "upsert"-ing
// a bulk of PromotionActivation nodes.
type PromotionActivationUpsertBulk struct {
	create *PromotionActivationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PromotionActivation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(promotionactivation.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PromotionActivationUpsertBulk) UpdateNewValues() *PromotionActivationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(promotionactivation.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(promotionactivation.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PromotionActivation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PromotionActivationUpsertBulk) Ignore() *PromotionActivationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromotionActivationUpsertBulk) DoNothing() *PromotionActivationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromotionActivationCreateBulk.OnConflict
// documentation for more info.
func (u *PromotionActivationUpsertBulk) Update(set func(*PromotionActivationUpsert)) *PromotionActivationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromotionActivationUpsert{UpdateSet: update})
	}))
	return u
}

// SetPromoterUserID sets the "promoter_user_id" field.
func (u *PromotionActivationUpsertBulk) SetPromoterUserID(v int64) *PromotionActivationUpsertBulk {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.SetPromoterUserID(v)
	})
}

// AddPromoterUserID adds v to the "promoter_user_id" field.
func (u *PromotionActivationUpsertBulk) AddPromoterUserID(v int64) *PromotionActivationUpsertBulk {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.AddPromoterUserID(v)
	})
}

// UpdatePromoterUserID sets the "promoter_user_id" field to the value that was provided on create.
func (u *PromotionActivationUpsertBulk) UpdatePromoterUserID() *PromotionActivationUpsertBulk {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.UpdatePromoterUserID()
	})
}

// SetActivatedAt sets the "activated_at" field.
func (u *PromotionActivationUpsertBulk) SetActivatedAt(v time.Time) *PromotionActivationUpsertBulk {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.SetActivatedAt(v)
	})
}

// UpdateActivatedAt sets the "activated_at" field to the value that was provided on create.
func (u *PromotionActivationUpsertBulk) UpdateActivatedAt() *PromotionActivationUpsertBulk {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.UpdateActivatedAt()
	})
}

// SetThresholdAmount sets the "threshold_amount" field.
func (u *PromotionActivationUpsertBulk) SetThresholdAmount(v float64) *PromotionActivationUpsertBulk {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.SetThresholdAmount(v)
	})
}

// AddThresholdAmount adds v to the "threshold_amount" field.
func (u *PromotionActivationUpsertBulk) AddThresholdAmount(v float64) *PromotionActivationUpsertBulk {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.AddThresholdAmount(v)
	})
}

// UpdateThresholdAmount sets the "threshold_amount" field to the value that was provided on create.
func (u *PromotionActivationUpsertBulk) UpdateThresholdAmount() *PromotionActivationUpsertBulk {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.UpdateThresholdAmount()
	})
}

// SetTriggerUsageAmount sets the "trigger_usage_amount" field.
func (u *PromotionActivationUpsertBulk) SetTriggerUsageAmount(v float64) *PromotionActivationUpsertBulk {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.SetTriggerUsageAmount(v)
	})
}

// AddTriggerUsageAmount adds v to the "trigger_usage_amount" field.
func (u *PromotionActivationUpsertBulk) AddTriggerUsageAmount(v float64) *PromotionActivationUpsertBulk {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.AddTriggerUsageAmount(v)
	})
}

// UpdateTriggerUsageAmount sets the "trigger_usage_amount" field to the value that was provided on create.
func (u *PromotionActivationUpsertBulk) UpdateTriggerUsageAmount() *PromotionActivationUpsertBulk {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.UpdateTriggerUsageAmount()
	})
}

// SetCommissionRecordID sets the "commission_record_id" field.
func (u *PromotionActivationUpsertBulk) SetCommissionRecordID(v int64) *PromotionActivationUpsertBulk {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.SetCommissionRecordID(v)
	})
}

// AddCommissionRecordID adds v to the "commission_record_id" field.
func (u *PromotionActivationUpsertBulk) AddCommissionRecordID(v int64) *PromotionActivationUpsertBulk {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.AddCommissionRecordID(v)
	})
}

// UpdateCommissionRecordID sets the "commission_record_id" field to the value that was provided on create.
func (u *PromotionActivationUpsertBulk) UpdateCommissionRecordID() *PromotionActivationUpsertBulk {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.UpdateCommissionRecordID()
	})
}

// ClearCommissionRecordID clears the value of the "commission_record_id" field.
func (u *PromotionActivationUpsertBulk) ClearCommissionRecordID() *PromotionActivationUpsertBulk {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.ClearCommissionRecordID()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromotionActivationUpsertBulk) SetUpdatedAt(v time.Time) *PromotionActivationUpsertBulk {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromotionActivationUpsertBulk) UpdateUpdatedAt() *PromotionActivationUpsertBulk {
	return u.Update(func(s *PromotionActivationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PromotionActivationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PromotionActivationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromotionActivationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromotionActivationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
