// Code generated by ent, DO NOT EDIT.

package promotioncommissionrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the promotioncommissionrecord type in the database.
	Label = "promotion_commission_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBeneficiaryUserID holds the string denoting the beneficiary_user_id field in the database.
	FieldBeneficiaryUserID = "beneficiary_user_id"
	// FieldSourceUserID holds the string denoting the source_user_id field in the database.
	FieldSourceUserID = "source_user_id"
	// FieldBusinessDate holds the string denoting the business_date field in the database.
	FieldBusinessDate = "business_date"
	// FieldCommissionType holds the string denoting the commission_type field in the database.
	FieldCommissionType = "commission_type"
	// FieldRelationDepth holds the string denoting the relation_depth field in the database.
	FieldRelationDepth = "relation_depth"
	// FieldLevelID holds the string denoting the level_id field in the database.
	FieldLevelID = "level_id"
	// FieldLevelSnapshot holds the string denoting the level_snapshot field in the database.
	FieldLevelSnapshot = "level_snapshot"
	// FieldRateSnapshot holds the string denoting the rate_snapshot field in the database.
	FieldRateSnapshot = "rate_snapshot"
	// FieldBaseAmount holds the string denoting the base_amount field in the database.
	FieldBaseAmount = "base_amount"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSettlementBatchID holds the string denoting the settlement_batch_id field in the database.
	FieldSettlementBatchID = "settlement_batch_id"
	// FieldNote holds the string denoting the note field in the database.
	FieldNote = "note"
	// FieldCreatedByUserID holds the string denoting the created_by_user_id field in the database.
	FieldCreatedByUserID = "created_by_user_id"
	// FieldSettledAt holds the string denoting the settled_at field in the database.
	FieldSettledAt = "settled_at"
	// FieldCancelledAt holds the string denoting the cancelled_at field in the database.
	FieldCancelledAt = "cancelled_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the promotioncommissionrecord in the database.
	Table = "promotion_commission_records"
)

// Columns holds all SQL columns for promotioncommissionrecord fields.
var Columns = []string{
	FieldID,
	FieldBeneficiaryUserID,
	FieldSourceUserID,
	FieldBusinessDate,
	FieldCommissionType,
	FieldRelationDepth,
	FieldLevelID,
	FieldLevelSnapshot,
	FieldRateSnapshot,
	FieldBaseAmount,
	FieldAmount,
	FieldStatus,
	FieldSettlementBatchID,
	FieldNote,
	FieldCreatedByUserID,
	FieldSettledAt,
	FieldCancelledAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CommissionTypeValidator is a validator for the "commission_type" field. It is called by the builders before save.
	CommissionTypeValidator func(string) error
	// DefaultRelationDepth holds the default value on creation for the "relation_depth" field.
	DefaultRelationDepth int8
	// LevelSnapshotValidator is a validator for the "level_snapshot" field. It is called by the builders before save.
	LevelSnapshotValidator func(string) error
	// DefaultBaseAmount holds the default value on creation for the "base_amount" field.
	DefaultBaseAmount float64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the PromotionCommissionRecord queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBeneficiaryUserID orders the results by the beneficiary_user_id field.
func ByBeneficiaryUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBeneficiaryUserID, opts...).ToFunc()
}

// BySourceUserID orders the results by the source_user_id field.
func BySourceUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceUserID, opts...).ToFunc()
}

// ByBusinessDate orders the results by the business_date field.
func ByBusinessDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBusinessDate, opts...).ToFunc()
}

// ByCommissionType orders the results by the commission_type field.
func ByCommissionType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommissionType, opts...).ToFunc()
}

// ByRelationDepth orders the results by the relation_depth field.
func ByRelationDepth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRelationDepth, opts...).ToFunc()
}

// ByLevelID orders the results by the level_id field.
func ByLevelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLevelID, opts...).ToFunc()
}

// ByLevelSnapshot orders the results by the level_snapshot field.
func ByLevelSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLevelSnapshot, opts...).ToFunc()
}

// ByRateSnapshot orders the results by the rate_snapshot field.
func ByRateSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRateSnapshot, opts...).ToFunc()
}

// ByBaseAmount orders the results by the base_amount field.
func ByBaseAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseAmount, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySettlementBatchID orders the results by the settlement_batch_id field.
func BySettlementBatchID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettlementBatchID, opts...).ToFunc()
}

// ByNote orders the results by the note field.
func ByNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNote, opts...).ToFunc()
}

// ByCreatedByUserID orders the results by the created_by_user_id field.
func ByCreatedByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedByUserID, opts...).ToFunc()
}

// BySettledAt orders the results by the settled_at field.
func BySettledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettledAt, opts...).ToFunc()
}

// ByCancelledAt orders the results by the cancelled_at field.
func ByCancelledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCancelledAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
