// Code generated by ent, DO NOT EDIT.

package promotioncommissionrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLTE(FieldID, id))
}

// BeneficiaryUserID applies equality check predicate on the "beneficiary_user_id" field. It's identical to BeneficiaryUserIDEQ.
func BeneficiaryUserID(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldBeneficiaryUserID, v))
}

// SourceUserID applies equality check predicate on the "source_user_id" field. It's identical to SourceUserIDEQ.
func SourceUserID(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldSourceUserID, v))
}

// BusinessDate applies equality check predicate on the "business_date" field. It's identical to BusinessDateEQ.
func BusinessDate(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldBusinessDate, v))
}

// CommissionType applies equality check predicate on the "commission_type" field. It's identical to CommissionTypeEQ.
func CommissionType(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldCommissionType, v))
}

// RelationDepth applies equality check predicate on the "relation_depth" field. It's identical to RelationDepthEQ.
func RelationDepth(v int8) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldRelationDepth, v))
}

// LevelID applies equality check predicate on the "level_id" field. It's identical to LevelIDEQ.
func LevelID(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldLevelID, v))
}

// LevelSnapshot applies equality check predicate on the "level_snapshot" field. It's identical to LevelSnapshotEQ.
func LevelSnapshot(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldLevelSnapshot, v))
}

// RateSnapshot applies equality check predicate on the "rate_snapshot" field. It's identical to RateSnapshotEQ.
func RateSnapshot(v float64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldRateSnapshot, v))
}

// BaseAmount applies equality check predicate on the "base_amount" field. It's identical to BaseAmountEQ.
func BaseAmount(v float64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldBaseAmount, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldAmount, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldStatus, v))
}

// SettlementBatchID applies equality check predicate on the "settlement_batch_id" field. It's identical to SettlementBatchIDEQ.
func SettlementBatchID(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldSettlementBatchID, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldNote, v))
}

// CreatedByUserID applies equality check predicate on the "created_by_user_id" field. It's identical to CreatedByUserIDEQ.
func CreatedByUserID(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldCreatedByUserID, v))
}

// SettledAt applies equality check predicate on the "settled_at" field. It's identical to SettledAtEQ.
func SettledAt(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldSettledAt, v))
}

// CancelledAt applies equality check predicate on the "cancelled_at" field. It's identical to CancelledAtEQ.
func CancelledAt(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldCancelledAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldUpdatedAt, v))
}

// BeneficiaryUserIDEQ applies the EQ predicate on the "beneficiary_user_id" field.
func BeneficiaryUserIDEQ(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldBeneficiaryUserID, v))
}

// BeneficiaryUserIDNEQ applies the NEQ predicate on the "beneficiary_user_id" field.
func BeneficiaryUserIDNEQ(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNEQ(FieldBeneficiaryUserID, v))
}

// BeneficiaryUserIDIn applies the In predicate on the "beneficiary_user_id" field.
func BeneficiaryUserIDIn(vs ...int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldIn(FieldBeneficiaryUserID, vs...))
}

// BeneficiaryUserIDNotIn applies the NotIn predicate on the "beneficiary_user_id" field.
func BeneficiaryUserIDNotIn(vs ...int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNotIn(FieldBeneficiaryUserID, vs...))
}

// BeneficiaryUserIDGT applies the GT predicate on the "beneficiary_user_id" field.
func BeneficiaryUserIDGT(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGT(FieldBeneficiaryUserID, v))
}

// BeneficiaryUserIDGTE applies the GTE predicate on the "beneficiary_user_id" field.
func BeneficiaryUserIDGTE(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGTE(FieldBeneficiaryUserID, v))
}

// BeneficiaryUserIDLT applies the LT predicate on the "beneficiary_user_id" field.
func BeneficiaryUserIDLT(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLT(FieldBeneficiaryUserID, v))
}

// BeneficiaryUserIDLTE applies the LTE predicate on the "beneficiary_user_id" field.
func BeneficiaryUserIDLTE(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLTE(FieldBeneficiaryUserID, v))
}

// SourceUserIDEQ applies the EQ predicate on the "source_user_id" field.
func SourceUserIDEQ(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldSourceUserID, v))
}

// SourceUserIDNEQ applies the NEQ predicate on the "source_user_id" field.
func SourceUserIDNEQ(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNEQ(FieldSourceUserID, v))
}

// SourceUserIDIn applies the In predicate on the "source_user_id" field.
func SourceUserIDIn(vs ...int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldIn(FieldSourceUserID, vs...))
}

// SourceUserIDNotIn applies the NotIn predicate on the "source_user_id" field.
func SourceUserIDNotIn(vs ...int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNotIn(FieldSourceUserID, vs...))
}

// SourceUserIDGT applies the GT predicate on the "source_user_id" field.
func SourceUserIDGT(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGT(FieldSourceUserID, v))
}

// SourceUserIDGTE applies the GTE predicate on the "source_user_id" field.
func SourceUserIDGTE(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGTE(FieldSourceUserID, v))
}

// SourceUserIDLT applies the LT predicate on the "source_user_id" field.
func SourceUserIDLT(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLT(FieldSourceUserID, v))
}

// SourceUserIDLTE applies the LTE predicate on the "source_user_id" field.
func SourceUserIDLTE(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLTE(FieldSourceUserID, v))
}

// SourceUserIDIsNil applies the IsNil predicate on the "source_user_id" field.
func SourceUserIDIsNil() predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldIsNull(FieldSourceUserID))
}

// SourceUserIDNotNil applies the NotNil predicate on the "source_user_id" field.
func SourceUserIDNotNil() predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNotNull(FieldSourceUserID))
}

// BusinessDateEQ applies the EQ predicate on the "business_date" field.
func BusinessDateEQ(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldBusinessDate, v))
}

// BusinessDateNEQ applies the NEQ predicate on the "business_date" field.
func BusinessDateNEQ(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNEQ(FieldBusinessDate, v))
}

// BusinessDateIn applies the In predicate on the "business_date" field.
func BusinessDateIn(vs ...time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldIn(FieldBusinessDate, vs...))
}

// BusinessDateNotIn applies the NotIn predicate on the "business_date" field.
func BusinessDateNotIn(vs ...time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNotIn(FieldBusinessDate, vs...))
}

// BusinessDateGT applies the GT predicate on the "business_date" field.
func BusinessDateGT(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGT(FieldBusinessDate, v))
}

// BusinessDateGTE applies the GTE predicate on the "business_date" field.
func BusinessDateGTE(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGTE(FieldBusinessDate, v))
}

// BusinessDateLT applies the LT predicate on the "business_date" field.
func BusinessDateLT(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLT(FieldBusinessDate, v))
}

// BusinessDateLTE applies the LTE predicate on the "business_date" field.
func BusinessDateLTE(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLTE(FieldBusinessDate, v))
}

// CommissionTypeEQ applies the EQ predicate on the "commission_type" field.
func CommissionTypeEQ(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldCommissionType, v))
}

// CommissionTypeNEQ applies the NEQ predicate on the "commission_type" field.
func CommissionTypeNEQ(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNEQ(FieldCommissionType, v))
}

// CommissionTypeIn applies the In predicate on the "commission_type" field.
func CommissionTypeIn(vs ...string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldIn(FieldCommissionType, vs...))
}

// CommissionTypeNotIn applies the NotIn predicate on the "commission_type" field.
func CommissionTypeNotIn(vs ...string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNotIn(FieldCommissionType, vs...))
}

// CommissionTypeGT applies the GT predicate on the "commission_type" field.
func CommissionTypeGT(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGT(FieldCommissionType, v))
}

// CommissionTypeGTE applies the GTE predicate on the "commission_type" field.
func CommissionTypeGTE(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGTE(FieldCommissionType, v))
}

// CommissionTypeLT applies the LT predicate on the "commission_type" field.
func CommissionTypeLT(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLT(FieldCommissionType, v))
}

// CommissionTypeLTE applies the LTE predicate on the "commission_type" field.
func CommissionTypeLTE(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLTE(FieldCommissionType, v))
}

// CommissionTypeContains applies the Contains predicate on the "commission_type" field.
func CommissionTypeContains(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldContains(FieldCommissionType, v))
}

// CommissionTypeHasPrefix applies the HasPrefix predicate on the "commission_type" field.
func CommissionTypeHasPrefix(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldHasPrefix(FieldCommissionType, v))
}

// CommissionTypeHasSuffix applies the HasSuffix predicate on the "commission_type" field.
func CommissionTypeHasSuffix(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldHasSuffix(FieldCommissionType, v))
}

// CommissionTypeEqualFold applies the EqualFold predicate on the "commission_type" field.
func CommissionTypeEqualFold(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEqualFold(FieldCommissionType, v))
}

// CommissionTypeContainsFold applies the ContainsFold predicate on the "commission_type" field.
func CommissionTypeContainsFold(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldContainsFold(FieldCommissionType, v))
}

// RelationDepthEQ applies the EQ predicate on the "relation_depth" field.
func RelationDepthEQ(v int8) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldRelationDepth, v))
}

// RelationDepthNEQ applies the NEQ predicate on the "relation_depth" field.
func RelationDepthNEQ(v int8) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNEQ(FieldRelationDepth, v))
}

// RelationDepthIn applies the In predicate on the "relation_depth" field.
func RelationDepthIn(vs ...int8) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldIn(FieldRelationDepth, vs...))
}

// RelationDepthNotIn applies the NotIn predicate on the "relation_depth" field.
func RelationDepthNotIn(vs ...int8) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNotIn(FieldRelationDepth, vs...))
}

// RelationDepthGT applies the GT predicate on the "relation_depth" field.
func RelationDepthGT(v int8) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGT(FieldRelationDepth, v))
}

// RelationDepthGTE applies the GTE predicate on the "relation_depth" field.
func RelationDepthGTE(v int8) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGTE(FieldRelationDepth, v))
}

// RelationDepthLT applies the LT predicate on the "relation_depth" field.
func RelationDepthLT(v int8) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLT(FieldRelationDepth, v))
}

// RelationDepthLTE applies the LTE predicate on the "relation_depth" field.
func RelationDepthLTE(v int8) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLTE(FieldRelationDepth, v))
}

// LevelIDEQ applies the EQ predicate on the "level_id" field.
func LevelIDEQ(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldLevelID, v))
}

// LevelIDNEQ applies the NEQ predicate on the "level_id" field.
func LevelIDNEQ(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNEQ(FieldLevelID, v))
}

// LevelIDIn applies the In predicate on the "level_id" field.
func LevelIDIn(vs ...int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldIn(FieldLevelID, vs...))
}

// LevelIDNotIn applies the NotIn predicate on the "level_id" field.
func LevelIDNotIn(vs ...int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNotIn(FieldLevelID, vs...))
}

// LevelIDGT applies the GT predicate on the "level_id" field.
func LevelIDGT(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGT(FieldLevelID, v))
}

// LevelIDGTE applies the GTE predicate on the "level_id" field.
func LevelIDGTE(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGTE(FieldLevelID, v))
}

// LevelIDLT applies the LT predicate on the "level_id" field.
func LevelIDLT(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLT(FieldLevelID, v))
}

// LevelIDLTE applies the LTE predicate on the "level_id" field.
func LevelIDLTE(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLTE(FieldLevelID, v))
}

// LevelIDIsNil applies the IsNil predicate on the "level_id" field.
func LevelIDIsNil() predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldIsNull(FieldLevelID))
}

// LevelIDNotNil applies the NotNil predicate on the "level_id" field.
func LevelIDNotNil() predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNotNull(FieldLevelID))
}

// LevelSnapshotEQ applies the EQ predicate on the "level_snapshot" field.
func LevelSnapshotEQ(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldLevelSnapshot, v))
}

// LevelSnapshotNEQ applies the NEQ predicate on the "level_snapshot" field.
func LevelSnapshotNEQ(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNEQ(FieldLevelSnapshot, v))
}

// LevelSnapshotIn applies the In predicate on the "level_snapshot" field.
func LevelSnapshotIn(vs ...string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldIn(FieldLevelSnapshot, vs...))
}

// LevelSnapshotNotIn applies the NotIn predicate on the "level_snapshot" field.
func LevelSnapshotNotIn(vs ...string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNotIn(FieldLevelSnapshot, vs...))
}

// LevelSnapshotGT applies the GT predicate on the "level_snapshot" field.
func LevelSnapshotGT(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGT(FieldLevelSnapshot, v))
}

// LevelSnapshotGTE applies the GTE predicate on the "level_snapshot" field.
func LevelSnapshotGTE(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGTE(FieldLevelSnapshot, v))
}

// LevelSnapshotLT applies the LT predicate on the "level_snapshot" field.
func LevelSnapshotLT(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLT(FieldLevelSnapshot, v))
}

// LevelSnapshotLTE applies the LTE predicate on the "level_snapshot" field.
func LevelSnapshotLTE(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLTE(FieldLevelSnapshot, v))
}

// LevelSnapshotContains applies the Contains predicate on the "level_snapshot" field.
func LevelSnapshotContains(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldContains(FieldLevelSnapshot, v))
}

// LevelSnapshotHasPrefix applies the HasPrefix predicate on the "level_snapshot" field.
func LevelSnapshotHasPrefix(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldHasPrefix(FieldLevelSnapshot, v))
}

// LevelSnapshotHasSuffix applies the HasSuffix predicate on the "level_snapshot" field.
func LevelSnapshotHasSuffix(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldHasSuffix(FieldLevelSnapshot, v))
}

// LevelSnapshotIsNil applies the IsNil predicate on the "level_snapshot" field.
func LevelSnapshotIsNil() predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldIsNull(FieldLevelSnapshot))
}

// LevelSnapshotNotNil applies the NotNil predicate on the "level_snapshot" field.
func LevelSnapshotNotNil() predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNotNull(FieldLevelSnapshot))
}

// LevelSnapshotEqualFold applies the EqualFold predicate on the "level_snapshot" field.
func LevelSnapshotEqualFold(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEqualFold(FieldLevelSnapshot, v))
}

// LevelSnapshotContainsFold applies the ContainsFold predicate on the "level_snapshot" field.
func LevelSnapshotContainsFold(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldContainsFold(FieldLevelSnapshot, v))
}

// RateSnapshotEQ applies the EQ predicate on the "rate_snapshot" field.
func RateSnapshotEQ(v float64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldRateSnapshot, v))
}

// RateSnapshotNEQ applies the NEQ predicate on the "rate_snapshot" field.
func RateSnapshotNEQ(v float64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNEQ(FieldRateSnapshot, v))
}

// RateSnapshotIn applies the In predicate on the "rate_snapshot" field.
func RateSnapshotIn(vs ...float64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldIn(FieldRateSnapshot, vs...))
}

// RateSnapshotNotIn applies the NotIn predicate on the "rate_snapshot" field.
func RateSnapshotNotIn(vs ...float64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNotIn(FieldRateSnapshot, vs...))
}

// RateSnapshotGT applies the GT predicate on the "rate_snapshot" field.
func RateSnapshotGT(v float64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGT(FieldRateSnapshot, v))
}

// RateSnapshotGTE applies the GTE predicate on the "rate_snapshot" field.
func RateSnapshotGTE(v float64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGTE(FieldRateSnapshot, v))
}

// RateSnapshotLT applies the LT predicate on the "rate_snapshot" field.
func RateSnapshotLT(v float64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLT(FieldRateSnapshot, v))
}

// RateSnapshotLTE applies the LTE predicate on the "rate_snapshot" field.
func RateSnapshotLTE(v float64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLTE(FieldRateSnapshot, v))
}

// RateSnapshotIsNil applies the IsNil predicate on the "rate_snapshot" field.
func RateSnapshotIsNil() predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldIsNull(FieldRateSnapshot))
}

// RateSnapshotNotNil applies the NotNil predicate on the "rate_snapshot" field.
func RateSnapshotNotNil() predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNotNull(FieldRateSnapshot))
}

// BaseAmountEQ applies the EQ predicate on the "base_amount" field.
func BaseAmountEQ(v float64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldBaseAmount, v))
}

// BaseAmountNEQ applies the NEQ predicate on the "base_amount" field.
func BaseAmountNEQ(v float64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNEQ(FieldBaseAmount, v))
}

// BaseAmountIn applies the In predicate on the "base_amount" field.
func BaseAmountIn(vs ...float64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldIn(FieldBaseAmount, vs...))
}

// BaseAmountNotIn applies the NotIn predicate on the "base_amount" field.
func BaseAmountNotIn(vs ...float64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNotIn(FieldBaseAmount, vs...))
}

// BaseAmountGT applies the GT predicate on the "base_amount" field.
func BaseAmountGT(v float64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGT(FieldBaseAmount, v))
}

// BaseAmountGTE applies the GTE predicate on the "base_amount" field.
func BaseAmountGTE(v float64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGTE(FieldBaseAmount, v))
}

// BaseAmountLT applies the LT predicate on the "base_amount" field.
func BaseAmountLT(v float64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLT(FieldBaseAmount, v))
}

// BaseAmountLTE applies the LTE predicate on the "base_amount" field.
func BaseAmountLTE(v float64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLTE(FieldBaseAmount, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLTE(FieldAmount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldContainsFold(FieldStatus, v))
}

// SettlementBatchIDEQ applies the EQ predicate on the "settlement_batch_id" field.
func SettlementBatchIDEQ(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldSettlementBatchID, v))
}

// SettlementBatchIDNEQ applies the NEQ predicate on the "settlement_batch_id" field.
func SettlementBatchIDNEQ(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNEQ(FieldSettlementBatchID, v))
}

// SettlementBatchIDIn applies the In predicate on the "settlement_batch_id" field.
func SettlementBatchIDIn(vs ...int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldIn(FieldSettlementBatchID, vs...))
}

// SettlementBatchIDNotIn applies the NotIn predicate on the "settlement_batch_id" field.
func SettlementBatchIDNotIn(vs ...int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNotIn(FieldSettlementBatchID, vs...))
}

// SettlementBatchIDGT applies the GT predicate on the "settlement_batch_id" field.
func SettlementBatchIDGT(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGT(FieldSettlementBatchID, v))
}

// SettlementBatchIDGTE applies the GTE predicate on the "settlement_batch_id" field.
func SettlementBatchIDGTE(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGTE(FieldSettlementBatchID, v))
}

// SettlementBatchIDLT applies the LT predicate on the "settlement_batch_id" field.
func SettlementBatchIDLT(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLT(FieldSettlementBatchID, v))
}

// SettlementBatchIDLTE applies the LTE predicate on the "settlement_batch_id" field.
func SettlementBatchIDLTE(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLTE(FieldSettlementBatchID, v))
}

// SettlementBatchIDIsNil applies the IsNil predicate on the "settlement_batch_id" field.
func SettlementBatchIDIsNil() predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldIsNull(FieldSettlementBatchID))
}

// SettlementBatchIDNotNil applies the NotNil predicate on the "settlement_batch_id" field.
func SettlementBatchIDNotNil() predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNotNull(FieldSettlementBatchID))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldHasSuffix(FieldNote, v))
}

// NoteIsNil applies the IsNil predicate on the "note" field.
func NoteIsNil() predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldIsNull(FieldNote))
}

// NoteNotNil applies the NotNil predicate on the "note" field.
func NoteNotNil() predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNotNull(FieldNote))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldContainsFold(FieldNote, v))
}

// CreatedByUserIDEQ applies the EQ predicate on the "created_by_user_id" field.
func CreatedByUserIDEQ(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldCreatedByUserID, v))
}

// CreatedByUserIDNEQ applies the NEQ predicate on the "created_by_user_id" field.
func CreatedByUserIDNEQ(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNEQ(FieldCreatedByUserID, v))
}

// CreatedByUserIDIn applies the In predicate on the "created_by_user_id" field.
func CreatedByUserIDIn(vs ...int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldIn(FieldCreatedByUserID, vs...))
}

// CreatedByUserIDNotIn applies the NotIn predicate on the "created_by_user_id" field.
func CreatedByUserIDNotIn(vs ...int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNotIn(FieldCreatedByUserID, vs...))
}

// CreatedByUserIDGT applies the GT predicate on the "created_by_user_id" field.
func CreatedByUserIDGT(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGT(FieldCreatedByUserID, v))
}

// CreatedByUserIDGTE applies the GTE predicate on the "created_by_user_id" field.
func CreatedByUserIDGTE(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGTE(FieldCreatedByUserID, v))
}

// CreatedByUserIDLT applies the LT predicate on the "created_by_user_id" field.
func CreatedByUserIDLT(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLT(FieldCreatedByUserID, v))
}

// CreatedByUserIDLTE applies the LTE predicate on the "created_by_user_id" field.
func CreatedByUserIDLTE(v int64) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLTE(FieldCreatedByUserID, v))
}

// CreatedByUserIDIsNil applies the IsNil predicate on the "created_by_user_id" field.
func CreatedByUserIDIsNil() predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldIsNull(FieldCreatedByUserID))
}

// CreatedByUserIDNotNil applies the NotNil predicate on the "created_by_user_id" field.
func CreatedByUserIDNotNil() predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNotNull(FieldCreatedByUserID))
}

// SettledAtEQ applies the EQ predicate on the "settled_at" field.
func SettledAtEQ(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldSettledAt, v))
}

// SettledAtNEQ applies the NEQ predicate on the "settled_at" field.
func SettledAtNEQ(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNEQ(FieldSettledAt, v))
}

// SettledAtIn applies the In predicate on the "settled_at" field.
func SettledAtIn(vs ...time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldIn(FieldSettledAt, vs...))
}

// SettledAtNotIn applies the NotIn predicate on the "settled_at" field.
func SettledAtNotIn(vs ...time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNotIn(FieldSettledAt, vs...))
}

// SettledAtGT applies the GT predicate on the "settled_at" field.
func SettledAtGT(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGT(FieldSettledAt, v))
}

// SettledAtGTE applies the GTE predicate on the "settled_at" field.
func SettledAtGTE(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGTE(FieldSettledAt, v))
}

// SettledAtLT applies the LT predicate on the "settled_at" field.
func SettledAtLT(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLT(FieldSettledAt, v))
}

// SettledAtLTE applies the LTE predicate on the "settled_at" field.
func SettledAtLTE(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLTE(FieldSettledAt, v))
}

// SettledAtIsNil applies the IsNil predicate on the "settled_at" field.
func SettledAtIsNil() predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldIsNull(FieldSettledAt))
}

// SettledAtNotNil applies the NotNil predicate on the "settled_at" field.
func SettledAtNotNil() predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNotNull(FieldSettledAt))
}

// CancelledAtEQ applies the EQ predicate on the "cancelled_at" field.
func CancelledAtEQ(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldCancelledAt, v))
}

// CancelledAtNEQ applies the NEQ predicate on the "cancelled_at" field.
func CancelledAtNEQ(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNEQ(FieldCancelledAt, v))
}

// CancelledAtIn applies the In predicate on the "cancelled_at" field.
func CancelledAtIn(vs ...time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldIn(FieldCancelledAt, vs...))
}

// CancelledAtNotIn applies the NotIn predicate on the "cancelled_at" field.
func CancelledAtNotIn(vs ...time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNotIn(FieldCancelledAt, vs...))
}

// CancelledAtGT applies the GT predicate on the "cancelled_at" field.
func CancelledAtGT(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGT(FieldCancelledAt, v))
}

// CancelledAtGTE applies the GTE predicate on the "cancelled_at" field.
func CancelledAtGTE(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGTE(FieldCancelledAt, v))
}

// CancelledAtLT applies the LT predicate on the "cancelled_at" field.
func CancelledAtLT(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLT(FieldCancelledAt, v))
}

// CancelledAtLTE applies the LTE predicate on the "cancelled_at" field.
func CancelledAtLTE(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLTE(FieldCancelledAt, v))
}

// CancelledAtIsNil applies the IsNil predicate on the "cancelled_at" field.
func CancelledAtIsNil() predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldIsNull(FieldCancelledAt))
}

// CancelledAtNotNil applies the NotNil predicate on the "cancelled_at" field.
func CancelledAtNotNil() predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNotNull(FieldCancelledAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PromotionCommissionRecord) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PromotionCommissionRecord) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PromotionCommissionRecord) predicate.PromotionCommissionRecord {
	return predicate.PromotionCommissionRecord(sql.NotPredicates(p))
}
