// Code generated by ent, DO NOT EDIT.

package promotionsettlementbatch

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldLTE(FieldID, id))
}

// BusinessDate applies equality check predicate on the "business_date" field. It's identical to BusinessDateEQ.
func BusinessDate(v time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldEQ(FieldBusinessDate, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldEQ(FieldStatus, v))
}

// TotalRecords applies equality check predicate on the "total_records" field. It's identical to TotalRecordsEQ.
func TotalRecords(v int) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldEQ(FieldTotalRecords, v))
}

// TotalAmount applies equality check predicate on the "total_amount" field. It's identical to TotalAmountEQ.
func TotalAmount(v float64) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldEQ(FieldTotalAmount, v))
}

// ExecutedByUserID applies equality check predicate on the "executed_by_user_id" field. It's identical to ExecutedByUserIDEQ.
func ExecutedByUserID(v int64) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldEQ(FieldExecutedByUserID, v))
}

// ExecutedAt applies equality check predicate on the "executed_at" field. It's identical to ExecutedAtEQ.
func ExecutedAt(v time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldEQ(FieldExecutedAt, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldEQ(FieldNote, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldEQ(FieldUpdatedAt, v))
}

// BusinessDateEQ applies the EQ predicate on the "business_date" field.
func BusinessDateEQ(v time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldEQ(FieldBusinessDate, v))
}

// BusinessDateNEQ applies the NEQ predicate on the "business_date" field.
func BusinessDateNEQ(v time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldNEQ(FieldBusinessDate, v))
}

// BusinessDateIn applies the In predicate on the "business_date" field.
func BusinessDateIn(vs ...time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldIn(FieldBusinessDate, vs...))
}

// BusinessDateNotIn applies the NotIn predicate on the "business_date" field.
func BusinessDateNotIn(vs ...time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldNotIn(FieldBusinessDate, vs...))
}

// BusinessDateGT applies the GT predicate on the "business_date" field.
func BusinessDateGT(v time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldGT(FieldBusinessDate, v))
}

// BusinessDateGTE applies the GTE predicate on the "business_date" field.
func BusinessDateGTE(v time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldGTE(FieldBusinessDate, v))
}

// BusinessDateLT applies the LT predicate on the "business_date" field.
func BusinessDateLT(v time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldLT(FieldBusinessDate, v))
}

// BusinessDateLTE applies the LTE predicate on the "business_date" field.
func BusinessDateLTE(v time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldLTE(FieldBusinessDate, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldContainsFold(FieldStatus, v))
}

// TotalRecordsEQ applies the EQ predicate on the "total_records" field.
func TotalRecordsEQ(v int) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldEQ(FieldTotalRecords, v))
}

// TotalRecordsNEQ applies the NEQ predicate on the "total_records" field.
func TotalRecordsNEQ(v int) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldNEQ(FieldTotalRecords, v))
}

// TotalRecordsIn applies the In predicate on the "total_records" field.
func TotalRecordsIn(vs ...int) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldIn(FieldTotalRecords, vs...))
}

// TotalRecordsNotIn applies the NotIn predicate on the "total_records" field.
func TotalRecordsNotIn(vs ...int) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldNotIn(FieldTotalRecords, vs...))
}

// TotalRecordsGT applies the GT predicate on the "total_records" field.
func TotalRecordsGT(v int) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldGT(FieldTotalRecords, v))
}

// TotalRecordsGTE applies the GTE predicate on the "total_records" field.
func TotalRecordsGTE(v int) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldGTE(FieldTotalRecords, v))
}

// TotalRecordsLT applies the LT predicate on the "total_records" field.
func TotalRecordsLT(v int) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldLT(FieldTotalRecords, v))
}

// TotalRecordsLTE applies the LTE predicate on the "total_records" field.
func TotalRecordsLTE(v int) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldLTE(FieldTotalRecords, v))
}

// TotalAmountEQ applies the EQ predicate on the "total_amount" field.
func TotalAmountEQ(v float64) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldEQ(FieldTotalAmount, v))
}

// TotalAmountNEQ applies the NEQ predicate on the "total_amount" field.
func TotalAmountNEQ(v float64) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldNEQ(FieldTotalAmount, v))
}

// TotalAmountIn applies the In predicate on the "total_amount" field.
func TotalAmountIn(vs ...float64) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldIn(FieldTotalAmount, vs...))
}

// TotalAmountNotIn applies the NotIn predicate on the "total_amount" field.
func TotalAmountNotIn(vs ...float64) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldNotIn(FieldTotalAmount, vs...))
}

// TotalAmountGT applies the GT predicate on the "total_amount" field.
func TotalAmountGT(v float64) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldGT(FieldTotalAmount, v))
}

// TotalAmountGTE applies the GTE predicate on the "total_amount" field.
func TotalAmountGTE(v float64) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldGTE(FieldTotalAmount, v))
}

// TotalAmountLT applies the LT predicate on the "total_amount" field.
func TotalAmountLT(v float64) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldLT(FieldTotalAmount, v))
}

// TotalAmountLTE applies the LTE predicate on the "total_amount" field.
func TotalAmountLTE(v float64) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldLTE(FieldTotalAmount, v))
}

// ExecutedByUserIDEQ applies the EQ predicate on the "executed_by_user_id" field.
func ExecutedByUserIDEQ(v int64) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldEQ(FieldExecutedByUserID, v))
}

// ExecutedByUserIDNEQ applies the NEQ predicate on the "executed_by_user_id" field.
func ExecutedByUserIDNEQ(v int64) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldNEQ(FieldExecutedByUserID, v))
}

// ExecutedByUserIDIn applies the In predicate on the "executed_by_user_id" field.
func ExecutedByUserIDIn(vs ...int64) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldIn(FieldExecutedByUserID, vs...))
}

// ExecutedByUserIDNotIn applies the NotIn predicate on the "executed_by_user_id" field.
func ExecutedByUserIDNotIn(vs ...int64) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldNotIn(FieldExecutedByUserID, vs...))
}

// ExecutedByUserIDGT applies the GT predicate on the "executed_by_user_id" field.
func ExecutedByUserIDGT(v int64) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldGT(FieldExecutedByUserID, v))
}

// ExecutedByUserIDGTE applies the GTE predicate on the "executed_by_user_id" field.
func ExecutedByUserIDGTE(v int64) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldGTE(FieldExecutedByUserID, v))
}

// ExecutedByUserIDLT applies the LT predicate on the "executed_by_user_id" field.
func ExecutedByUserIDLT(v int64) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldLT(FieldExecutedByUserID, v))
}

// ExecutedByUserIDLTE applies the LTE predicate on the "executed_by_user_id" field.
func ExecutedByUserIDLTE(v int64) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldLTE(FieldExecutedByUserID, v))
}

// ExecutedByUserIDIsNil applies the IsNil predicate on the "executed_by_user_id" field.
func ExecutedByUserIDIsNil() predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldIsNull(FieldExecutedByUserID))
}

// ExecutedByUserIDNotNil applies the NotNil predicate on the "executed_by_user_id" field.
func ExecutedByUserIDNotNil() predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldNotNull(FieldExecutedByUserID))
}

// ExecutedAtEQ applies the EQ predicate on the "executed_at" field.
func ExecutedAtEQ(v time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldEQ(FieldExecutedAt, v))
}

// ExecutedAtNEQ applies the NEQ predicate on the "executed_at" field.
func ExecutedAtNEQ(v time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldNEQ(FieldExecutedAt, v))
}

// ExecutedAtIn applies the In predicate on the "executed_at" field.
func ExecutedAtIn(vs ...time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldIn(FieldExecutedAt, vs...))
}

// ExecutedAtNotIn applies the NotIn predicate on the "executed_at" field.
func ExecutedAtNotIn(vs ...time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldNotIn(FieldExecutedAt, vs...))
}

// ExecutedAtGT applies the GT predicate on the "executed_at" field.
func ExecutedAtGT(v time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldGT(FieldExecutedAt, v))
}

// ExecutedAtGTE applies the GTE predicate on the "executed_at" field.
func ExecutedAtGTE(v time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldGTE(FieldExecutedAt, v))
}

// ExecutedAtLT applies the LT predicate on the "executed_at" field.
func ExecutedAtLT(v time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldLT(FieldExecutedAt, v))
}

// ExecutedAtLTE applies the LTE predicate on the "executed_at" field.
func ExecutedAtLTE(v time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldLTE(FieldExecutedAt, v))
}

// ExecutedAtIsNil applies the IsNil predicate on the "executed_at" field.
func ExecutedAtIsNil() predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldIsNull(FieldExecutedAt))
}

// ExecutedAtNotNil applies the NotNil predicate on the "executed_at" field.
func ExecutedAtNotNil() predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldNotNull(FieldExecutedAt))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldHasSuffix(FieldNote, v))
}

// NoteIsNil applies the IsNil predicate on the "note" field.
func NoteIsNil() predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldIsNull(FieldNote))
}

// NoteNotNil applies the NotNil predicate on the "note" field.
func NoteNotNil() predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldNotNull(FieldNote))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldContainsFold(FieldNote, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PromotionSettlementBatch) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PromotionSettlementBatch) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PromotionSettlementBatch) predicate.PromotionSettlementBatch {
	return predicate.PromotionSettlementBatch(sql.NotPredicates(p))
}
